### ISSUE TITLE
Possible to delay chat?

### ISSUE THREAD

**Issue by Yoirkie** [Chatterino/chatterino2#1699] opened 2020-05-20 22:03 UTC
Since I use livestreamer, theres like a 10s lag. Would it be possible to delay chat from real time?

**Comment by Mm2PL** [comment] 2020-05-20 22:04
not a Chatterino issue,
related to #1666 as it's IRCs fault
please use the templates that were created, they are here to help you make a good issue

**Comment by apa420** [comment] 2020-05-22 17:03
duplicate of #645

**Closed by apa420** 2020-05-22 17:03 UTC
