### ISSUE TITLE
Colored usernames in @mentions in chat

### ISSUE THREAD

**Issue by Sjorsa** [Chatterino/chatterino2#2507] opened 2021-03-09 13:18 UTC
**What should be added?**

Under miscellaneous settings you can make usernames bold and give them a different font weight. (also for usernames without an @) It would be handy if those bold usernames also took on the color of the specific user.
**Why should it be added?**

This would make it easier to follow conversations in a chat.
Also, to be clear, I'm not talking about the username that is before a message, but a username that someone mentions when talking to someone.

**Comment by Mm2PL** [comment] 2021-03-09 13:22
already in nightly, duplicate of #2121

**Comment by Sjorsa** [comment] 2021-03-09 16:54
Oops, I searched for color but didn't search for closed issues. Is there any indication when it would be in the main version? If it's not close yet then I might use the nightly, is it stable?

**Comment by pajlada** [comment] 2021-03-11 23:31
Duplicate of #2121
There's always the nightly version available here on github releases https://github.com/Chatterino/chatterino2/releases/tag/nightly-build if you want to try the feature out before the next stable release is available for any feedback you might have.

**Closed by pajlada** 2021-03-11 23:31 UTC
Labels: enhancement
