### ISSUE TITLE
Chatterino Disconnecting 

### ISSUE THREAD

**Issue by benjiPKS** [Chatterino/chatterino2#3111] opened 2021-08-03 08:42 UTC
So for the past few hours it says connected "insert streamer name here" is live then proceeds to constantly say reconnected. ive tried logging out, ending chatterino task and restarting my computer.

   
![image](https://user-images.githubusercontent.com/73210322/127985379-283a6328-658d-4665-a353-802749052a3e.png)

Windows 10 19042.1110
Chatterino Nightly 7.3.2 (commit 68659eb2c, )

**Comment by ALazyMeme** [comment] 2021-08-03 08:43
Please search for other issues prior to creating new ones.

Duplicate of https://github.com/Chatterino/chatterino2/issues/3107

**Closed by ALazyMeme** 2021-08-03 08:43 UTC
Labels: bug

**Comment by benjiPKS** [comment] 2021-08-03 08:46
FeelsDankMan my bad i didnt see it. dyslexia at its finest

**Comment by zneix** [comment] 2021-08-03 08:46
Pinned issue btw...
