### ISSUE TITLE
Mentioning users with tab defaults to all lowercase letters

### ISSUE THREAD

**Issue by Bucket69** [Chatterino/chatterino2#1390] opened 2019-10-26 21:07 UTC
Using tab to mention a user doesn't copy the uppercase letters in their name and that used to be a working feature before these major updates. If I wanted to @ someone with the name "TestUser" with tab and type something like @tes and hit tab  then it would show up as @testuser rather than @TestUser

**Comment by cinemassacres** [comment] 2019-10-27 03:38
https://github.com/Chatterino/chatterino2/issues/1199

**Comment by fourtf** [comment] 2019-10-27 19:39
duplicate of #1199

**Closed by fourtf** 2019-10-27 19:39 UTC
Labels: bug, needs triage
