### ISSUE TITLE
Remove sensitive data from Settings/settings.json

### ISSUE THREAD

**Issue by Vanidor** [Chatterino/chatterino2#4561] opened 2023-04-19 09:25 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I want to be able to synchronize my settings between multiple computers, but the sensitive data in `Settings/settings.json` is stopping me from being able to do it.

### OS and Chatterino Version

Windows 11, Chatterino 2.4.2 (this release https://github.com/Chatterino/chatterino2/releases/tag/v2.4.2)

**Comment by Vanidor** [comment] 2023-04-19 09:26
A solution could be to store the sensitive data in a different file that can be easily excluded from synchronizing it. `Settings/sensitive-settings.json` for example

**Comment by leon-richardt** [comment] 2023-04-19 09:32
Duplicate of #1099.

**Closed by leon-richardt** 2023-04-19 09:32 UTC
Labels: enhancement, issue-report
