### ISSUE TITLE
2 bugs with the new 2.1.6 i noticed , new user here.

### ISSUE THREAD

**Issue by Tho0mgarlic** [Chatterino/chatterino2#1465] opened 2019-12-29 10:01 UTC
**Describe the bug**

two bugs 
a) when i hover over link from different chat , the current Chatterino tab get unselected , wasnt the case in previous Chatterinos. 
b) emote preview icon on the bottom right of every chat is broken ??! or idk 
**To reproduce**

for issue a) hover over links , while opening multiple tabs in chattirno , make the current tab unselected and therefore its the issue 
for issue b) click on emote preview icon , and see the screenshot below 
**Screenshots**

im not able to capture issue a) since its dynamic cant be screenshotted , 
issue b) 
  https://imgur.com/GIBlQMn and https://imgur.com/Jdj4PVd  
**Chatterino version**

im using Chatterino 2.1.6 portable version or Chatterino 2.1.6 (commit c5e8c5396)
**Operating system**

Windows 7 
**Additional information**

if there's no quick fix is there a way to rollback to 2.1.5 portable , thanks in advance

**Comment by fourtf** [comment] 2019-12-29 10:17
a) is fixed in https://github.com/Chatterino/chatterino2/commit/443aba3f9cfb07ee42d7d78f9e0b0bebc1c71a75
and I can't reproduce b) so I'll close it

In the future please create one issue per bug 👍

**Closed by fourtf** 2019-12-29 10:17 UTC
Labels: bug, needs triage

**Comment by Tho0mgarlic** [comment] 2019-12-29 10:54
thanks for the help !
