### ISSUE TITLE
Emote AutoComplete suggestion

### ISSUE THREAD

**Issue by SPONGSPong** [Chatterino/chatterino2#1438] opened 2019-12-12 15:31 UTC
is it possible to make emote autocomplete to be like this?
like when you type ":forsenh" and then emote will show like forsenHappy, forsenHobo, and else.. 

![image](https://user-images.githubusercontent.com/58819884/70724537-6137c480-1d2d-11ea-81b4-df4584450b4f.png)

**Comment by apa420** [comment] 2019-12-12 18:06
Duplicate of #591

**Closed by apa420** 2019-12-12 18:06 UTC
