### ISSUE TITLE
Update Button Not Accessable

### ISSUE THREAD

**Issue by Kaosarbitrium** [Chatterino/chatterino2#3019] opened 2021-07-15 23:17 UTC
**Self-Updating feature is unusable**

    When there's an update, you get the downward arrow button, bringing up a prompt saying "Your version is out of date! Would you like to update?", insinuating that there should be some "Yes" response button that downloads the appropriate .exe file and begins the install process. If nothing else, it should take me to the download location so I can do it easier. 
    However: That button isn't visible when the Chatterino client is in position over the default Twitch Chat position. There's just, a large blank area where *something* is supposed to be, under the cut-off text. The bottons are there, but the window for it is extremely wide and goes to the right of the screen. The window does not wrap around to stay in the confines of the Chatterino window size, meaning it's very easy for it to be off screen, especially if you have your Chatterino Window on the right side of the screen.

**Screenshots**
[The Chatterino client positioned in the center of the screen, with the update window open](https://gyazo.com/efee3934d87f0f5adcf3719477cf2312)

[The Chatterino client positioned over the default location of the Twitch chat, the right side of the screen, with the update window open](https://gyazo.com/35ac1b5e0562a6345b1cd7c3d5726525)

**OS and Chatterino Version**
        Windows 10, Chatterino 2.3.3 Beta, issue prevalent since Chatterino 2.1.0 on same platform

**Comment by zneix** [comment] 2021-07-16 00:12
Duplicate of #2123

**Closed by zneix** 2021-07-16 00:12 UTC
Labels: issue-report
