### ISSUE TITLE
Make it so ignored phrases show up normally in internal logging

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#1330] opened 2019-09-22 20:09 UTC
**Is your feature request related to a problem? Please describe.**

Currently ignored phrases are applied before logging, so chatterino logs are altered by ignored phrases.

[2019-09-22 19:58:31] #pajlada felanbird: KEKW
![image](https://user-images.githubusercontent.com/41973452/65393686-ea081b00-dd51-11e9-8769-628aced47a89.png)
[15:58:32]  felanbird: xqcP

1: External Logging
2: Chatterino Screenshot
3: Chatterino Log

**Describe the solution you'd like**

I think the only real way this could be fixed is if the logging happened before ignored phrases were applied. 

**Additional context**

It's probably a shot in the dark suggestion but eShrug 
![image](https://user-images.githubusercontent.com/41973452/65393771-2c7e2780-dd53-11e9-95bd-2c275c9530d2.png)

**Comment by pajlada** [comment] 2020-12-05 11:26
As a chat client, Chatterino is logging what's printed on the screen.
Not a bug, won't fix. Sorry for the delayed closing of the issue.

**Closed by pajlada** 2020-12-05 11:26 UTC
Labels: bug
