### ISSUE TITLE
Always-on-top Highlights

### ISSUE THREAD

**Issue by Chomchaum** [Chatterino/chatterino2#2277] opened 2020-12-13 20:25 UTC
Would be nice to have pop-up notification for highlights, which would be always-on-top mainly if window isn not AoT.
It may allow people to choose notification's screen (for multiple screen setups) and position (top left, top right, bottom left, bottom right)

Sometimes you hear HL sound but you'd just like to see what has been said.

**Comment by zneix** [comment] 2020-12-21 21:53
I think supporting native desktop notifications (if possible) would be a cool solution for this as well.

**Comment by apa420** [comment] 2021-01-02 05:32
Duplicate of #398.
If this is not what you meant, you can explain why and reopen the issue.

**Closed by apa420** 2021-01-02 05:32 UTC
Labels: enhancement

**Comment by alazymeme** [comment] 2021-01-02 11:05
Fairly sure users can't reopen issues if they're closed by a repo admin
