### ISSUE TITLE
Show Timeout Timer

### ISSUE THREAD

**Issue by James-SSH** [Chatterino/chatterino2#2456] opened 2021-02-14 03:46 UTC
It would be nice if somewhere in the UI there was a timer present to check how long you have left on your timeout

**Comment by Mm2PL** [comment] 2021-02-14 17:04
Duplicates #870, which fourtf decided to be out of scope of the Chatterino project.

**Comment by zneix** [comment] 2021-04-15 10:54
Duplicate of #870

**Closed by zneix** 2021-04-15 10:54 UTC
