### ISSUE TITLE
Crash when removing list item in settings

### ISSUE THREAD

**Issue by sando** [Chatterino/chatterino2#1937] opened 2020-09-03 03:14 UTC
**Describe the bug**
Chatterino will crash when attempting to remove an item from a table view in any of the settings pages. Setting the item to blank works around it, but then you're left with an orphan item. Tested with a blank profile.

**To reproduce**
1. Open settings dialog
2. Go to *Commands*, or any other settings page with a table view
3. Add item
4. Remove item

**Screenshots**
Exception/stack trace:
![image](https://user-images.githubusercontent.com/58441/92067284-450e1300-ede7-11ea-9173-118e1d5a8768.png)

**Chatterino version**
Chatterino 2.2.2 (commit cbcd5f386)

**Operating system**
Windows 10 2004

**Comment by leon-richardt** [comment] 2020-09-11 17:16
Duplicate of https://github.com/Chatterino/chatterino2/issues/1529.

**Comment by apa420** [comment] 2020-09-11 17:19
Duplicate of #1529

**Closed by apa420** 2020-09-11 17:19 UTC
Labels: bug, needs triage

**Comment by pajlada** [comment] 2020-09-13 09:11
Thank you for the detailed bug report, the screenshot helps a ton.
I've gone ahead and split up a few of the vector accesses in that class in https://github.com/Chatterino/chatterino2/commit/7eabba959b0374abb16ebf2dbeba157901cb3303 - if you run into this again, please post an update in #1529
