### ISSUE TITLE
Emote menu cluttered with permanent twitch event emotes

### ISSUE THREAD

**Issue by c0ldplasma** [Chatterino/chatterino2#2954] opened 2021-07-04 12:57 UTC
**Describe your issue**

As you can see in the Screenshot below my emote menu is cluttered with permanent twitch seasonal/event emotes. I almost never use these emotes so i always have to scroll through them to get to my sub emotes.

**Screenshots**

![Webp net-resizeimage](https://user-images.githubusercontent.com/14879514/124385584-9cfefa00-dcd6-11eb-85d9-24b99caa468a.png)

**Comment by c0ldplasma** [comment] 2021-07-04 13:01
Three different suggestions:

1.  Put seasonal/event emotes in a seperate tab instead of the sub tab in the emote menu as they aren't sub emotes after all.
2. Display them below sub emotes.
3. Option to selectively hide emote sets.

**Comment by zneix** [comment] 2021-07-04 16:11
Duplicate of #2341

**Closed by zneix** 2021-07-04 16:11 UTC
Labels: issue-report
