### ISSUE TITLE
Crash issue after adding an "Ignore Message"

### ISSUE THREAD

**Issue by CeciliaKM** [Chatterino/chatterino2#2705] opened 2021-04-27 14:42 UTC
When I added an "Ignore" message pattern Chatterino 2.3.0 began repeatedly crashing.
Specifically, my pattern was "o7", with regex enabled, not case sensitive, and replaced with nothing (just deleted everything in that box). I needed to go into settings to delete the pattern directly from my settings file in order to fix the crashing issue.

**Comment by apa420** [comment] 2021-08-15 15:22
Unable to reproduce on Chatterino Nightly 2.3.3 (commit 4dee7ad7 )

Closing this issue for now because you didn't use the issue template.
If the issue persists create another issue using the bug template.

**Closed by apa420** 2021-08-15 15:22 UTC
