### ISSUE TITLE
Add timeout reasons 

### ISSUE THREAD

**Issue by RandomHuman29** [Chatterino/chatterino2#1679] opened 2020-05-09 19:09 UTC
**Is your feature request related to a problem? Please describe.**
When I get timed out, I don’t see the reason I got timed out so I can not repeat the mistake

**Describe the solution you'd like**
It would be nice to be able to see the reason other users and me get timed out, it would be a cool feature as a non mod

**Comment by Mm2PL** [comment] 2020-05-09 19:10
i think this is solved in the nightlies.

**Comment by apa420** [comment] 2020-05-09 20:29
Latest nightly provides this desired behavior, it will be in an update in due time for non-nightly. #1629

**Comment by apa420** [comment] 2020-05-09 20:30
Duplicate of #962

**Closed by apa420** 2020-05-09 20:29 UTC
Labels: enhancement
