### ISSUE TITLE
Tooltips for zero-width emotes are inaccessable

### ISSUE THREAD

**Issue by jammehcow** [Chatterino/chatterino2#3615] opened 2022-03-19 22:19 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When a zero-width emote is posted along side a standard emote, only a tooltip for the standard emote is shown no matter where the mouse is hovered. 

### Screenshots

N/A

### OS and Chatterino Version

Chatterino 7.3.4 (commit 530dcc3c), applies to c2

**Comment by jammehcow** [comment] 2022-03-19 22:20
Pulled upstream from https://github.com/SevenTV/chatterino7/issues/72

**Comment by Mm2PL** [comment] 2022-03-19 22:22
To reproduce:
  1. Post `FeelsDankMan cvMask`
  2. try to hover over the cvMask emote
  3. see that there is no tooltip for it, just FeelsDankMan

FeelsDankMan

**Comment by LosFarmosCTL** [comment] 2022-08-15 10:30
I actually really like the way chatsen displays them, only thing missing would be provider information for the emotes on the bottom, and the first FeelsDankMan is kinda unnecessary, but the general layout is pretty nice imo:

![image](https://user-images.githubusercontent.com/80157503/184619859-1a2d6377-969a-48dc-bdfe-e412325e3584.jpeg)

Not sure how feasible something like that would be to implement though, given the current LIDL zero-width emote implementation.

**Comment by Mm2PL** [comment] 2022-08-15 11:05
I think we would have to rework zero width emotes to actual modifier emotes, this would probably be also mean solving that render order issue with animated emotes.

15 sie 2022 12:31:16 LosFarmosCTL ***@***.***>:

**Comment by LosFarmosCTL** [comment] 2022-08-15 16:21
> I think we would have to rework zero width emotes to actual modifier emotes

I experimented a bit with that a couple of months ago, but didn't feel like I had the knowledge about neither C++, qt or the c2 codebase to tackle this, and I don't think I would feel comfortable working on it now as well.

From what I could tell though this will require some pretty drastic changes to both emote and even general rendering, considering that not only are emotes being drawn completely separately, but animated images are even rendered in a completely separate method and canvas compared to normal UI elements (which is also the reason why they are drawn above non-animated zero-width emotes, they are actually just drawn later on top of the entire UI)

Maybe we could actually create separate emotes for combinations of emote+zerowidth, but this would create additional memory usage and would definitely still be a hacky solution, I can conceive of a bunch of possible side effects even by just thinking about it for a few seconds.

Whatever way a refactor like that could be going, its almost certainly going to take a very long time to get merged, if it ever happens. Not sure if that warrants slapping more hacky code on top of already messy things, but there might be no other way to fix current issues.

**Closed** 2023-03-18 16:30 UTC
Labels: bug, Feature: Emotes
