### ISSUE TITLE
Connecting entered Emote to channel source. 

### ISSUE THREAD

**Issue by Reallifetsundere** [Chatterino/chatterino2#1848] opened 2020-08-09 20:36 UTC
**What should be added?**

(I'm sorry if this was suggested already as this is my first time using github)
 
     The idea is when a user enters an emote in chat, the emote should be able to be clicked on to have a small window popped up and see the link for the channel it belongs to as well as to be able to have a follow button to follow it if you should choose to, much like the original site, but Chatterino is much easier and lighter to use. 

**Why should it be added?**
     There are times where I find and spot an awesome emote on chatterino but there is no way to find out who's channel it belongs to other than the little info you get from hovering it. Left clicking on the emote currently does nothing unless I am not aware of a setting I missed. Right clicking links me to its emote sizes for some reason such as 1x 2x or 3x in sizes. It would definitely be a quality of life if this were featured in.

(Again, sorry if this was already requested)

**Comment by cinemassacres** [comment] 2020-08-10 02:15
Duplicate of #1735

**Comment by apa420** [comment] 2020-08-10 11:09
Duplicate of #1735

**Closed by apa420** 2020-08-10 11:09 UTC
Labels: enhancement, needs triage
