### ISSUE TITLE
chatterino 2.3.0 does not work 

### ISSUE THREAD

**Issue by baechu69** [Chatterino/chatterino2#2666] opened 2021-04-22 22:05 UTC
i updated from 2.2.2 to 2.3.0 and it won't connect to the channels, i have tried to remove the account and re enter the account, i have also tried to do a clean uninstall and re install. if anyone has a fix or if the devs can look in to it

**Comment by jammehcow** [comment] 2021-04-22 23:50
Have you gone through all steps on the wiki?
https://wiki.chatterino.com/Help/#chatterino-not-startingcrashing-upon-startup

**Comment by InvertedFire** [comment] 2021-04-23 03:55
I am having the same issue right after updating from version 2.2.3-beta2 where the program doesn't respond even after trying the step @jammehcow mentioned from the Basic Troubleshooting.

**Comment by zneix** [comment] 2021-04-23 06:32
@InvertedFire could you give nightly release a try? I talked to a few users who had the same issue; switching to nightly had fixed their issues.

1. Go [here](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build) and (I assume you're a windows user) download `test-cmake-chatterino-windows-x86-64.zip`.
2. Extract it.
3. Import the files in "C:\Program Files\Chatterino" (or whereever your Chatterino files are located).
4. Start the app and see if it works, it should say `Chatterino Nightly 2.3.0` in the title bar if you've done all of it correctly.

**Comment by piggeywig2000** [comment] 2021-04-23 19:24
> @InvertedFire could you give nightly release a try? I talked to a few users who had the same issue; switching to nightly had fixed their issues.
> 
> 1. Go [here](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build) and (I assume you're a windows user) download `test-cmake-chatterino-windows-x86-64.zip`.
> 2. Extract it.
> 3. Import the files in "C:\Program Files\Chatterino" (or whereever your Chatterino files are located).
> 4. Start the app and see if it works, it should say `Chatterino Nightly 2.3.0` in the title bar if you've done all of it correctly.

I was having a similar issue after upgrading to 2.3.0 and this fixed it.

Chatterino would often freeze and say Not Responding, and it would stay like this until I forcibly closed it. This would happen on startup if I had channels open, and it would often happen upon adding a new channel. If I deleted my `window-layout.json` from AppData and started Chatterino it wouldn't freeze, but it would after adding one or two channels.

If Chatterino didn't freeze after adding a new channel, the UI would also sometimes feel quite unresponsive immediately after adding a new channel, but this would only last for less than a second.

It sounds like I'm not the only one with this issue, so hopefully this helps to find the cause.

**Comment by alazymeme** [comment] 2021-04-24 01:36
https://discord.com/channels/253897423439659008/459650160658481152/835275384378753074

Someone on the discord said your thing fixed it @zneix

**Comment by leon-richardt** [comment] 2021-04-24 06:47
So, what's different about the way nightlies are built compared to the way the release build as built?

**Comment by zneix** [comment] 2021-04-24 07:07
> So, what's different about the way nightlies are built compared to the way the release build was built?

I know that for windows build, it was built by @fourtf with qmake and nightlies are from CI.

**Comment by Wilkolicious** [comment] 2021-05-05 21:35
I was also having trouble with 2.3.0 at startup - it would open but then just get "stuck" for a few mins.  Clicking anywhere prompted the "not responding" dialogue box. 

https://github.com/Chatterino/chatterino2/issues/2666#issuecomment-825424260 fixed this for me.

**Comment by zneix** [comment] 2021-05-06 11:13
does this still occur after clearing your cache and updating to 2.3.1? If not, also try [nightly](https://wiki.chatterino.com/Help/#what-is-nightly-and-how-to-use-install-it) and see if it fixes the issue.

**Comment by piggeywig2000** [comment] 2021-05-06 14:05
Updated to 2.3.1 and the issue is still there. Changing to the latest nightly fixed it though.

**Comment by alefbeo** [comment] 2021-05-16 22:43
Still having similar issues on the Windows stable & beta builds, even through 2.3.1 and 2.3.2 beta. Not only is there lag at startup, but randomly while using the program. I tried a fresh install/wipe of Chatterino without any positive results. 

Interestingly, I noticed the lag seems to disappear on the nightly, portable, and the macOS versions. I have similar or identical settings, so not sure what's happening. 

Just wanted to report, hopefully this can help

**Comment by guirc99** [comment] 2021-05-21 19:01
Same stuff as https://github.com/Chatterino/chatterino2/issues/2666#issuecomment-841888050. Only nightly builds work (Windows 10 1607 (RS1) LTSB).

**Comment by ALazyMeme** [comment] 2021-07-14 12:00
Issue still in 2.3.3-beta?

**Comment by alefbeo** [comment] 2021-07-21 10:22
Lag and issues connecting to channels appear to be fixed on 2.3.3!

**Closed** 2021-07-25 10:45 UTC
Labels: bug
