### ISSUE TITLE
Emote window position isnt saved after restarting Chatterino

### ISSUE THREAD

**Issue by makedir** [Chatterino/chatterino2#5414] opened 2024-05-21 06:11 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Emote window position isnt saved afer restarting Chatterino, always spawns on left top corner. Please give option to make it always spawn left or right next to Chaterino window.

### OS and Chatterino Version

2.5.1 Windows 11

**Comment by Felanbird** [comment] 2024-05-21 06:54
Cannot replicate on windows 10

**Comment by CaptainFlint** [comment] 2024-05-21 12:06
I have the same issue on Windows 10. I open Chatterino, click the emotes button to open the dialog. Move it to some place, change its size; the resulting position is like this:

![image](https://github.com/Chatterino/chatterino2/assets/6475044/a2726a48-b2da-4394-968d-115b5759b8a5)
[Full size image](https://github.com/Chatterino/chatterino2/assets/6475044/4adbefcc-7eb3-4100-83bb-fad91ef39e10)

Then I restart Chatterino, open the emotes dialog again, and it appears like this:

![image](https://github.com/Chatterino/chatterino2/assets/6475044/ae2d602a-5c99-49d1-85a5-d7c0fc0fa24a)
[Full size image](https://github.com/Chatterino/chatterino2/assets/6475044/e4c7129d-63d4-4e88-b36c-e2a88023015f)

Neither position, nor size are remembered. The dialog is not even fully visible, part of it is hidden beyond the lower border of the screen (if I pull the dialog up without changing its size, there will be two extra lines of emotes visible).

I had this behavior for as long as I can remember, even when I was working in Windows 7. I just never got around to reporting it.

**Comment by Nerixyz** [comment] 2024-05-21 16:23
I noticed the emote window moves by 8 pixels every time it's reopened. For me on Windows 10, the following change fixes this: https://github.com/Nerixyz/chatterino2/commit/7303c13d014cfc3980c270e49161b4f67b2b2611

However, I can't replicate the emote window moving more than 8px. It might be good to mention if you're using any high-DPI scaling or change your monitor layout frequently.

**Comment by CaptainFlint** [comment] 2024-05-21 16:47
My display configuration is a single monitor 2560x1440 resolution, default 100% scaling.

I also noticed that the windows:emotePopup:x/y in window-layout.json are used for restoring the position, but these values are never saved by Chatterino. No matter where I move the dialog over the screen, those x/y coordinates in the json file are never updated. But if I edit them manually, next time I open the emote dialog its position reflects the change. (And, of course, there are no issues with write access or anything stupid like that, I checked; other data in the same file are updated properly.)

Also, indeed, there is a shift in those coordinates. I made a screenshot of the whole display and measured the 0-based coordinates of the top left corner after moving the dialog, wrote them into the json, and next time the dialog is opened it's displaced by (-8, -1) compared to what is written in the JSON.

**Comment by Nerixyz** [comment] 2024-05-21 18:21
> I also noticed that the windows:emotePopup:x/y in window-layout.json are used for restoring the position, but these values are never saved by Chatterino. No matter where I move the dialog over the screen, those x/y coordinates in the json file are never updated.

Chatterino doesn't record the position of the emote popup until it's closed, and doesn't save it until the main app is closed, or a window is moved/resized. I've added that in my branch.

**Comment by CaptainFlint** [comment] 2024-05-21 19:00
Of course, I was checking the JSON file only after closing the application, not while it was running. Sorry, should have mentioned it, but thought it was obvious.

Also, while we're at it, why is only the position of the emotes dialog processed and not the size? For the main window size is also stored. It would make sense to keep/restore the emotes dialog size too.

**Comment by Nerixyz** [comment] 2024-05-21 20:28
> Also, while we're at it, why is only the position of the emotes dialog processed and not the size? For the main window size is also stored. It would make sense to keep/restore the emotes dialog size too.

That's a good idea. I've done that in the PR. Ideally, we'd do that for more windows (e.g. the settings window - https://github.com/Chatterino/chatterino2/issues/2583) in the future. It also resolves the invisible-bounds issue.

**Comment by makedir** [comment] 2024-05-22 06:44
Please give an option you can set where to auto open the emjoi window:

- left, right, top, bottom

and then auto attach to main window.

**Closed** 2024-06-01 10:38 UTC
Labels: issue-report

**Comment by makedir** [comment] 2024-06-21 03:27
Not totally fixed. Still is buggy and wont save / attach emoji wndow when you use standalone client start option -c channel. @pajlada

**Comment by pajlada** [comment] 2024-06-22 09:40
> Not totally fixed. Still is buggy and wont save / attach emoji wndow when you use standalone client start option -c channel. @pajlada

Nothing is saved when you use `-c` - so I would say this is the expected behaviour.

**Comment by makedir** [comment] 2024-06-22 14:17
Not accetable. Then fix "-c" mode and change that behavior or add another option to disable that behavior.

**Comment by pajlada** [comment] 2024-06-22 14:25
> Not accetable. Then fix "-c" mode and change that behavior or add another option to disable that behavior.

There's nothing to fix when it's the intended behaviour - it's for use with other applications that want to launch Chatterino in scenarios where you might have multiple instances of Chatterino running at the same time.

I don't know what option to add since I don't know the use case. You can build Chatterino from source and disable the `dontSaveSettings` part of Args.cpp

**Comment by makedir** [comment] 2024-06-22 14:32
You dont need to answer to this. This Issue report was all about the nonsense implementation, that the emoji gui is seperated. This makes zero sense. It needs to be autodocked to the main window or removed at all as a seperate buggy window.

**Comment by pajlada** [comment] 2024-06-22 14:38
Seems like we misunderstood your original report then - in the future you can try reducing the scope of the report, or being clearer with your wording to ensure that doesn't happen
