### ISSUE TITLE
Follow emotes don't show on suggest or tab

### ISSUE THREAD

**Issue by francorz** [Chatterino/chatterino2#4824] opened 2023-09-17 18:33 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Follow emotes don't show in the emote suggest or tab in other channels, only in the channel of streamer (yes, i'm subscribed)

Other channels:
![219392392-abf9d29c-cf4b-4acb-8bc0-759c1d43bbc4](https://github.com/Chatterino/chatterino2/assets/83022459/65d5b00a-c06e-4bb9-8fe6-acd23f66b053)

The channel that I'm subbed:
![219392643-7305e0fc-00be-4073-9186-c30130754e29](https://github.com/Chatterino/chatterino2/assets/83022459/f2ecaebc-7394-4865-9d4f-c4d290ed640e)

### OS and Chatterino Version

Chatterino Nightly 2.4.5 (commit 3265df76) built on 2023-09-17 with Qt 5.15.2, MSVC 193532217 Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by Felanbird** [comment] 2023-09-17 19:02
Duplicate of #4233

**Closed by Felanbird** 2023-09-17 19:02 UTC
Labels: issue-report
