### ISSUE TITLE
Cannot type @ Symbol on Mac

### ISSUE THREAD

**Issue by c0ldplasma** [Chatterino/chatterino2#3099] opened 2021-07-31 22:01 UTC
**Describe your issue**

It is not possible to type an @ Symbol on Mac with "Alt + L" or "Alt Gr  + L".  I would guess thats an issue with chatterinos keybindings.

**OS and Chatterino Version**
macOS Big Sur, M1, Chatterino 2.3.3 (commit ae9f92de )

**Comment by c0ldplasma** [comment] 2021-07-31 22:10
The Chatterino Keybindings page says that "Alt + Arrow keys" should change the selected splits. I just found out that arrow keys dont work for me, instead those functions are on "Alt + H/J/K/L" for whatever reason.

**Comment by Mm2PL** [comment] 2021-07-31 22:56
Duplicate of #2184

**Closed by Mm2PL** 2021-07-31 22:56 UTC
Labels: issue-report

**Comment by DK-Web** [comment] 2022-01-30 19:08
@ sign not shown in Chatfield with option / alt + L please fix! Can´t mention user without mouse.
