### ISSUE TITLE
Cannot chat sometimes. (also sometimes losing chat badges, may be an unrelated issue with Chatterino)

### ISSUE THREAD

**Issue by Oscillate1** [Chatterino/chatterino2#1500] opened 2020-01-14 22:20 UTC
Sometimes, I cannot chat, it seems like it just drops me from all channels.   I tried re-logging into my account on Chatterino and it worked for a while, but then happened again.   So no clue on how to recreate it, but noticed it happening last few days.  (With no disconnect notice, etc)

Not sure about the losing chat badges in Chatterino, but I know other people have noticed it, so it wasn't just a local visual bug, but maybe a Twitch issue, not sure.

**Comment by apa420** [comment] 2020-01-15 07:10
Badges lost are caused by twitch just not sending the badges. As for the no disconnect messages in such, is also a twitch issue with you being disconnected and not receiving any messages afaik.

**Comment by alazymeme** [comment] 2020-05-31 06:38
Are you still able to reproduce this?

**Comment by apa420** [comment] 2020-09-25 18:21
Closing of in favour of #1831

**Closed by apa420** 2020-09-25 18:21 UTC
Labels: bug, needs triage, twitch
