### ISSUE TITLE
Reload subscriber emotes doesnt count for the new animated emotes

### ISSUE THREAD

**Issue by heyimrendy** [Chatterino/chatterino2#2899] opened 2021-06-19 09:31 UTC
**Describe your issue**
When reload emotes pressed, the new animated emotes gone. Animated emotes loaded correctly the first time we open Chatterino but whenever emotes reload, it's gone.
Also higher tier subscriber emotes with modifiers doesnt show at all, tier 2 for example include `_HF` modifier.

**Screenshots** 

**OS and Chatterino Version**
Windows 10, Chatterino Nightly 2.3.2 (commit 9fb5ef60d, )

**Comment by sando** [comment] 2021-06-19 09:39
Can repro on Chatterino Nightly 2.3.2 (commit 6136b82, ). Looks like animated sub emotes are part of a different emote set?

**Comment by Mm2PL** [comment] 2021-06-19 10:06
Can reproduce on 9fb5ef60

**Comment by leon-richardt** [comment] 2021-06-19 10:22
Might need to scrape them off IRC tags somehow? https://dev.twitch.tv/docs/irc/tags#userstate-twitch-tags

**Comment by talneoran** [comment] 2021-06-19 10:32
The changes in #2857 currently fix the unloading of animated emotes on refresh.

**Comment by zneix** [comment] 2021-06-19 10:40
Duplicate of #2631

**Closed by zneix** 2021-06-19 10:40 UTC
Labels: bug, issue-report
