### ISSUE TITLE
Add "low-trust-users" PubSub events thingies, support for Chatterino

### ISSUE THREAD

**Issue by karl-police** [Chatterino/chatterino2#3479] opened 2022-01-09 22:18 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Twitch added the ability to Monitor users, Restrict users and it reports Suspicious Users that might are ban evaders.

These all go into PubSub, similar to when AutoMod catches a filtered message.

Would be very useful if Chatterino could like, style the message for these new moderation features.

### OS and Chatterino Version

Chatterino Nightly 2.3.4 (commit dfa3818a7, built on Windows 10)

**Comment by Felanbird** [comment] 2022-01-10 03:29
Duplicate of #3380

**Closed by Felanbird** 2022-01-10 03:29 UTC
Labels: issue-report
