### ISSUE TITLE
Placeholder color changed with Qt update

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#3604] opened 2022-03-10 21:58 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

The color of our input placeholder changed between qt5-base version `5.15.2+kde+r305-1` and `5.15.3+kde+r133-1`.

### Screenshots

How it looks currently:
![2022-03-10_22-55](https://user-images.githubusercontent.com/25011746/157761186-8faea3db-eaed-44af-aa0b-ed5899e521a0.png)

### OS and Chatterino Version

Arch btw, Chatterino Nightly + Dankerino patches 2.3.4 (commit 0c3cafa4, built on 2022-03-09)

**Comment by leon-richardt** [comment] 2022-03-11 10:34
Duplicate of #3593

**Closed** 2022-03-12 10:40 UTC
Labels: bug
