### ISSUE TITLE
Hype Trains and Predictions

### ISSUE THREAD

**Issue by hanzoxdva** [Chatterino/chatterino2#2236] opened 2020-11-28 21:58 UTC
Maybe this has already been asked but is implementing Hype Trains and Predictions on the to-do list?

**Comment by leon-richardt** [comment] 2020-11-28 22:05
Hype Trains have been requested in https://github.com/Chatterino/chatterino2/issues/2061 before, refer to that issue for more information regarding the matter.

As for Predictions, a similar restriction applies. As long as there is no public API from Twitch, there is no chance for this feature to be implemented unfortunately.

**Comment by apa420** [comment] 2020-11-28 22:12
Duplicate of #2061

**Closed** 2020-11-28 22:11 UTC
Labels: enhancement, needs triage
