### ISSUE TITLE
Feature Request: Option to hide spam of the same messages (with some % of accuracy)

### ISSUE THREAD

**Issue by hemirt** [Chatterino/chatterino2#1460] opened 2019-12-25 21:38 UTC
Would be nice to get rid off either mod spam or multiple people spamming the same thing (albeit with some small differences, eg. a dot at the end, numbers, etc...)

**Comment by hemirt** [comment] 2019-12-25 21:41
Levenshtein distance sounds nice
> The Levenshtein distance has several simple upper and lower bounds. These include:
> - It is at least the difference of the sizes of the two strings.
> - It is at most the length of the longer string.
> - It is zero if and only if the strings are equal.
> - If the strings are the same size, the Hamming distance is an upper bound on the Levenshtein distance.
> - The Levenshtein distance between two strings is no greater than the sum of their Levenshtein distances from a third string (triangle inequality).
https://en.wikipedia.org/wiki/Levenshtein_distance

**Comment by hemirt** [comment] 2019-12-25 21:43
Also would be better to be only able to enable it on longer (than x characters) messages

**Comment by hemirt** [comment] 2019-12-25 21:44
The Damerau-Levenshtein distance also allows transposition of two adjacent characters, so that would be better

**Comment by hemirt** [comment] 2019-12-25 21:45
Maybe someone is better versed in string similarity algorithms and would know better ones

**Comment by apa420** [comment] 2019-12-25 21:47
duplicate of #892

**Closed by apa420** 2019-12-25 21:47 UTC
Labels: enhancement, needs triage
