### ISSUE TITLE
Invisible Mode (Hide to Tray)

### ISSUE THREAD

**Issue by SmaltParrot50** [Chatterino/chatterino2#2448] opened 2021-02-12 13:57 UTC
Add hide to tray or a invisible mode for people that only use the browser extension and don't want their taskbar cluttered up.

**Comment by pajlada** [comment] 2021-02-13 11:47
@SqueezeingDynamicProcess Thank you for your feature requests!
Generally, it's a lot easier for us to track feature requests if they're separated into one feature request per issue, so if you could take your second feature request and make a new issue that would be awesome.
Thank you!

**Comment by leon-richardt** [comment] 2021-02-13 16:07
This is now a duplicate of https://github.com/Chatterino/chatterino2/issues/1358 :smile:

**Comment by zneix** [comment] 2021-04-15 11:39
Duplicate of #393

**Closed by zneix** 2021-04-15 11:39 UTC
Labels: enhancement
