### ISSUE TITLE
"Smooth scrolling on new messages" causes chats to not load

### ISSUE THREAD

**Issue by GreenComfyTea** [Chatterino/chatterino2#2710] opened 2021-04-28 07:23 UTC
**Describe the bug**
When "Smooth scrolling on new messages" is enabled, some of the chats don't load. It seems like it has a pattern of which chats don't load thou it's not consistent. I have 42 channels opened. 

1st restart: 2 empty chats (jhkyeong, imnaomii).
2nd restart: 2 empty chats (jhkyeong, rainsyyy).
3rd restart: 3 empty chats (jhkyeong, rainsyyy, imnaomii).
4th restart: 3 empty chats (jhkyeong, rainsyyy, imnaomii).
5th restart: 1 empty chats (imnaomii).
6th restart: 0 empty chats.

I have seen other chats to be empty too.
With the feature disabled, I did 5 restarts and every time all chats were loaded.

**To reproduce**
Enable "Smooth scrolling on new messages", restart Chatterino.

**Screenshots**
How chat looks without message history when loaded correctly:
![image](https://user-images.githubusercontent.com/30152047/116361824-14616a80-a80a-11eb-8888-f5afdd5174f0.png)

How chat looks when loaded correctly:
![image](https://user-images.githubusercontent.com/30152047/116363595-f98ff580-a80b-11eb-93f0-4fc0e377d799.png)

How chat looks when the bug occurs:
![image](https://user-images.githubusercontent.com/30152047/116362455-bb460680-a80a-11eb-9da2-38538a9e12cc.png)

**Chatterino version**
Chatterino Nightly 2.3.0 (commit 9c41adca2, )

**Operating system**
Windows 10 20H2 (OS Build 19042.928)

**Additional information**
Might be similar to: https://github.com/Chatterino/chatterino2/issues/779
The bug was present for a while, not just in the specified Chatterino version.

**Comment by zneix** [comment] 2021-04-28 08:10
I gotta say I encounter this bug from time to time but I wasn't able to reproduce this consistently. When this happens, as a temporary workaround try adding a new split to the tab in which one of the splits didn't show messages, resize it, so the unloaded split gets smaller and you should notice messages appear on it.
Not sure if this isn't actually a duplicate of #779 but I'll leave this open for a bit.

**Comment by pajlada** [comment] 2022-08-12 19:21
Confirmed duplicate of #779

**Closed by pajlada** 2022-08-12 19:21 UTC
Labels: bug
