### ISSUE TITLE
Hide Messages from Multiple Users by Badge

### ISSUE THREAD

**Issue by gzachariadis** [Chatterino/chatterino2#2097] opened 2020-10-20 12:03 UTC
### Hide Messages from Multiple Users (preferably by Badge)

**Why should it be added?**

I have been using FrankerFacez for a while, but I switched to chatterino mainly for the regex highlights on chat and because I moderate for multiple channels at a time. I want to be able to hide all messages from other moderators in those chats so I can focus on only what users are saying.

**Comment by Mm2PL** [comment] 2020-10-20 12:05
Dupe of #1632 
Fixed by #1748 
`(author.badges) contains ("moderator")`

**Comment by apa420** [comment] 2020-10-20 13:19
Duplicate of #1632

**Closed by apa420** 2020-10-20 13:19 UTC
Labels: enhancement, needs triage
