### ISSUE TITLE
Chat translator

### ISSUE THREAD

**Issue by Meeeee6623** [Chatterino/chatterino2#2091] opened 2020-10-19 14:50 UTC
**What should be added?**
A feature that allows a user to choose one or more languages to translate to a certain language, by channel or global, and maybe even translate messages before sending them, using amazon or google translate. 

**Why should it be added?**
This would allow users to interact better with streamers/chats in other languages, and allow people to use chatterino entirely, instead of using twitch chat with a translator plugin.

**Comment by Mm2PL** [comment] 2020-10-19 14:55
Pretty sure this is a duplicate of an issue that was closed as out of scope, but I can't find the ID of it.

**Comment by fourtf** [comment] 2020-10-20 09:13
This issue is out of scope of the Chatterino project.

**Closed by fourtf** 2020-10-20 09:13 UTC
Labels: enhancement, needs triage

**Comment by Felanbird** [comment] 2022-05-23 00:34
With the merging of #3738, this feature now technically partially exists.

Custom translate commands can be setup and accessed via the new right-click execute command feature.

![image](https://user-images.githubusercontent.com/41973452/168465406-ef29f4c2-fc55-4c85-b6ed-1cd5469707b1.png)

Right click with no highlighting will search the full message text, highlighting will only search the highlighted words.

// google
`/openurl https://translate.google.com/?sl=auto&tl=en&text={1+}`

// bing
`/openurl https://www.bing.com/translator/?from=auto&to=en&text={1+}`

// deepl
`/openurl https://www.deepl.com/en/translator#auto/en/{1+}`
