### ISSUE TITLE
Random crash nightly v1638 built

### ISSUE THREAD

**Issue by Thehail** [Chatterino/chatterino2#1876] opened 2020-08-18 20:23 UTC
**Describe the bug**
Chatterino randomly crashing.

**To reproduce**
1. Open chatterino.
2. Keep it open.
3. It randomly crashes after some time (application closes, needs to open again)

**Screenshots**
It's a random crash, I can't really take a screenshot of it.

**Chatterino version**
nightly v1638 built 👉 2020-08-15T19:34:57.0000000Z 👈

**Operating system**
Windows 10

**Additional information**
If you need additional info, tell me. I will gladly post it. I don't really know how this reproduces, the crash happens even when I'm just watching the stream/chat.

**Comment by Mm2PL** [comment] 2020-08-18 22:03
These kinds of bug are really hard to find and fix. Best way to find how it crashed is to provide a [core dump](https://en.wikipedia.org/wiki/Core_dump), HOWEVER **those can contain secrets like the oauth token that lets you chat using the logged-in accounts**, because they are generally are full memory dumps of the process. But getting a core dump or even just a stack trace is hard, because as you mentioned the cause of it is unknown. Another way is to wait for a miracle and that it gets fixed by someone without even knowing that it's gone, but then we will not know that it's fixed. This may not be fixed soon or at all if we don't get more info on what it is 🙁

**Comment by Thehail** [comment] 2020-08-18 22:51
Alright, I'll just stick reopening the program until it magically fixes or someone finds a fix.

**Comment by mfmarlow** [comment] 2020-08-19 21:28
i'm having the same issue

**Comment by heyimrendy** [comment] 2020-08-20 09:54
Noticed that Chatterino now often crash for me after commit that added Channel Points. Tested with latest Chatterino Nightly 2.1.7 (commit 88f45a284, )

**Comment by alazymeme** [comment] 2020-08-21 08:46
Same issue commit 88f45a284, 15.08.2020

**Comment by alazymeme** [comment] 2020-08-27 13:32
Don't think it does. Was debugging today and got the crash. Below is what I got:
`error: Debugger encountered an exception: Exception at 0x7ffe6b8b295b, code: 0xc0000005: read access violation at: 0xb10, flags=0x0 (first chance)`

![image](https://user-images.githubusercontent.com/12804673/91448634-79507380-e8bd-11ea-80fd-2e05d93242a1.png)

**Comment by Thehail** [comment] 2020-08-30 20:08
Any update on this problem?

**Comment by oldLucke** [comment] 2020-08-30 22:43
for me this seems to be fixed. hadn't a single crash since 83b6fad8e6a6ed33972cefd6e9f6a09a773e1cb5

**Comment by Thehail** [comment] 2020-08-31 01:02
Will give it a try with the new update.

**Comment by alazymeme** [comment] 2020-08-31 03:04
This was fixed in https://github.com/Chatterino/chatterino2/commit/279a80b66fe489bacd6d4da820ea346f5e633d92 for me. Update to 2.2.2 and you should be good

**Closed** 2020-09-04 14:00 UTC
Labels: bug, needs triage
