### ISSUE TITLE
Repetitive 'glitch-like' audio bug on macOS

### ISSUE THREAD

**Issue by manmanboyboy** [Chatterino/chatterino2#4673] opened 2023-06-09 06:28 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [ ] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Audio bug where occurring via any source (speakers, AUX and BT), where a very short glitch-like sound plays every few seconds. 
- Only occurs when chatterino is open (not necessarily focused)
- Only occurs when audio is actively playing 
- Not exclusive to twitch stream/browser audio, audio from other apps have the same issue ONLY if chatterino is open
- Issue most noticeable and pronounced via speakers but still present over headphones (wired and wireless)

### Screenshots

<img width="407" alt="image" src="https://github.com/Chatterino/chatterino2/assets/136055294/7eb96103-dd8b-4d48-a932-cd9ab8c18ced">

### OS and Chatterino Version

Chatterino 7.4.4 (commit 90ee0afd) built with Qt 5.15.2, running on macOS 13.2, kernel: 22.3.0

**Comment by Felanbird** [comment] 2023-06-09 07:09
Duplicate of #4445

**Closed by Felanbird** 2023-06-09 07:09 UTC
Labels: issue-report

**Comment by manmanboyboy** [comment] 2023-06-09 10:42
Sorry don't know how I missed this, github is a bit confusing to navigate for non-devs.
