### ISSUE TITLE
Skip image uploading confirmation if you clicked "Yes, don't ask again" in the alert

### ISSUE THREAD

**Issue by x9136** [Chatterino/chatterino2#5010] opened 2023-12-10 11:09 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Now, if you select "Yes, don't ask again" in the alert, the next time you upload a picture, you'll be asked for confirmation again.

I'm pretty sure that by clicking on "Yes, don't ask again" you uncheck the option:
![Screenshot 2023-12-10 at 14 01 23](https://github.com/Chatterino/chatterino2/assets/60105060/bdf83c09-5e0b-4eef-9ef8-79afc919290f)

### Screenshots

![Screenshot 2023-12-10 at 13 39 07](https://github.com/Chatterino/chatterino2/assets/60105060/91598cff-44fb-49bd-87fd-bfd971cb5dfa)

### OS and Chatterino Version

Chatterino 2.4.5 (commit 05a72d33) built with Qt 6.5.0 Running on macOS 14.1, kernel: 23.1.0

**Comment by pajlada** [comment] 2023-12-10 11:29
Can't reproduce

https://github.com/Chatterino/chatterino2/assets/962989/0d900ce6-193b-4e71-9e8a-d688e88c22aa

**Comment by pajlada** [comment] 2023-12-10 11:31
I can reproduce on macOS - investigating

**Comment by pajlada** [comment] 2023-12-10 11:56
I've confirmed that this will be fixed by https://github.com/Chatterino/chatterino2/pull/5011 - thanks for reporting the issue!

**Closed** 2023-12-10 12:28 UTC
Labels: bug, OS: Mac
