### ISSUE TITLE
Add which channel sub emotes belong to

### ISSUE THREAD

**Issue by daiexd** [Chatterino/chatterino2#2135] opened 2020-10-26 05:10 UTC
What Should Be Added?
A channel name under sub emotes on hover, to tell you which channel the sub emote is from.

Why Should It Be Added?
So that you do not have to use a 'what emote is it' command to be able to know which channel the sub emote is from.
Sometimes the set emote code is not matching to the name of the twitch channel, so it is hard to know who the emote belongs to. 
![image](https://user-images.githubusercontent.com/73288014/97135819-9b734e80-17a5-11eb-8305-686aad547a40.png)

**Comment by leon-richardt** [comment] 2020-10-26 06:12
Duplicate of #917. Not that easy to implement without making loads of API calls unfortunately.

**Comment by pajlada** [comment] 2020-10-26 16:39
Duplicate of #917

**Closed** 2020-10-26 16:39 UTC
Labels: enhancement
