### ISSUE TITLE
Add the BTTV commands /localsub and /localmod

### ISSUE THREAD

**Issue by cemX44** [Chatterino/chatterino2#2794] opened 2021-05-20 00:26 UTC
/localsub will make the chat appear in sub-mode to you only.
/localsuboff turns it off, returning things to normal.

/localmod will only allow you to see mods chat.
/localmodoff turns it off, returning back to normal.

They are already implemented in native Twitch chat with BTTV installed and I would like to see it in Chatterino too.
Not a programmer myself, so I don't know hard it is to do this but I would really appreciate it and so would others.

**Comment by sando** [comment] 2021-05-20 02:28
Duplicate of #2330

You can achieve the same functionality using [Filters](https://wiki.chatterino.com/Filters/) within Chatterino.

**Closed** 2021-05-20 07:13 UTC

**Comment by gzachariadis** [comment] 2022-12-20 12:23
`/localsub` is effectively `author.subbed || flags.system_message || author.badges contains "moderator" || author.badges contains "vip" || author.badges contains "broadcaster"`

'/localmod' is effectively `author.badges contains "moderator" || author.badges contains "broadcaster"`

Note: Local sub as I have laid it out here, will still show highlighted messages even if not written by a sub, moderator, vip or broadcaster.
