### ISSUE TITLE
adding support for youtube channels would be cool

### ISSUE THREAD

**Issue by petterio** [Chatterino/chatterino2#2162] opened 2020-11-07 01:13 UTC
don't know if it is easy to implement a channel going live on youtube. 
but having the option to join a live channels chat would be cool. with bttv and ffz emote support ofc :--)

**Comment by alazymeme** [comment] 2020-11-07 07:01
I don't agree, I think this is out of scope for chatterino.

**Comment by apa420** [comment] 2020-11-07 14:02
How would bttv and ffz emote support make sense for youtube?

**Comment by cinemassacres** [comment] 2020-11-11 20:40
duplicate of #357

**Comment by fourtf** [comment] 2020-11-17 11:50
Youtube support is unfortunately very hard to do so I would say this is out of scope.

**Closed by fourtf** 2020-11-17 11:50 UTC
Labels: enhancement, needs triage

**Comment by itzklyde** [comment] 2021-12-09 17:47
> How would bttv and ffz emote support make sense for youtube?

Looks like they work great on YouTube now eh

**Comment by Felanbird** [comment] 2021-12-09 17:56
Locking this to prevent random spam bumping, the current conversation about youtube support has most recently been discussed in #3298
