### ISSUE TITLE
alternate background colour flickering 

### ISSUE THREAD

**Issue by madstingray16** [Chatterino/chatterino2#1789] opened 2020-07-06 19:11 UTC
when i use the chatterino native host and have not clicked on the chat box, the colours will swap between the different shades of grey on the same line, this is using the alternate background colour option in the settings. so the colour changes for each chatters line like its flashing. 

To reproduce
i would like this fixed as its very annoying and the only issue i have found 

version
Chatterino 2.1.7 (commit 845c8fa63)

Operating system
 Windows 10

**Comment by Mm2PL** [comment] 2020-07-06 19:13
Maybe it's related to what happens with searching, if you press enter a couple times in the search popup window the background will flicker. As I am on Linux I cannot even test if this bug is reproducible.

**Comment by Mm2PL** [comment] 2020-07-06 19:14
Is it possible for you to provide a video of the bug happening including you doing what causes it?

**Comment by rainstack** [comment] 2020-07-12 22:50
![Chatterino-Native-Host-Background-Alternating](https://user-images.githubusercontent.com/53135204/87258227-e6c05600-c46f-11ea-8414-7e13d014e8a7.gif)

Here is a clip of it happening. I went to an offline chat to capture it, but it happens in active chats with current messages too.

When the Chatterino Native Host window is in full focus, the background color alternating doesn't happen. If I click anywhere else, like to interact with the player, the color alternating starts whether there are more messages or not.

**Comment by skullsir** [comment] 2020-07-13 00:45
Do you have the window or the text in a specific size; have you tried a clean reinstall at all?

I unable to reproduce the issue with Windows 10 2004

**Comment by rainstack** [comment] 2020-07-13 13:51
I've moved the browser window and changed the height to capture the GIF I posted, so that automatically resized and moved the Chatterino Native Host chat overlay. I have tried a reinstall when I first noticed it happening.

I was using the Segoe UI font, which I believe was default, with a size of 14pt. Since your post, I've tried all the other sizes in the drop-down with the same result. In case it matters, my UI Scale is Default. Of note, I've turned off the "Alternate background color" option, and while it obviously doesn't flash the background colors anymore, the text wrapping that sometimes changes that you can see in the GIF I posted still happens.

As for my Windows 10 info, I'm also on build 2004 but it was happening in the previous build too. It's on a single 1080p screen with the scale set to 100%. Only one monitor is connected to the system.

**Comment by rainstack** [comment] 2020-07-15 09:06
I think I've found some more information to go on for this issue. The alternating background color changing automatically (even without new messages) seems to only happen with the Chatterino Native Host window when there is an odd # of messages in the chat window. 

I installed the latest nightly build to test if it was the same (it is). The build includes a message history for  the usercard window, and the same alternating colors for odd # of messages happens when the Refresh button is pressed. 

![Chatterino-Native-Host-Background-Alternating2](https://user-images.githubusercontent.com/53135204/87526537-f77ff000-c658-11ea-8cff-8bb6cf3fbe07.gif)

**Comment by pajlada** [comment] 2020-07-18 12:44
Should be fixed in master now @rainstack  - when the CI has built a new nightly version in ~10 minutes could you please test this and see if it fixes your issues with the extension & the User Info Popup?

Thanks a lot for your detailed report!

**Closed** 2020-07-18 12:44 UTC
Labels: bug

**Comment by rainstack** [comment] 2020-07-18 17:21
@pajlada I can confirm the latest nightly build solves this issue in both the extension chat window and the usercard popup. Thank you!
