### ISSUE TITLE
Log In button doesn't open browser.

### ISSUE THREAD

**Issue by bjwest** [Chatterino/chatterino2#1973] opened 2020-09-19 22:57 UTC
**Describe the bug**

Adding an new account, the 'Log in (Opens in browser)' button does not open browser when pressed.

**To reproduce**
Go to Chatterino Settings (cog in upper left of window) -> Accounts and press 'Add' button on top of dialog.
in next (unnamed) dialog 'Basic' tab, press 'Log in (Opens in browser)' button

**Screenshots**

**Chatterino version**
Chatterino 2.2.2 (commit 07fc0c3ad)

**Operating system**
Operating System: KDE neon 5.19
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.0
Kernel Version: 5.4.0-47-generic
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 3800X 8-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: AMD Radeon RX 5600 XT

**Additional information**
Firefox is set as my system default browser and opens for other applications that call it.

**Comment by leon-richardt** [comment] 2020-09-20 07:54
Possible duplicate of #1779.

**Comment by RAnders00** [comment] 2020-09-20 10:14
Duplicate of #1779

**Closed by RAnders00** 2020-09-20 10:14 UTC
Labels: bug, needs triage
