### ISSUE TITLE
Hide "Send message as [user]..." from he input line

### ISSUE THREAD

**Issue by mangojuice0** [Chatterino/chatterino2#2646] opened 2021-04-19 12:15 UTC
**What should be added?**
A way to hide "Send message as [user]..." from he input line

**Why should it be added?**
Previous versions didn't have this feature and honestly it's way too distracting. It also becomes useless when you only have one account connected.

**Comment by leon-richardt** [comment] 2021-04-19 12:18
This has been discussed to lengths in https://github.com/Chatterino/chatterino2/issues/2305.

**Comment by Mm2PL** [comment] 2021-04-19 12:18
duplicate of #2305

**Comment by alazymeme** [comment] 2021-04-19 12:21
I find this more distracting than the chatterino implementation. You have every right to ignore it, but I don't see a reason to add more unnecessary settings:

![image](https://user-images.githubusercontent.com/12804673/115235525-a22fbc80-a15d-11eb-8440-3a33b616415f.png)

**Comment by zneix** [comment] 2021-04-19 12:22
Duplicate of #2305, see discussion there for more explanation. Also, after some time I (and others) eventually got used to this.

**Closed by zneix** 2021-04-19 12:22 UTC
Labels: enhancement

**Comment by zneix** [comment] 2021-04-19 12:26
However after some thinking maybe we could just change the placeholder text to show us the name of the channel instead of current account, not sure if I want to touch that again though - it could cause another wave of complaints.
