### ISSUE TITLE
Notification if sent message was dropped by tmi

### ISSUE THREAD

**Issue by GaZaTu** [Chatterino/chatterino2#3083] opened 2021-07-29 17:39 UTC
**Describe your issue**

Sometimes my messages just don't go out (single message, not spamming).
It's fucking annoying, especially in fast chats like #forsen. 😡

Would be dank if some bigbrain could add an optional notification if my message was dropped by tmi.
Channel specific self highlight would be an acceptable workaround aswell (+ configuration to only have this active while the streamer is online would be even better).
🤣🤣🤣🤣🤣🤣

**Screenshots**

**OS and Chatterino Version**

**Comment by apa420** [comment] 2021-07-29 17:46
Duplicate of #1710

**Closed by apa420** 2021-07-29 17:46 UTC
Labels: issue-report
