### ISSUE TITLE
Minimize Chatterino to system tray

### ISSUE THREAD

**Issue by dozzzz02** [Chatterino/chatterino2#1358] opened 2019-10-08 21:13 UTC
**Is your feature request related to a problem? Please describe.**
Basically, you have to have chatterino open, even if you dont want to use it directly. This is used for the window inside the stream which replaces the normal chat.

**Describe the solution you'd like**
Either:

- Minimize main chatterino window and remove it from the taskbar and show only the icon in the system tray. Only show the chatterino windows used in browsers ( if you have more than 1 window ) 
- Have the chatterino (program) window be the one that replaces the chat window in the browser.

**Describe alternatives you've considered**
Closing the window by clicking (X) but that also closes the window in the browser.

**Additional context**
Kinda like spotify, which has a 'if you click close, minimize to system tray.'

**Comment by fourtf** [comment] 2019-10-08 21:16
Duplicate of https://github.com/Chatterino/chatterino2/issues/393 but this has an actual description so I'm closing the other one.

**Comment by fourtf** [comment] 2019-10-08 21:18
Also fixed your markdown in the description

**Comment by cinemassacres** [comment] 2020-08-16 22:00
is there any progress ?

**Comment by leon-richardt** [comment] 2020-08-17 08:52
> is there any progress ?

No one is working on it AFAIK.

**Comment by Akakeshaa** [comment] 2023-06-05 20:37
this is still pending please implement this

**Comment by zerogott** [comment] 2023-08-15 08:51
Any update on this?

**Comment by ZjemCiKolege** [comment] 2023-11-29 20:01
Any progress?

**Comment by ZjemCiKolege** [comment] 2024-04-29 11:58
Any update on this?

**Comment by pajlada** [comment] 2024-07-13 09:51
Closing this as a wont-fix because this is a big lift for something I don't want to force on others, and making it optional is not fun. Happy to explore this again in the future, but for now this just isn't feasible.

**Closed by pajlada** 2024-07-13 09:51 UTC
Labels: enhancement
