### ISSUE TITLE
Emotes parse wrong somehow

### ISSUE THREAD

**Issue by karl-police** [Chatterino/chatterino2#2569] opened 2021-03-27 20:50 UTC
**Describe the bug**
Emotes parse wrong somehow

**To reproduce**
Try to send this in chatterino: `PowerUpL 🤓 PowerUpR hehe, you will be banned ❗  `

**Screenshots**
Original message:
![](https://i.imgur.com/YXdxHSm.png)

In chatterino:
![](https://i.imgur.com/JYtsz1B.png9)

Add more spaces and it will look like this in chatterino:
![](https://i.imgur.com/H8UfVoo.png)

**Chatterino version**
Chatterino 2.2.3-beta2 (commit 6499b7c12)

**Operating system**
Windows 10 64Bit

**Comment by jammehcow** [comment] 2021-03-27 21:28
Cannot reproduce, `Chatterino 2.2.3-beta2 (commit 1f5b62e6e)`

**Comment by jammehcow** [comment] 2021-03-27 21:39
Duplicate of #2479 

Was fixed in #2490. Bug is no longer present in nightly.

**Closed** 2021-03-27 22:41 UTC
Labels: bug
