### ISSUE TITLE
No information about historic messages service inside chatterino app

### ISSUE THREAD

**Issue by hemirt** [Chatterino/chatterino2#5304] opened 2024-04-07 21:24 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Currently the in app does not present information about who is faciliating the historic messages service, nor the privacy policy, or terms of service. (The wiki does say so, but I believe it could also be in the app). And there is also an undocumented hardcoded limit of 800 maximum messages to load.

Also changing the service is unnecessarily difficult, CHATTERINO2_RECENT_MESSAGES_URL (and similarly CHATTERINO2_LINK_RESOLVER_URL and CHATTERINO2_PROXY_URL<sup>[1]</sup>) could be moved into settings/external and be easily available for change by the user.

#

[1] For CHATTERINO2_PROXY_URL it might be better left as both an ENV var, since a user could set up multiple different environments to set this parameter in multiple different ways, and it could still be inside settings, and the setting be ignored if it exists as an environment variable.

### Screenshots

Preview of historic messages setting
![image](https://github.com/Chatterino/chatterino2/assets/1310440/5ffd6346-337b-4f7f-8706-34b3330ad962)

Versus preview of link preview setting
![image](https://github.com/Chatterino/chatterino2/assets/1310440/ee6d8e8a-b243-4db4-9193-5890808e7ff3)

### OS and Chatterino Version

Chatterino Nightly 2.5.0-beta.1 (commit 25a69fd1) built on 2024-04-07 with Qt 6.5.0, MSVC 193833135 Running on Windows 11 Version 23H2, kernel: 10.0.22631

**Comment by pajlada** [comment] 2024-04-07 21:30
Duplicate of #1311

**Closed by pajlada** 2024-04-07 21:30 UTC
Labels: issue-report

**Comment by hemirt** [comment] 2024-04-07 21:42
> Duplicate of #1311

I believe the issues I listed could benefit from having a discussion before creating any directed issues, whilst the linked issue seems to be addressing the problem of non information, it is of different nature, and the listed proposed solutions only address my issue in part. For example I never saw any installer, I downloaded the release zip, and the proposed solution of system message does not seem to hint at choosing a different service host.

Should I then make a new issue (if it does not exist) for each:
- hardcoded limit of 800 messages
- not user friendly setting of
- - CHATTERINO2_RECENT_MESSAGES_URL
- - CHATTERINO2_LINK_RESOLVER_URL 
- - CHATTERINO2_PROXY_URL

**Comment by hemirt** [comment] 2024-04-07 21:48
Whilst nobody is probably going to change the default link resolver, I could see people changing their recent messages provider to add in features that are not present in the current one provided (e.g. longer timeframes or larger message set). And proxy settings are quite common that they should be inside the settings.
