### ISSUE TITLE
Highlights for certain types of users in chat…

### ISSUE THREAD

**Issue by NYISLANDERFAN** [Chatterino/chatterino2#2639] opened 2021-04-17 21:30 UTC
**What should be added?**

A Highlight option should be added for certain types of users in chat, such as Broadcaster, Moderator, Subscriber, etc. instead of only able to use highlights for specific usernames.

**Why should it be added?**

I believe this should be added because it would be a very helpful tool to use for, both, Moderators, Streamers, and just regular users to use in a chat to make sure they don't miss messages from the streamer themself, or any of the moderators.

**Comment by sando** [comment] 2021-04-17 21:37
Duplicate of #1696

**Comment by zneix** [comment] 2021-04-17 23:42
Duplicate of #1696

**Closed by zneix** 2021-04-17 23:42 UTC
Labels: enhancement
