### ISSUE TITLE
Weird white bar at the edge of the screen

### ISSUE THREAD

**Issue by gwua** [Chatterino/chatterino2#1734] opened 2020-06-11 18:11 UTC
**Describe the bug**
When Chatterino2 is in fullscreen mode on my first display, a white bar appears on the edge of my second display.

**To reproduce**
Toggle fullscreen mode in Chatterino.

**Screenshots**
![sfyKoSLtmg](https://user-images.githubusercontent.com/51796937/84423859-cd857900-ac27-11ea-8a4a-307c838cee54.png)

**Chatterino version**
Chatterino Nightly 2.1.7 (39cc421f9)

**Operating system**
Windows 10 Pro Version 2004 (OS Build 19041.329)

**Additional information**
This bug started happening after updating to version 2004.

**Comment by apa420** [comment] 2020-06-11 18:20
Duplicate of #1718

**Closed by apa420** 2020-06-11 18:20 UTC
Labels: bug, needs triage
