### ISSUE TITLE
Implement 7TV into Chatterino

### ISSUE THREAD

**Issue by karl-police** [Chatterino/chatterino2#2908] opened 2021-06-20 23:39 UTC
There's a new third party thing called 7TV. Which isn't available yet in Chatterino.

However, I don't think it should be added until the issues are resolved. As example, conflict issues. Since 7TV has global emotes, that BTTV has as well but to enable separately, it might not be that good to implement 7TV straight away. We should wait until it is a bit more ready.

First of all, for everyone that would use Chatterino would see these global emotes in the emotes tab and it would be weird if those global emotes from 7TV would be started to get used in channels that don't even have any of these enabled.

That's why we should wait until 7TV adds the ability to disable global emotes from a channel.

&nbsp;
You know 7TV, might not be the last third party we see, who knows.

**Comment by Felanbird** [comment] 2021-06-21 00:15
Duplicate of #2827

You can already get Chatterino with 7tv via their repo, https://github.com/SevenTV/chatterino7

**Comment by karl-police** [comment] 2021-06-21 00:26
oh there are Discussions now

**Comment by Mm2PL** [comment] 2021-06-21 06:42
Duplicate of #2827

**Closed by Mm2PL** 2021-06-21 06:42 UTC
Labels: issue-report
