### ISSUE TITLE
Chatterino Subscriber Emote Glitch/Bug

### ISSUE THREAD

**Issue by NYISLANDERFAN** [Chatterino/chatterino2#2624] opened 2021-04-12 21:50 UTC
**Describe the bug:**
[In some cases] using subscriber emotes in their designated channel (the channel they're from) - in bulk — {SEE SCREENSHOT BELOW}

**To reproduce:**
[In some cases] use subscriber emotes in their designated channel (the channel they're from) - in bulk — {SEE SCREENSHOT BELOW}

**Screenshots:**
<img width="850" alt="chatterino subscriber emote glitch" src="https://user-images.githubusercontent.com/44728118/114466316-5063c100-9bb6-11eb-88cb-2dc0bea5965e.png">

**Chatterino version:**
Chatterino 2.2.3-beta2 (commit 6499b7c12)

**Operating system:**
macOS Big Sur Version 11.2.3
<img width="450" alt="macOS Big Sur Version 11.2.3" src="https://user-images.githubusercontent.com/44728118/114466671-c9fbaf00-9bb6-11eb-9070-0496852e2128.png">

**Additional information:**
it's where subscriber emotes only post once in some cases and then it's just text afterwards and nothing fixes it, it doesn't work if you try to reload sub emotes via the menu, and quitting out of it entirely and restarting it doesn't do anything to fix it either.

**Comment by zneix** [comment] 2021-04-12 22:05
Duplicate of #2479 (check that issue for more information)

This has been fixed in #2490. You can download [nightly build](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build) which has the fix, hope this helps!

**Closed by zneix** 2021-04-12 22:05 UTC
Labels: bug

**Comment by NYISLANDERFAN** [comment] 2021-04-12 23:02
will all of my settings be saved if i download a different version?

**Comment by zneix** [comment] 2021-04-13 06:37
Yes, don't worry. Nothing should disappear since all your data should be located within your chatterino folder - according to [the wiki](https://wiki.chatterino.com/Help/#where-is-my-chatterino-folder-located) it should be in `$HOME/Library/Application Support/chatterino`.

**Comment by NYISLANDERFAN** [comment] 2021-04-13 11:51
it did save, thank you!
