### ISSUE TITLE
Closing Shroud crashes desktop app.

### ISSUE THREAD

**Issue by maxy55555** [Chatterino/chatterino2#2952] opened 2021-07-04 03:07 UTC
I follow many Twitch.tv streamers, one of which is Shroud. I have had his chat open for a couple of years now and never tried to close it. Today, I tried to swap the split with him in it for another channel, and my application immediately crashed. After rebooting, I tried to simply close the split, which resulted in another crash. I can close every other tab I have open, rename/swap channels as I please, but the app will not crash until I try to close Shroud's tab. It crashes every time I try to do so.

Windows 10, v2004
Chatterino 2.3.2, commit 6732b25f3
No browser extension installed.

I have noticed the app crashes randomly as well, but I am unable to reproduce those crashes. It seems unrelated.

**Comment by ALazyMeme** [comment] 2021-07-04 05:12
I believe the first part is a duplicate of https://github.com/Chatterino/chatterino2/issues/2391 (as I've also run into this issue, it seems to be related to faster moving chats)
The second part is likely a duplicate of https://github.com/Chatterino/chatterino2/issues/2774

Could you please try downloading the latest nightly and seeing if that fixes it?

**Comment by Mm2PL** [comment] 2021-07-22 15:17
Duplicate of #2391 
Duplicate of #2774

**Closed by Mm2PL** 2021-07-22 15:17 UTC
Labels: issue-report
