### ISSUE TITLE
Option to disable trailing hidden Unicode character when sending repeated text

### ISSUE THREAD

**Issue by YorVeX** [Chatterino/chatterino2#1933] opened 2020-09-02 01:19 UTC
**What should be added?**
When sending the same text as in the line before chatterino automatically appends a space character and a hidden Unicode character (0xE0000, or bytes F3 A0 80 80) to the end of the line that is sent to the server. That is a pretty clever way of circumventing the Twitch protection for repeated messages, because the message technically differs from the one before while visually it doesn't.

However, I would like to have an option to disable this behavior.

**Why should it be added?**
While this feature is great for normal chatting it's annoying when testing bot commands (e.g. repeating them until they work as they should), because some bots actually detect this character and think it's part of the command that is sent to them. It took me a long time before I found out why bots would complain about invalid parameters in every other message.

**Comment by cinemassacres** [comment] 2020-09-02 02:34
https://github.com/Chatterino/chatterino2/issues/1024

**Comment by apa420** [comment] 2020-09-02 06:04
Since there is a lot of people using chatterino I would suggest filtering out this character in your bot.
#1024 is only discussing how the character is represented in the code it is not really relevant to this issue.
The option to edit/remove the trailing character should probably be an option imo.

**Comment by Mm2PL** [comment] 2020-09-02 08:39
Duplicate of #1572

**Comment by apa420** [comment] 2020-09-05 21:18
Duplicate of #1572

**Closed by apa420** 2020-09-05 21:18 UTC
Labels: enhancement
