### ISSUE TITLE
Chatterino lagging at startup (2.3.0)

### ISSUE THREAD

**Issue by Oscillate1** [Chatterino/chatterino2#2675] opened 2021-04-23 20:40 UTC
Updated to Chatterino version 2.3.0 today and it lags at startup.   It hangs in not responding state for 1 minute or so before it begins to function.

I am using Windows 10 OS

I cleared cache, turned off features that I seen were new or just turned on when I first launched after update.  (Live indicator on tabs, colored names for @usernames and anything else I noticed that I did not need or use before.

I've turned on beta updates for now.  Thanks

**Comment by alazymeme** [comment] 2021-04-24 04:48
Sounds like a duplicate of https://github.com/Chatterino/chatterino2/issues/2666
Can you please try this solution? https://github.com/Chatterino/chatterino2/issues/2666#issuecomment-825424260

**Comment by zneix** [comment] 2021-05-06 11:11
@Oscillate1 does this still occur after clearing your cache and updating to 2.3.1?

**Comment by Oscillate1** [comment] 2021-05-09 21:56
Yes, when updating, I had to delete the cache.  Updating alone did not fix it, data in the cache was causing a conflict with it launching.

**Closed** 2023-05-08 17:34 UTC
Labels: bug
