### ISSUE TITLE
(macOS) Key hold for accent menu repeats keypress while open

### ISSUE THREAD

**Issue by jupjohn** [Chatterino/chatterino2#2604] opened 2021-04-08 10:58 UTC
**Describe the bug**
When holding a key in macOS to display the accent menu they key being held repeats the character in the input box until released or a accent is picked.

**To reproduce**
 1. Open chatterino and navigate to an open split
 2. Press and hold any letter that can be accented
 3. Observe accent menu opens but key repeat continues

Also when pressing a number associated with the accented char you wish to pick that is appended to the text box too.

**Screenshots**
https://user-images.githubusercontent.com/4962764/114014851-290eaa80-98bd-11eb-986a-f896c9346d28.mp4

**Chatterino version**
Chatterino 2.2.3-beta2 (commit 032a791ec)

**Operating system**
macOS 10.15.x Catalina

**Comment by pajlada** [comment] 2023-12-10 12:15
Duplicate of https://github.com/Chatterino/chatterino2/issues/1430

**Closed by pajlada** 2023-12-10 12:15 UTC
Labels: bug
