### ISSUE TITLE
Crash on startup when filter attached

### ISSUE THREAD

**Issue by heyimrendy** [Chatterino/chatterino2#3108] opened 2021-08-03 02:40 UTC
**Describe your issue**
Chatterino crash on startup when we have channel filter attached. 

https://i.nuuls.com/P4Mgx.mp4

Steps to reproduce

1. Add filter to a channel
2. Close chatterino
3. Open chatterino again

Commit 3cb1e5158ab360776a98954aff9e79b2b2f5d6d7 works without crash.

**OS and Chatterino Version**
Chatterino Nightly 2.3.3 (commit 784fdd28b, )
Windows 10 21H1

**Comment by ALazyMeme** [comment] 2021-08-03 02:55
Cannot reproduce, Windows 10 21H1, build 19043.1151. Chatterino Commit 770b9f26

Is there a specific filter you're using? Suggest you also try updating to the latest nightly/beta to test if it was fixed in a later version.

**Comment by heyimrendy** [comment] 2021-08-03 03:06
> Is there a specific filter you're using? Suggest you also try updating to the latest nightly/beta to test if it was fixed in a later version.

No specific filter, just the default one when we create filter. `(message.content) contains ("hello")`
Im using latest nightly already, commit from 2 days ago. I'll test again when new commit being push, to see if its still crash for me.

**Comment by Felanbird** [comment] 2021-08-03 05:58
Can replicate building d7e8f4e | w10

![image](https://user-images.githubusercontent.com/41973452/127965155-ec0d840c-4562-411f-9d42-0716995f4e67.png)
Nothing in console, only this prompt

**Comment by pajlada** [comment] 2021-08-03 07:21
Thanks for the report! Will be fixed by https://github.com/Chatterino/chatterino2/pull/3110

**Closed** 2021-08-03 07:39 UTC
Labels: bug, high priority
