### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by mfmarlow** [Chatterino/chatterino2#2180] opened 2020-11-13 00:57 UTC
**Describe the bug**

Every now and then I'll look over to my taskbar and see that Chatterino has closed. I stuck a debugger on it and caught it throwing an exception related to the heap (see screenshot below) and was able to actually prevent the application from crashing. After resuming the process, the Native Host extension seems to not attach at all.

`Exception thrown at 0x00007FFF65E8ED29 (ntdll.dll) in chatterino.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFF65EF87F0).`

**To reproduce**

Idk, it seems random. Based on debug info, it could be related to NW detach.

**Screenshots**

![image](https://user-images.githubusercontent.com/44077383/99015104-0b553900-2509-11eb-9431-9db34672249a.png)

**Chatterino version**

Chatterino Nightly 2.2.3-beta (commit 0eed45ae6, 08.11.2020)
**Operating system**

Windows 10 version 2004 build 19041.572
**Additional information**

**Comment by pijcab** [comment] 2021-01-22 19:00
Idk if it's super relevant since I'm still using **v2.2.2-fix** but **I get those random crashes too.**

I didn't attach a debugger to it either

**Comment by d0nk7** [comment] 2022-05-26 22:19
![uP_a_](https://user-images.githubusercontent.com/18603393/170588490-5e94f8de-9ed1-4a26-9d20-f8edc15a022a.png)
![8AUDu](https://user-images.githubusercontent.com/18603393/170588491-981cfc84-1325-4d38-aae9-62087d62a582.png)
![Sh8HY](https://user-images.githubusercontent.com/18603393/170588493-87fac202-ca2f-49cb-bbd1-b0ed0ca494bd.png)
I'm having this issue too, it's crashing constantly and is making it impossible to use
Chatterino Nightly 2.3.5 (commit 6ef3ecc9, built on 2022-05-23) running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by pajlada** [comment] 2022-05-28 09:49
> ![uP_a_](https://user-images.githubusercontent.com/18603393/170588490-5e94f8de-9ed1-4a26-9d20-f8edc15a022a.png) ![8AUDu](https://user-images.githubusercontent.com/18603393/170588491-981cfc84-1325-4d38-aae9-62087d62a582.png) ![Sh8HY](https://user-images.githubusercontent.com/18603393/170588493-87fac202-ca2f-49cb-bbd1-b0ed0ca494bd.png) I'm having this issue too, it's crashing constantly and is making it impossible to use Chatterino Nightly 2.3.5 (commit [6ef3ecc](https://github.com/Chatterino/chatterino2/commit/6ef3ecc952be5e1b07bddf6a751a2999139e8a34), built on 2022-05-23) running on Windows 10 Version 2009, kernel: 10.0.19044
> 
> It's not happening on [28efd29](https://github.com/Chatterino/chatterino2/commit/28efd29dfa73f29702d4dbb56073a9e2158fd64e) for me

Are you doing anything when it crashes? e.g. interacting with a usercard, sending a message or something like that

**Comment by d0nk7** [comment] 2022-05-29 04:38
> Are you doing anything when it crashes? e.g. interacting with a usercard, sending a message or something like that

No, just launching and normal usage, nothing in particular was triggering it, a crash would occur pretty soon after launch.
Luckily, I ended up rebuilding my settings from scratch and it _seems_ to have fixed it.
So it might've just been something to do with updates and my old settings not playing nice, I still have my old settings laying around, so I'll see if I can try to reproduce it.

**Comment by pajlada** [comment] 2022-08-12 18:50
Closing this one out since it's too generic, feel free to open a new issue if you find a pattern to the crashes or if you're able to attach a stacktrace with the crash

**Closed by pajlada** 2022-08-12 18:50 UTC
Labels: bug
