### ISSUE TITLE
individual channel logs suggestion

### ISSUE THREAD

**Issue by shadopi** [Chatterino/chatterino2#1545] opened 2020-02-11 15:49 UTC
**Is your feature request related to a problem? Please describe.**
It's frustrating to try to have logs for one specific channel and having to close all my other tabs so it doesn't take up too much space
**Describe the solution you'd like**
I'd like to have logging for individual channels

**Describe alternatives you've considered**
I've tried having 2 chatterino's open but i feel like having this feature would be much easier and i'm sure other people would like having this feature too 

**Additional context**

**Comment by leon-richardt** [comment] 2020-02-11 21:41
Duplicate of #1456.

**Closed** 2020-02-15 23:58 UTC
Labels: enhancement
