### ISSUE TITLE
Chatterino not starting (white screen)

### ISSUE THREAD

**Issue by Speeder2k** [Chatterino/chatterino2#2563] opened 2021-03-24 20:08 UTC
**Describe the bug**
 When starting chatterino, the window is just white and then closes after a few seconds. Tried running it in administrative mode, reinstalling, and updating my windows version and none of these things worked.
**To reproduce**
 Open chatterino

**Screenshots**

![chatterino](https://user-images.githubusercontent.com/81329010/112376020-5272e800-8cba-11eb-8694-068d3c08a4f7.JPG)

**Chatterino version**
Chatterino v2.2.2-fix

**Operating system**
 Windows 10 Home Insider Preview - Build 21337.rs_prerelease.210312-1502

**Additional information**
sorry if this is an operating system issue

**Comment by alazymeme** [comment] 2021-03-25 08:21
Have you tried the steps as listed in the basic troubleshooting section of the wiki? https://wiki.chatterino.com/Help/#basic-troubleshooting

Please give those steps a try and get back to me.

**Comment by sando** [comment] 2021-03-25 08:49
> Windows 10 Home Insider Preview - Build 21337.rs_prerelease.210312-1502

Duplicate of #2475. Chatterino doesn't currently work on Insider dev channel builds.

**Closed** 2023-06-13 16:38 UTC
Labels: bug
