### ISSUE TITLE
Add an option to customize badges like FFZ does

### ISSUE THREAD

**Issue by bontalor** [Chatterino/chatterino2#1857] opened 2020-08-14 09:27 UTC
**What should be added?**
Add an option to change the shape and use the old twitch badges like FFZ does: 
![ffz settings](https://user-images.githubusercontent.com/62087307/90234909-739f5c00-ddee-11ea-8ea9-7a19ee21121e.png)

**Why should it be added?**
It would allow for more customization

**Comment by leon-richardt** [comment] 2020-08-14 09:29
Duplicate of https://github.com/Chatterino/chatterino2/issues/1461.

**Comment by alazymeme** [comment] 2020-08-14 15:52
Duplicate of https://github.com/Chatterino/chatterino2/issues/1314

**Comment by apa420** [comment] 2020-08-15 19:26
Duplicate of #1314

**Closed by apa420** 2020-08-15 19:26 UTC
Labels: enhancement, needs triage
