### ISSUE TITLE
Moderation messages not showing up in own channel

### ISSUE THREAD

**Issue by badoge** [Chatterino/chatterino2#2620] opened 2021-04-12 12:17 UTC
**Describe the bug**
Moderation messages don't show the reason and the mod that did the action if you are the broadcaster.

**To reproduce**
Time someone out through a broadcaster/mod account and look at the timeout messages

**Screenshots**

logged in as broadcaster:
![image](https://user-images.githubusercontent.com/18620902/114389782-7c774600-9ba6-11eb-8471-0a3b81099c4d.png)
logged in as mod:
![image](https://user-images.githubusercontent.com/18620902/114389883-9d3f9b80-9ba6-11eb-8c09-d345b3e39291.png)

**Chatterino version**
Chatterino 2.2.2-fix (commit a82f57f94)

**Operating system**
Windows 10

**Additional information**
might be related to #2520

**Comment by wigoor** [comment] 2021-04-12 14:23
Same thing happens after a disconnect/reconnect.
![chatterino_eSvebVDKWY](https://user-images.githubusercontent.com/26260419/114410023-50aa8f00-9bab-11eb-94e0-ef7afa9212af.png)

**Comment by alazymeme** [comment] 2021-04-12 14:26
Can't confirm, works just fine for me:
![image](https://user-images.githubusercontent.com/12804673/114410696-eadff680-9bee-11eb-94f2-447fc6a1575c.png)

**Comment by alazymeme** [comment] 2021-04-12 14:27
But I will mention that this is probably classed as a duplicate of https://github.com/Chatterino/chatterino2/issues/1022

**Comment by zneix** [comment] 2021-04-12 15:07
I don't think it's related to #2520, perhaps it's the same cause as with #1022 since the moderation messages are handled via PubSub. @badoge could you try restarting chatterino and checking if you can see those messages? I can't reproduce this either:
![hi mm](https://cdn.zneix.eu/kXqwznq.png)

**Comment by zneix** [comment] 2021-04-12 15:12
Duplicate of #1022

**Closed by zneix** 2021-04-12 15:12 UTC
Labels: bug
