### ISSUE TITLE
Chatterino native host problem

### ISSUE THREAD

**Issue by Jayybeel** [Chatterino/chatterino2#1473] opened 2020-01-01 01:39 UTC
I cant seem to get the extension to work. i have restarted browser and refreshed many times, disabled and re enabled the extension but im always stuck on this screen as shown in the screenshot.

![Screenshot (25)](https://user-images.githubusercontent.com/59403089/71637289-2d4c2100-2c93-11ea-8f4e-f0844c946e99.png)

the browser i am using is Brave, i have tested this on Chrome and it worked so i dont understand why it wouldn't work with Brave since its also a chromium based browser

**Comment by pajlada** [comment] 2020-01-01 10:08
Duplicate of #1294

**Closed by pajlada** 2020-01-01 10:08 UTC
Labels: bug, extension
