### ISSUE TITLE
 Chatterino closes automatically when opening the app

### ISSUE THREAD

**Issue by vex-ol** [Chatterino/chatterino2#2198] opened 2020-11-17 13:56 UTC
On my Mac with macOS Big Sur operating system version 11.0.1, the Chatterino application closes instantly as soon as the application opens, I have already uninstalled and reinstalled the application several times and the problem continues to persist, How can I solve this problem ?

**Comment by pajlada** [comment] 2020-11-17 14:07
Could you try the latest Nightly or beta version @vex-ol ? This is probably related to #2192

**Comment by erenertugrul** [comment] 2020-11-17 15:31
macOS (v2.2.3-beta2) crashed

![Screen Shot 2020-11-17 at 18 29 58](https://user-images.githubusercontent.com/27224622/99410005-04606900-2903-11eb-813c-6e476fff1c05.png)

**Comment by jam396** [comment] 2020-11-17 16:40
I'm having the same problem. Tried the latest Nightly build too.

**Comment by Cmac0801** [comment] 2020-11-17 21:02
I've been running on the Big Sur beta's for a few months with no issues (currently on 11.0.1 20B29), then suddenly yesterday the app started crashing. Didn't update macOS and didn't change Chatterino versions. 

I completely cleared everything in the settings folder (`~/Library/Application Support/chatterino/Settings/`) and now it's working again, so I'm assuming the culprit is somewhere in there. I tried replacing the new settings files with my old ones and it started crashing again, so it's definitely related. Didn't look into it any further than that though.

**Comment by Cmac0801** [comment] 2020-11-17 21:37
Fixed it by using the latest Nightly: https://github.com/Chatterino/chatterino2/pull/2192/checks?check_run_id=1408346574 

@pajlada was right, it's related to #2192 and the FFZ API change.

**Comment by pajlada** [comment] 2020-11-17 23:33
@erenertugrul @jam396 Could you try deleting your cache folder before trying again?
For **Windows**:
Delete the `%APPDATA%/Chatterino2/Cache` folder

For **Linux**:
Delete the `$HOME/.local/share/chatterino/Cache` folder: `rm -rf "$HOME/.local/share/chatterino/Cache"`

For **Mac**:
Delete the `$HOME/Library/Application Support/chatterino/Cache` folder: `rm -rf "$HOME/Library/Application Support/chatterino/Cache"`

**Comment by jam396** [comment] 2020-11-17 23:34
I just tried the Nightly build released later today and it works now! Thanks!

**Comment by erenertugrul** [comment] 2020-11-18 10:32
hi, @pajlada  i deleted $HOME/Library/Application Support/chatterino/ 
but nothing changed.
this odd 
I tried versions
2.2.1 it works
2.2.2 it works
2.2.3-beta crashed
2.2.3-beta2 crashed

my mac high sierra

**Comment by Cmac0801** [comment] 2020-11-18 10:45
@erenertugrul try this Nightly build from yesterday: https://github.com/Chatterino/chatterino2/pull/2192/checks?check_run_id=1408346574

**Comment by GabrielDuarteM** [comment] 2020-11-18 18:23
Same thing is happening with me, on windows.
I use the portable version, updated yesterday to 2.2.2-fix, and continued on using yesterday without problems. Today though, when I try to open it, chatterino opens as a white screen (image below) and closes right after (about one second later)
![image](https://user-images.githubusercontent.com/7675500/99571035-16a9d800-29d3-11eb-8838-6e5431d45b69.png)

Tried again the version 2.2.2, 2.2.1, and even 2.2.0, and the problem happens on them as well.
I also tried the latest nightly, and #2192, and deleted the cache, none of those fixed it for me.

**Comment by cheich** [comment] 2020-11-22 14:42
@GabrielDuarteM Opening once with admin privileges fixed it for me

**Comment by GabrielDuarteM** [comment] 2020-11-22 19:19
@cheich Can confirm that opening with admin privileges fixes the problem! Thanks for sharing!

**Comment by zneix** [comment] 2021-06-26 13:49
Duplicate of #2127, there's too many "chatterino crashing" / "chatterino crashing on startup" issues open, so I'll keep one open and close the other ones.

**Closed by zneix** 2021-06-26 13:49 UTC
Labels: bug
