### ISSUE TITLE
One monitor streaming support

### ISSUE THREAD

**Issue by CyrChudac** [Chatterino/chatterino2#1645] opened 2020-04-23 20:01 UTC
**Is your feature request related to a problem? Please describe.**
No problem related, I just miss that functionality.

**Describe the solution you'd like**
I would like to have a possibility of opacity setting, so you can stream and see the game through the chat window on one monitor (obviously with the 'always on top' setting is active).

**Describe alternatives you've considered**
Additional good functionality would be, to set that you need to hold a specific key to interact with the chat window (while the 'always on top' setting is active), otherwise it is click-through. So you can set the opacity to low, then play the game normaly even through the chat window and if you need to interact with the chat just press a specific button and the window becomes interactive.

**Additional context**
This is both possible for example in Restream Chat app. But I like yours more. But lack of this functionality makes me not using it...

PS: I saw there were couple requests saying something similiar, but my version seems more compact for me.

**Comment by leon-richardt** [comment] 2020-04-23 20:03
Duplicate of #1618. Although I think it would be appropriate to comment your use case there. 😄

**Comment by alazymeme** [comment] 2020-06-09 11:31
@pajlada pls close

**Closed** 2020-06-09 11:31 UTC
Labels: enhancement, needs triage
