### ISSUE TITLE
I can´t use the @ in Chatterino

### ISSUE THREAD

**Issue by Kuechenschabe** [Chatterino/chatterino2#2184] opened 2020-11-14 15:26 UTC
I can´t write the "@" in Chat but the copy works.

I use it on MacOS 10.14.6 (18G6042) I thinks this is the Problem.

The version is Chatterino 2.2.2 (commit 07fc0c3ad)

I hope this will help you. 
Kind regards

**Comment by alazymeme** [comment] 2020-11-15 02:11
This makes absolutely no sense. Could you provide more information?

**Comment by Kuechenschabe** [comment] 2020-11-15 10:00
If i type <opt>+L for the @ symbol they are nothing happens. But if i go in my Browser ich can type "@" and it copy and paste in Chatterino.

**Comment by pajlada** [comment] 2020-11-15 12:13
This is related to macOS keyboard inputs which are very different from other operating systems - I will mark this with "help wanted" as I'm not in a position to reproduce/fix this

**Comment by apa420** [comment] 2020-11-16 12:01
There has been an issue similar to this posted here, but I can't find it.

**Comment by zneix** [comment] 2021-04-15 11:56
Duplicate of #1979

**Comment by zneix** [comment] 2021-04-15 11:57
sorry, I commented on wrong issue ![xd](https://static-cdn.jtvnw.net/emoticons/v1/301512758/1.0)

**Comment by c0ldplasma** [comment] 2021-07-31 23:02
From my comment in #3099: "The Chatterino keybindings page says that "Alt + Arrow keys" should change the selected split. I just found out that arrow keys dont work for me, instead those functions are on "Alt + H/J/K/L" for whatever reason."

**Comment by pajlada** [comment] 2021-08-01 13:28
> From my comment in #3099: "The Chatterino keybindings page says that "Alt + Arrow keys" should change the selected split. I just found out that arrow keys dont work for me, instead those functions are on "Alt + H/J/K/L" for whatever reason."
> 
> So that function overwrites the @ key.

Does your keyboard have dedicated arrow keys? Or are the arrow keys accessed by using some keyboard combination like FN+something

**Comment by c0ldplasma** [comment] 2021-08-01 13:32
It has dedicated Arrow Keys. (Roccat Vulcan TKL)

**Comment by pajlada** [comment] 2021-08-01 13:47
The arrow keys seem to send the correct code, however, arrow keys always seem to *also* add the "keypad" or "numpad" modifier, which is what confuses Chatterino.

I don't think we will end up doing a quick fix for this, but rather in the PR that will rework all hotkeys (including the ability to add custom hotkeys) we'd want to ensure we take this into account.
CC @Mm2PL 

Thanks for helping me investigate @c0ldplasma

**Comment by Xrzys** [comment] 2022-01-05 22:15
Issue still exist on macos build :/

**Comment by Felanbird** [comment] 2022-01-05 22:25
> Issue still exist on macos build :/

What build specifically, commit can be found in ⚙️ -> About ( in brackets )
I ask because I'm unsure if it ended up being fixed intentionally or accidentally in #2340

**Comment by LosFarmosCTL** [comment] 2022-01-05 22:35
This issue should definitely be fixed by #2340 (it is for me) since chatterino no longer has default keybindings for VIM hotkeys (Option+HJKL), which was overwriting the macOS default keybinding Option+L for @ before that PR.

**Comment by c0ldplasma** [comment] 2022-01-05 22:45
Can confirm that its fixed in the newest nightly macos build

**Comment by Xrzys** [comment] 2022-01-05 22:46
@Felanbird Chatterino 2.3.4 (commit 4e5170799)

**Comment by Felanbird** [comment] 2022-01-05 22:47
> @Felanbird Chatterino 2.3.4 (commit [4e51707](https://github.com/Chatterino/chatterino2/commit/4e5170799fb437ff1196d748784907c7d484f42d))

That's what I expected, you can find and download the newest nightly build [here.](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build)

**Comment by Xrzys** [comment] 2022-01-05 22:49
@Felanbird on 34203dfa7 issue not longer exist

**Comment by Felanbird** [comment] 2022-01-05 22:50
Fixed by #2340

**Closed by Felanbird** 2022-01-05 22:50 UTC
Labels: bug, mac, help wanted
