### ISSUE TITLE
Something weird happend to the context menu, and the text is close to the right border now.

### ISSUE THREAD

**Issue by karl-police** [Chatterino/chatterino2#3514] opened 2022-01-15 19:45 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I remember the text within the context menu being smaller and not like that.

![image](https://user-images.githubusercontent.com/12023782/149635677-98237b55-e5c5-4c39-a9a7-c1fbb64dbecb.png)

### OS and Chatterino Version

Chatterino Nightly 2.3.4 (commit e742860af, built on ) Windows 10

**Comment by karl-police** [comment] 2022-01-15 21:09
If I change the background with setStyleSheet it fixes the text, for some reason.

**Comment by Felanbird** [comment] 2022-01-15 22:09
Unable to replicate
![image](https://user-images.githubusercontent.com/41973452/149639187-1e59bc88-3cea-4df5-afa5-602e4b73556a.png)


e742860af Windows 10 built with QtCreator

**Comment by karl-police** [comment] 2022-01-16 04:33
> Unable to replicate ![image](https://user-images.githubusercontent.com/41973452/149639187-1e59bc88-3cea-4df5-afa5-602e4b73556a.png)
> 
> [e742860](https://github.com/Chatterino/chatterino2/commit/e742860af7467ba8f4f5aac304ad9e8af0b789b7) Windows 10 built with QtCreator

Hmmm

I wonder what makes "setStyleSheet" fix it, if I change the background.

**Comment by karl-police** [comment] 2022-02-01 22:46
> Unable to replicate ![image](https://user-images.githubusercontent.com/41973452/149639187-1e59bc88-3cea-4df5-afa5-602e4b73556a.png)
> 
> [e742860](https://github.com/Chatterino/chatterino2/commit/e742860af7467ba8f4f5aac304ad9e8af0b789b7) Windows 10 built with QtCreator

I think it's caused by DPI Scaling. So, probably something maybe could be added, to globally disable DPI Scale in Chatterino?

**Comment by Nerixyz** [comment] 2024-10-14 08:20
Fixed on Windows; duplicate of https://github.com/Chatterino/chatterino2/issues/752.

**Closed** 2024-10-15 04:40 UTC
Labels: issue-report
