### ISSUE TITLE
Tab completion bug when two emotes with the same name but different capitalization are present

### ISSUE THREAD

**Issue by martinsstuff** [Chatterino/chatterino2#2369] opened 2021-01-17 18:41 UTC
**Describe the bug**

![2021-01-17_19-36-06](https://user-images.githubusercontent.com/29005772/104852484-8ec14b00-58fb-11eb-9951-91811165426c.gif)

Emotes: MEGALUL & MegaLUL (Channel: NymN)

Regardless of which of the two emotes is highlighted in the autocompleter, "MegaLUL" will filled in.

**Chatterino version**

Chatterino 2.2.2-fix (commit a82f57f94)

**Operating system**

Windows 10 20H2

**Comment by zneix** [comment] 2021-01-18 14:02
@martinsstuff I am unable to reproduce this behavior on 2.2.3-beta2 nightly 766700adc, please update to [latest nightly](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build) and see if the issue persists.
GIF with reproduction: https://cdn.zneix.eu/MtluQFG.gif
![IF YOU READ THIS YOU LOST ZULUL](https://cdn.zneix.eu/MtluQFG.gif)

**Comment by sando** [comment] 2021-01-18 14:18
Duplicate of #1962, fixed in #2133. This fix won't be present in the `2.2.2-fix` branch, but should be fixed in current beta/nightly.

**Closed** 2021-01-25 13:49 UTC
Labels: bug
