### ISSUE TITLE
"Emote images" setting displays HTML special characters incorrectly

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1118] opened 2019-06-29 18:41 UTC
To reproduce:

1. Type `<3` in a chat
2. Disable emote images in settings
3. Observe the result:
![841cd571158677ee](https://user-images.githubusercontent.com/1629196/60388189-21965c80-9aae-11e9-8160-e421484e4a74.png)

**Comment by fourtf** [comment] 2020-09-25 20:04
I don't exactly know what this means but seems fixed

**Comment by apa420** [comment] 2020-09-25 21:09
Still happens

**Comment by Mm2PL** [comment] 2021-06-18 22:27
![2021-06-19_00-26](https://user-images.githubusercontent.com/25011746/122621200-58dbea80-d084-11eb-865f-dda2ac90a156.png)
unable to reproduce

**Comment by apa420** [comment] 2021-06-18 23:09
Since twitch changed the way some of the emotes work this is now fixed.

**Closed by apa420** 2021-06-18 23:09 UTC
