### ISSUE TITLE
"Show in Mentions" must be turned on through settings.json

### ISSUE THREAD

**Issue by Kraftium** [Chatterino/chatterino2#2134] opened 2020-10-25 23:06 UTC
**Describe the bug**
"Show in Mentions" must be turned on through the settings.json file to turn on. When creating a new command or upgrading from an older commit, even when checkmarked on in the settings page, it stays false in the json and must be turned on manually through the json.

**To reproduce**
Create a new command and keep the "Show in Mentions" setting on. Even with the setting checkmarked, it wont show in mentions and wont make the tab have a red highlight on it. If you go into settings.json in the appdata, you will see that it is false. If you turn it on in the json file, it will work.

**Screenshots**
![image](https://user-images.githubusercontent.com/41495885/97121449-9518a000-16db-11eb-8df9-5fa803a75ac2.png)

![image](https://user-images.githubusercontent.com/41495885/97121453-9e097180-16db-11eb-8d6e-4e16aa546552.png)

**Chatterino version**
Chatterino Nightly 2.2.3-beta (commit 466d85c90, 25.10.2020)

**Operating system**
Windows 10

**Comment by daiexd** [comment] 2020-10-25 23:28
can replicate new highlights not showing in mentions, you seem to still be pinged in the chat, it just doesn't alert you which one even if you turn on flash taskbar. Windows 10 / Chatterino Nightly 2.2.3-beta (commit 466d85c90, 25.10.2020)
![image](https://user-images.githubusercontent.com/73288014/97121919-ed03e500-1775-11eb-8946-4c2193257681.png)
![image](https://user-images.githubusercontent.com/73288014/97121931-01e07880-1776-11eb-87d3-85f14e7c3452.png)

**Comment by leon-richardt** [comment] 2020-10-26 07:56
@Kraftium
> When creating a new command or upgrading from an older commit, even when checkmarked on in the settings page, it stays false in the json and must be turned on manually through the json.

Can reproduce on https://github.com/Chatterino/chatterino2/commit/466d85c907df6880af5149687f95c961d4ed6093 / Arch when creating new highlights. "Upgraded" highlights work for me.

> wont make the tab have a red highlight on it

Tab highlights have been broken before merging #2036 unfortunately. For example, check 0049a5ebb2b5bdb8feb7637f9a7acffc7b3cdf76 (last commit before merging #2036) where tab highlights are not applied already.


-------
@daiexd 

> it just doesn't alert you which one

Note that missing tab highlights are intended behavior, as noted in the changelog. Although this should maybe be documented somewhere in the settings as well.

**Comment by leon-richardt** [comment] 2020-10-26 08:27
I have pushed the fix for this in #2137. If you'd like you can go ahead and test the PR build to see if it fixes your issue.

**Closed** 2020-10-26 09:06 UTC
Labels: bug, needs triage
