### ISSUE TITLE
View emotion author on hover

### ISSUE THREAD

**Issue by TimaFrolov** [Chatterino/chatterino2#1720] opened 2020-06-03 18:09 UTC
**What should be added?**
View emotion author on hover

**Why should it be added?**
I think it is convenient and useful.

**Comment by cinemassacres** [comment] 2020-06-03 21:04
duplicate of #917

**Comment by TimaFrolov** [comment] 2020-06-04 06:02
Ok, I should have put it more precisely. I meant the authors of emutes in bttv / ffz like this 
![brave_kYIIDhiIg1](https://user-images.githubusercontent.com/50910468/83720621-0f1f8e00-a642-11ea-856a-2dae447a45f9.png)

**Closed** 2020-06-13 12:15 UTC
Labels: enhancement, needs triage
