### ISSUE TITLE
[Suggestion] Sorting for Tabs

### ISSUE THREAD

**Issue by LogicalSoIutions** [Chatterino/chatterino2#3077] opened 2021-07-27 19:31 UTC
I have a LOT of chat's open that I moderate for and chat in as I always have 3-5 streams open and I manually sort my tabs so the "LIVE" Channels are always towards the "front" of the chat list; reason being I like to CTRL + 1-9 through the channels.

Would love to have a way to "auto-sort" the tabs by "Live" , "Name" , or "None.

Thanks!

**Comment by apa420** [comment] 2021-07-28 08:03
Duplicate of #2810

**Closed by apa420** 2021-07-28 08:03 UTC
Labels: enhancement
