### ISSUE TITLE
Add a subscription highlight for a channel!

### ISSUE THREAD

**Issue by jeffboys123** [Chatterino/chatterino2#2718] opened 2021-04-29 17:35 UTC
**What should be added?**

Instead of a channel having a normal highlight for a new message for when someone subs or gifts a subscription to a channel it can have a purple highlight. This could be a setting that is already turned off for all channels and could be an option under "enable highlights for new messages" and have something like "enable highlights for new subscriptions". 

![image](https://user-images.githubusercontent.com/71993748/116592139-8d021d00-a917-11eb-858f-b29abdd46244.png)
![image](https://user-images.githubusercontent.com/71993748/116592171-97bcb200-a917-11eb-85db-02e4dfb96a4e.png)

**Why should it be added?**

This would most likely be used for people who are not tabbed into their own channel when getting offline subs or if you are a moderator for another channel. Sometimes it can get confusing when just seeing a normal highlight under my channel!

**Comment by zneix** [comment] 2021-04-30 05:59
Duplicate of #1543, being implemented in #1557.

**Closed by zneix** 2021-04-30 05:59 UTC
Labels: enhancement
