### ISSUE TITLE
Color @usernames not working with 7tv 

### ISSUE THREAD

**Issue by fredyacp** [Chatterino/chatterino2#2873] opened 2021-06-07 01:59 UTC
**Describe your issue**
if you install 7tv on chatterino it will not have color if you ''pong'' someone 

**Screenshots**

**OS and Chatterino Version**

**Comment by jammehcow** [comment] 2021-06-07 02:18
Please fill in the issue template instead of mangling it.

Since this is a 7tv-specific error please submit an issue [on their fork](https://github.com/SevenTV/chatterino7)
If you give proper steps to reproduce this instead of "pong" and someone can confirm it happens in base chatterino we'll pick it up.

**Comment by zneix** [comment] 2021-06-07 06:08
First of all, this has literally nothing to do with 7tv nor 7tv's Chatterino fork.
Second of all, this is a known issue which is occuring on regular Chatterino as well, duplicate of #2822

**Closed** 2021-06-07 06:08 UTC
Labels: issue-report
