### ISSUE TITLE
chatterino native needs a new update, i use version 7.3.4 and native doesnt go in the correct place 

### ISSUE THREAD

**Issue by madstingray16** [Chatterino/chatterino2#3226] opened 2021-09-05 22:23 UTC
chatterino native host not in correct position
<!--

new update 7.3.4 native doesn't go in the correct place 

  Examples:
native worked with version 7.3.2, however its not bugged with the new 7.3.4 it just isnt in the correct postion where native chat is.

[screenshot of native issue with version 7.3.4] (https://gyazo.com/e314f720f27c1072f14c0bc72933100d)

    

windows 10, google chrome, chatterino version 7.3.4

**Comment by ALazyMeme** [comment] 2021-09-06 00:54
Please check other issues as per the issue template prior to creating an issue in future. If you'd had followed accordingly, you would've seen that:
a. This should be posted on the [browser extension repo](https://github.com/Chatterino/chatterino-browser-ext)
b. There is already an issue created for it

![image](https://user-images.githubusercontent.com/12804673/132146675-8cbbca08-ecd7-44a7-b14b-ed45ca8fb027.png)

**Comment by ALazyMeme** [comment] 2021-09-06 00:54
Duplicate of https://github.com/Chatterino/chatterino-browser-ext/issues/65

**Closed by ALazyMeme** 2021-09-06 00:54 UTC
Labels: issue-report
