### ISSUE TITLE
Show emotes emojis after colon

### ISSUE THREAD

**Issue by Jckpt** [Chatterino/chatterino2#1682] opened 2020-05-11 10:32 UTC
**What should be added?**
Show emotes and emojis after colon like in FFZ 
![Screenshot of feature](https://i.imgur.com/GFlwlrh.png)
**Why should it be added?**
Autocompletion with colon is more consistent than with tab

**Comment by Mm2PL** [comment] 2020-05-11 10:34
Looks very similar to #591

**Comment by apa420** [comment] 2020-05-11 16:56
Duplicate of #375

**Closed by apa420** 2020-05-11 16:56 UTC
Labels: enhancement, needs triage
