### ISSUE TITLE
`flags.sub_message` filter showing too many message types

### ISSUE THREAD

**Issue by Fittiboy** [Chatterino/chatterino2#4231] opened 2022-12-13 10:38 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Currently, the `sub_message` flag does not appear to be working correctly!
In a split with that flag as the only filter, it shows sub messages, but also shows /announcement messages and raids.

### Screenshots

![image](https://user-images.githubusercontent.com/28876473/207295957-b3adb3fa-a97a-4264-9353-1ba80bf8631e.png)

### OS and Chatterino Version

Chatterino 2.4.0 (commit a0f93100 modified) built with Qt 5.15.2 Running on Arch Linux, kernel: 6.0.12-arch1-1

**Comment by Felanbird** [comment] 2022-12-13 17:40
Duplicate of #4163

It's working as expected...... but what is expected is wrong. Raids and Announcements were both just thrown into the sub handling, so it's only doing what our xd code says is correct.

You can mitigate this problem by changing your filter to `flags.sub_message && !((message.content == "Announcement") || (message.content == "raiders from") || (author.name == "Fossabot"))` - though this would still allow for announcements sent by other mods to show up.

**Comment by pajlada** [comment] 2022-12-17 11:37
Duplicate of #4163

**Closed by pajlada** 2022-12-17 11:37 UTC
Labels: issue-report
