### ISSUE TITLE
Blank file icon shown in place of stream thumbnail

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1972] opened 2020-09-18 14:13 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/1629196/93607547-c231ae80-f9c9-11ea-8cf9-abeb8f1b934f.png)
Chatterino is currently showing me a white "sheet of paper" icon instead of a stream thumbnail.

**To reproduce**
Not sure how to reproduce, but in my case I only have a split open for https://twitch.tv/forsen

**Screenshots**

**Chatterino version**
Chatterino Nightly 2.2.2 (commit c7a2f4cc9, )

**Operating system**
Windows 10

**Additional information**

**Comment by Mm2PL** [comment] 2020-09-18 14:15
Can reproduce on forsen's stream, not others.

**Comment by RAnders00** [comment] 2020-09-18 14:20
Thumbnail seems to work for forsen currently

https://static-cdn.jtvnw.net/previews-ttv/live_user_forsen-600x400.jpg

![image](https://user-images.githubusercontent.com/1629196/93608383-d75b0d00-f9ca-11ea-982b-34b3308589d4.png)

**Comment by apa420** [comment] 2020-09-18 18:23
This just fetches twitch's screenshot url (for the stream). So if anything it should only be twitch's fault

**Comment by RAnders00** [comment] 2020-09-18 18:44
So twitch is returning this white icon gif? I looked up the Helix "Get Streams" endpoint for forsen, and the link posted above (thumbnail url) is the URL returned from the helix api - or are thumbnails fetched differently?

**Comment by apa420** [comment] 2020-09-18 19:05
https://github.com/Chatterino/chatterino2/blob/b98c0c2a44fb99978d399d6a8436e45766a786fc/src/widgets/splits/SplitHeader.cpp#L591

**Comment by Felanbird** [comment] 2020-09-19 08:27
![image](https://user-images.githubusercontent.com/41973452/93662743-5b93ab80-fa30-11ea-8de3-8c9bc08c5da5.png)

can replicate in pajlada's stream today

**Comment by RAnders00** [comment] 2020-09-19 08:31
I think it's related to the exact size we're fetching, which is medium by default:

https://static-cdn.jtvnw.net/previews-ttv/live_user_pajlada-160x90.jpg

Even several minutes (15 minutes here in this case) the link to the 160x90 image redirects to a 404 image placeholder. Is it possible that Chatterino is not following redirects?

Twitch doesnt directly return the 404 image, instead a "302 Found" response is sent with a html page.

![image](https://user-images.githubusercontent.com/1629196/93662816-294f7180-fa63-11ea-9951-81f5a0a40f91.png)

Headers:

```
content-type: text/html
content-length: 138
location: https://static-cdn.jtvnw.net/ttv-static/404_preview-160x90.jpg
date: Sat, 19 Sep 2020 08:29:57 GMT
server: nginx
expires: Sat, 19 Sep 2020 08:44:57 GMT
cache-control: max-age=900
x-404-redirect: true
access-control-allow-origin: *
access-control-allow-methods: GET, OPTIONS
timing-allow-origin: https://www.twitch.tv
x-cache: Miss from cloudfront
via: 1.1 78aa4ecfac2dbbed080d75d85f660486.cloudfront.net (CloudFront)
x-amz-cf-pop: TXL52-C1
x-amz-cf-id: w1XyelrU5ZTfkmTb-J9Q12KYiQEoMcECFK9stOnATzH3cSw6uVGz2w==
```

**Comment by apa420** [comment] 2020-09-19 12:53
The thumbnail image is cached for 5 min on twitch's server. That's why chatterino only does a new fetch every 5 min.

If you look at the thumbnail on forsens stream right now it's the "offline stream" thumbnail (not a white gif or whatever). So I don't really know why twitch is sending a 302...

**Comment by fourtf** [comment] 2020-09-26 00:47
Can I close this? There likely isn't anything we can do if twitch returns this image

**Comment by pajlada** [comment] 2020-09-26 07:04
It looks like there is some cleanup we can definitely do around this issue - it's not only a Twitch API error.

**Closed** 2020-09-26 07:33 UTC
Labels: bug
