### ISSUE TITLE
Edit stream information within chatterino

### ISSUE THREAD

**Issue by sleepyeyesx** [Chatterino/chatterino2#2315] opened 2020-12-26 23:36 UTC
Would be nice  if we could edit the title, game, and tags within chatterino of streams we are modded in. Don't think its possible at the moment,

**Comment by Mm2PL** [comment] 2020-12-26 23:57
Please use the `Enhancement` issue template next time.

This is doable using the combination of the [Modify channel information](https://dev.twitch.tv/docs/api/reference#modify-channel-information), [Get all stream tags](https://dev.twitch.tv/docs/api/reference#get-all-stream-tags), [Get stream tags](https://dev.twitch.tv/docs/api/reference#get-stream-tags) and [Replace stream tags](https://dev.twitch.tv/docs/api/reference#replace-stream-tags) endpoints. Luckily all of which are available in the new Twitch API.

**Comment by alazymeme** [comment] 2020-12-27 04:59
Please use the search feature prior to creating an issue. As mm2pl also mentioned, please use the "Enhancement" issue option next time as it assists with us knowing exactly what you want.

Duplicate of https://github.com/Chatterino/chatterino2/issues/1300

**Comment by zneix** [comment] 2021-04-15 11:15
Duplicate of #1300, however it's been implemented in #2534

**Closed by zneix** 2021-04-15 11:15 UTC
