### ISSUE TITLE
Cant block some items in Twitch Chat.

### ISSUE THREAD

**Issue by soundtechscott** [Chatterino/chatterino2#2973] opened 2021-07-06 17:37 UTC
In Twitch chat, when somebody subscribes, a message appears...
Example:
<username> subscribed with Prime. They've subscribed for 2 months! 

or when somebody redeems channel points for special things a message appears
Example:
<username> redeemed Give H a Relic Booster Pack 2500 

I am not able to find any way to block these messages...
I've tried plain words and regex things and I cant find a way to block them...

specifically looking for a way to block the "redeemed channel points" type of things as most of them are not relevant to chat

using Windows 10 version of Chatterino

**Comment by Mm2PL** [comment] 2021-07-06 18:21
Blocks only apply to text messages sent by a user, not any special Channel Point Redemptions or Subscriptions.

**Comment by Felanbird** [comment] 2021-07-06 18:21
You want filters for this, but this will (probably)? work better once #2962 is merged

**Comment by Felanbird** [comment] 2021-07-06 18:40
As a note, both of these filters 
`!(author.no_color)` (grayname filter) & 
`((author.badges) contains ("subscriber") || (author.badges) contains ("founder") || (author.badges) contains ("moderator") || (author.badges) contains ("broadcaster"))` (my attempt at localsub) 
work to filter out ALL system messages (timeouts | bans | twitch command responses /vips /mods etc | sub notifs | channel point redemptions)

So you are probably very likely to get what you want blocked, with the filters.

**Comment by soundtechscott** [comment] 2021-07-06 19:34
anytime I try to use the || separator, it crashes 
I put all the (author) type filters in one at a time, and its fine, but non of them appear to block anything block anything

**Comment by Felanbird** [comment] 2021-07-06 19:50
> I put all the (author) type filters in one at a time, and its fine, but non of them appear to block anything block anything

Are you toggling each filter on in the specified tab? 
![image](https://user-images.githubusercontent.com/41973452/124658450-c56f2b80-de71-11eb-804b-aa56b071988f.png)
![image](https://user-images.githubusercontent.com/41973452/124658499-d1f38400-de71-11eb-83c2-694e14cb8487.png)

**Comment by soundtechscott** [comment] 2021-07-06 20:05
I didnt realize these were filters instead of ignores..

((author.badges) contains ("subscriber") || (author.badges) contains ("founder") || (author.badges) contains ("moderator") || (author.badges) contains ("broadcaster"))
disables chat 100%... 

the !(author.no_color) appears to work at blocking out all the gift subs and channel point redemption messages

**Comment by Felanbird** [comment] 2021-07-06 20:44
> ((author.badges) contains ("subscriber") || (author.badges) contains ("founder") || (author.badges) contains ("moderator") || (author.badges) contains ("broadcaster"))
> disables chat 100%...

https://i.imgur.com/DTcFs3u.gif

> the !(author.no_color) appears to work at blocking out all the gift subs and channel point redemption messages

As a note, this is intended to be used for filtering out graynames, so if you have the setting "Colorize users without a color set (gray names)" disabled, those people will be filtered out as well.

**Comment by Felanbird** [comment] 2021-11-27 16:18
I'm going to close this as it's had no updates and the implementation of #2962 happened as well.

After personal testing I can confirm that as [documented](https://wiki.chatterino.com/Filters/):

  - `!flags.sub_message` will hide subscription messages.
  - `!flags.reward_message` will hide most channel point redeemed messages.
  - `!flags.points_redeemed` will hide the "Highlight this message" that `flags.reward_message` does not.
  - `!flags.system_message` will hide timeouts/bans.

They can all be added together into a single filter like this:
`!(flags.reward_message || flags.points_redeemed || flags.sub_message || flags.system_message)`

**Closed by Felanbird** 2021-11-27 16:18 UTC
Labels: issue-report
