### ISSUE TITLE
Various emote improvements

### ISSUE THREAD

**Issue by kehlery** [Chatterino/chatterino2#2138] opened 2020-10-26 09:58 UTC
**What should be added?**

1. An option to enable more emote information to be shown in the emote thumbnail 
ie. upload date, the number of channels with the emote enabled and the origin channel for sub emotes.
<details>
<summary>Example</summary>
<img src="https://user-images.githubusercontent.com/40723238/97157198-059fdb00-1735-11eb-8caf-3e3413debd8c.png" width="200">
</details>
<br>

2. An option to instantly open the emote link via double clicking or middle clicking the emote in chat.

3. Include the ability to reverse image search selected emotes similar to what is outlined in #2058 .

4. Emotes within the emote list should be able to be interacted with in a similar fashion to emotes within chat. When right clicking on emotes in the emote list you should be able to open the emote link, the image, and perform all the actions described above exactly the same as when the emote is interacted with in chat.
<details>
<summary>Example</summary>
<img src="https://user-images.githubusercontent.com/40723238/97155366-7e516800-1732-11eb-88d0-f45acbe28920.png" width="300">
</details>
<br>
<br>

**Why should it be added?**
Using less clicks to view things is good :DDDDD

**Comment by leon-richardt** [comment] 2020-10-26 10:04
> the origin channel for sub emotes

In the future, please make sure to search existing issues for your suggestion. In fact, this feature has been suggested today (see #2135).

**Comment by zneix** [comment] 2020-10-26 11:29
request 4. is a duplicate of #1735, pretty much everything you requested is already an issue

**Comment by zneix** [comment] 2020-10-26 11:31
Also, I am afraid reverse image search is a bit too much for a project about twitch chat client and most likely it is out of its scope.

**Comment by kehlery** [comment] 2020-10-26 11:46
> Also, I am afraid reverse image search is a bit too much for a project about twitch chat client and most likely it is out of its scope.

yeah, I thought that I ought to suggest it to see if it was possible despite it being quite a task <img width="20" src="https://user-images.githubusercontent.com/40723238/97168581-ef4e4b00-1745-11eb-9c1c-0b944d3e4550.png">

**Comment by zneix** [comment] 2021-04-23 16:07
Update: 3. is out of scope of the Chatterino project and 4. is going to be fixed once I merge my Pull Request #2670 this weekend.

**Closed** 2021-04-24 15:43 UTC
Labels: enhancement
