### ISSUE TITLE
Ability to show all messages from all VIPS/MODS in a seperate tab

### ISSUE THREAD

**Issue by MildogMiller** [Chatterino/chatterino2#1980] opened 2020-09-23 14:22 UTC
**What should be added?**

Ability to show all messages from all VIPS/MODS in a seperate tab, ie, lets say John is streaming, and i open a tab for johns channel, i would suggest the ability to have an option where it only shows messages from VIPS,MODS, 

if it cant be in a seperate tab, then an option when you set someone to be highlighted, an option for all VIPS/MODS to be highlighted

**Why should it be added?**

I think it would be nice for streamers to have a sole tab for the messages for the vips and mods, that way the mods and vips stay in the same chat but its easier for the streamer to see them

**Comment by Mm2PL** [comment] 2020-09-23 14:23
duplicate of #1632 
See #1748

**Comment by apa420** [comment] 2020-09-23 17:15
duplicate of #1632

**Closed by apa420** 2020-09-23 17:15 UTC
Labels: enhancement, needs triage

**Comment by MildogMiller** [comment] 2020-09-23 17:18
How is it a dup?, I'm saying have a filter based on channel attributes,
like VIP, not name

**Comment by leon-richardt** [comment] 2020-09-23 17:26
> How is it a dup?, I'm saying have a filter based on channel attributes,
> like VIP, not name

It may not be quite as apparent from the linked issue directly but if you'd take a look at #1748 (which Mm2PL linked above), you will see that it matches your use case exactly.

**Comment by MildogMiller** [comment] 2020-09-23 18:49
oh i see

Many Thanks

Adir Miller
CEO
AAM editing
"Let's not just remember memories, Let's create them  "
Cell: 0760651753
Work Email: aamediting@gmail.com
