### ISSUE TITLE
Selecting an @Username chat message in chat history closes popup

### ISSUE THREAD

**Issue by blindfx** [Chatterino/chatterino2#2442] opened 2021-02-08 20:16 UTC
**Describe the bug**
Unable to select an @Username in the chat history(User card) to display the @'d users chat history.

**To reproduce**
1. Left click a username in chat who has used a targetted @ in a message.
2. In the chat history pop up left click the @username 

Aniticpated outcome: Chat history of the @'d user.
Actual outcome: chat history popup closes.

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit e48937e0a, )

**Operating system**
Windows 10

**Additional information**
Functionality appears to work on older 2.2.2 builds.

**Comment by Mm2PL** [comment] 2021-02-08 20:17
Can reproduce, requires auto-closing of user cards enabled.

**Comment by sando** [comment] 2021-02-09 11:30
Duplicate of #2297

**Closed** 2021-02-10 17:33 UTC
Labels: bug
