### ISSUE TITLE
multi-line messages line-wrap line jumping

### ISSUE THREAD

**Issue by daesig** [Chatterino/chatterino2#1751] opened 2020-06-22 22:22 UTC
**Describe the bug**
When a medium/large sized message is in chat, words jump lines every time a new message is sent in chat. 

Example:
I went to the store 
today and bought
an apple.

becomes:
I went to the store
today and bought an 
apple.

This alternates every time a new message gets sent in chat. It makes it really hard to read and can be distracting

**To reproduce**
Not really possible to reproduce easily. I think the combined size of your message line width + username width + timestamp determines if the problem will happen. Maybe a check that calculates if the message should be on a new line but it's off by 1 pixel?

**Screenshots**
![image](https://user-images.githubusercontent.com/45097996/85340853-2a661680-b4e7-11ea-8bfa-6a65cbdea9c1.png)

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10 Pro

**Additional information**
Theme: Dark, Font: Segoe UI, Font size: 12pt, UI scale: default
I tried playing around with font, size, ui scale but problem keeps coming back.

**Comment by Mm2PL** [comment] 2020-06-22 22:31
I'm sorry to disappoint you, but this issue might stick around for long, since there is no real way to reproduce this consistently, thus harder to pinpoint where the code at fault is located.
Does using a [Monospaced font](https://en.wikipedia.org/wiki/Monospaced_font) help?

**Comment by daesig** [comment] 2020-06-22 22:38
> 
> 
> I'm sorry to disappoint you, but this issue might stick around for long, since there is no real way to reproduce this consistently, thus harder to pinpoint where the code at fault is located.
> Does using a [Monospaced font](https://en.wikipedia.org/wiki/Monospaced_font) help?

I just downloaded this font and the problem did not go away. Feels like there really is just a real problem about deciding if a word should be on the same line or new line :(

https://fonts.google.com/specimen/Space+Mono?sidebar.open&selection.family=Space+Mono#standard-styles

**Comment by pajlada** [comment] 2020-11-22 14:07
As I'm unable to reproduce this, I will go ahead and close this issue. If you figure out a way to reproduce it, please re-open this issue and ping me

**Closed by pajlada** 2020-11-22 14:07 UTC
Labels: bug
