### ISSUE TITLE
Twitch Animated emotes are not animated on chatterino

### ISSUE THREAD

**Issue by ImDini** [Chatterino/chatterino2#2984] opened 2021-07-09 01:21 UTC
**Describe your issue**

All bttv emotes are animated on my client but the new twitch animated emotes only show the first frame as a static image (non animated)

https://i.imgur.com/csicbnn.mp4

**OS and Chatterino Version**

        Windows 10, Chatterino 2.3.2

**Comment by jeffboys123** [comment] 2021-07-09 01:41
This is already implemented in the nightly version.

**Comment by Felanbird** [comment] 2021-07-09 01:46
As mentioned above, this has been implemented on nightly since 6611c24e1375380037a1aaff94b2709d8d5f827a

**Comment by zneix** [comment] 2021-07-09 01:56
Duplicate of #2897

**Closed by zneix** 2021-07-09 01:56 UTC
Labels: issue-report
