### ISSUE TITLE
Channel Specific Mention Tabs 

### ISSUE THREAD

**Issue by mvnkey-twitch** [Chatterino/chatterino2#1791] opened 2020-07-07 05:22 UTC
**What should be added?**
i would like a mention tab that is channel specific so that when i get pinged it wouldnt show up in other mention tabs.

**Why should it be added?**
 because personally i have a mention tab on every tab i have, so when i get pinged all my tabs become red which mean if someone talks in a chat that isnt spamy i wouldnt know cuase its already red.

**Comment by DuskDarker** [comment] 2020-07-07 05:28
true

**Comment by leon-richardt** [comment] 2020-07-07 07:39
Duplicate of #518, being worked on in #1748.

**Comment by apa420** [comment] 2020-07-07 20:11
Duplicate of #518

**Closed by apa420** 2020-07-07 20:11 UTC
Labels: enhancement, needs triage
