### ISSUE TITLE
Failing to load a user card will crash chatterino

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1615] opened 2020-03-28 08:30 UTC
**Describe the bug**
Clicking on a user card then immediately clicking off it before it loads crashes chatterino

**To reproduce**
1. Click user card
2. Immediately click off of it before it loads

**Screenshots**
https://i.nuuls.com/fE5LT.gif

**Chatterino version**
Chatterino Nightly 2.1.7 (commit d1d17d4e4, 27.03.2020)

**Operating system**
Windows 10

**Comment by Mm2PL** [comment] 2020-03-28 10:36
Cannot reproduce on `d1d17d4e4` on Linux.

**Comment by apa420** [comment] 2020-03-28 23:02
I also can't reproduce on windows 8.1`6229b2f43`

**Comment by alazymeme** [comment] 2020-03-29 00:01
The weird part is that I can consistently reproduce this. I wonder if it's a Windows 10 exclusive issue

**Comment by gwua** [comment] 2020-03-29 00:06
Fellow Win10 user here, I was able to reproduce the crash. https://github.com/Chatterino/chatterino2/commit/d1d17d4e4b764db010260bc77d76eccbb92a2376

**Comment by alazymeme** [comment] 2020-03-29 00:10
Crashed for 99froxy, d1d17d4
![image](https://user-images.githubusercontent.com/12804673/77836845-610ce900-71a5-11ea-8c49-8b05c2e52992.png)

**Comment by alazymeme** [comment] 2020-03-29 00:11
Crashed for spacewalrus, d1d17d4 - windows 10
![image](https://user-images.githubusercontent.com/12804673/77836855-9e717680-71a5-11ea-9aec-e1c06324594f.png)

**Comment by alazymeme** [comment] 2020-03-29 00:15
I tested this on a stable portable version, the crash doesn't occur: Chatterino 2.1.7 (commit 845c8fa63)

**Comment by MastonDZN** [comment] 2020-04-02 15:44
I can reproduce this on windows 10, Chatterino Nightly 2.1.7 175e41c58

**Comment by apa420** [comment] 2020-04-02 16:02
Tried again on a newer version of chatterino `175e41c58` and it does now crash on windows 8.1

**Comment by apa420** [comment] 2020-04-02 16:10
Git commit `9a8b85e33` makes chatterino crash, commit `2e39dd4d9` works as intended.

**Comment by pajlada** [comment] 2020-04-05 11:03
Fixed in master

**Closed by pajlada** 2020-04-05 11:03 UTC
Labels: bug, needs triage
