### ISSUE TITLE
ucrtbase.dll crash [Windows]

### ISSUE THREAD

**Issue by Felanbird** [Chatterino/chatterino2#2774] opened 2021-05-13 04:32 UTC
**Describe your issue**

I'm just going to start with the fact that I'm 99% sure this is a windows issue, but just incase somebody has had it and fixed it with something that google searching doesn't know about, I'm opening the issue.

Somewhere around 2021-04-27 (That's the oldest crash log I can find) this started happening, was using 1f5b62e6e when the crashes originally started.

I've been able to deduce that the crashes only happen in the evening/night PST (via EST testing), Had no crashes before 6pm PST, and nothing after 5am PST.

Interestingly enough when the crash takes place, only one of my Chatterino instances crashes (main), but if the main crashes and isn't re-opened for long enough, the secondary window usually will crash (sort of like the main Chatterino is taking the bullet).

Googled options checklist:
> Clear AutomaticDestinations (quick access) cache ✓

> DISM.exe /Online /Cleanup-image /Restorehealth & sfc/scannow ✓

> Uninstall Display Drivers ✓

idk maybe we still have a windows god of war in this circle of arch linux btw-ers

**Screenshots**

![image](https://user-images.githubusercontent.com/41973452/118076484-41705a00-b380-11eb-8bd7-9f68bb1d4484.png)

![image](https://user-images.githubusercontent.com/41973452/118076431-23a2f500-b380-11eb-8d9b-469184979a35.png)
I've been asking people to check their crash logs for at least a week and finally somebody had the same crash

**OS and Chatterino Version**

Windows 10 Pro 19041.928

d59bb80 -> 1f5b62e6e | consistant between various versions in this commit range

**Comment by Mm2PL** [comment] 2021-05-13 07:37
After a little googling I found that `0xc0000409` is `STATUS_STACK_BUFFER_OVERRUN`

**Comment by Felanbird** [comment] 2021-05-13 07:43
> After a little googling I found that `0xc0000409` is `STATUS_STACK_BUFFER_OVERRUN`. The [StackOverflow thread](https://stackoverflow.com/questions/23409809/windows-7-exception-code-0xc0000409) also mentions Qt but the crash is in the app itself not `ucrtbase.dll`.

Actually now that you point out `0xc0000409` I realize it does apply to #2229 & #2323 | when I originally searched I must have misspelt `ucrtbase.dll` so no issues came up, but copy pasting the error code brings leads me to both of them.

**Comment by IMNdi** [comment] 2021-05-13 12:53
All mine are all the same for stable release (I have many of these but they are identical). I have found no pattern to them. They happen as I type, as it is alt+tabbed, when in game or when system is clean.

> ucrtbase.dll, version: 10.0.18362.1110
> Exception code: 0xc0000409
> Fault offset: 0x000000000006dace
> Faulting module path: C:\WINDOWS\System32\ucrtbase.dll

I have since abandoned that build for the latest nightly. By the way, actually adding version info to the exe would make this way easier to track across builds. All Chatterinos I have have no correct version resource.

**Comment by Still34** [comment] 2021-05-15 20:45
Experiencing the same crash after updating to v2.3.1.

**Comment by Still34** [comment] 2021-05-15 20:53
Found the root cause, https://github.com/Chatterino/chatterino2/blob/0a51252b761ac4a846725ce6b6e8cf8bba5efdf4/src/singletons/NativeMessaging.cpp#L153

![image](https://user-images.githubusercontent.com/5843208/118377889-0a61a900-b60b-11eb-8f4e-174b519b53ac.png)

**Comment by fourtf** [comment] 2021-05-15 22:26
I guess I could make starting the ipc thing a setting if you want to use the extension

**Comment by Still34** [comment] 2021-05-16 18:24
Confirm fixed in the latest nightly.

**Comment by Felanbird** [comment] 2021-05-16 23:00
> Confirm fixed in the latest nightly.

As much as I believe your God of War Windows ability, I am going to leave this issue open for a few days while I test this new commit 😁

**Comment by Felanbird** [comment] 2021-05-18 05:05
![image](https://user-images.githubusercontent.com/41973452/118592839-9f33e600-b774-11eb-9713-4fec6f9d5270.png)
I have unfortunately crashed | 2021-05-18 00:55:59 EST

**Comment by alazymeme** [comment] 2021-05-18 08:00
Crashing never seems to happen when I'm running Chatterino in debug mode ![LULE](https://cdn.betterttv.net/emote/60477a2f306b602acc599abf/1x)

**Comment by Mm2PL** [comment] 2021-05-18 08:33
Schrödinger's bug ![MegaLUL](https://cdn.frankerfacez.com/emote/119959/1)

**Comment by Still34** [comment] 2021-05-18 11:24
Haven't been able to repro yet 😞

**Comment by Felanbird** [comment] 2021-05-25 07:24
I was going to checkback after 1 week as I have no longer gotten any crashes since 2021-05-21~ , but unfortunately I got a qt related crash which ruined my testing. I do know of someone who still gets the crashes but I myself am unable to replicate them anymore.

qt crash error incase its somehow related

```
Faulting application name: chatterino.exe, version: 0.0.0.0, time stamp: 0x60a17e1d
Faulting module name: Qt5Core.dll, version: 5.15.2.0, time stamp: 0x5fa4dd3b
Exception code: 0xc0000005
Fault offset: 0x00000000001f1df7
Faulting process id: 0x3a00
Faulting application start time: 0x01d74d6beb992afb
Faulting application path: C:\Users\Felanbird\Desktop\2021_05_16_chatterino2\Chatterino2\chatterino.exe
Faulting module path: C:\Users\Felanbird\Desktop\2021_05_16_chatterino2\Chatterino2\Qt5Core.dll
Report Id: 6c4495c0-6af7-4224-be2b-ae8e26188c1c
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Still34** [comment] 2021-05-25 18:29
At least it's a different exception code this time around, but that still suggests something is broken somewhere related to memory.

**Comment by Felanbird** [comment] 2021-05-26 02:36
back to the normal error, that's what I get for jinxing it
```
Faulting application name: chatterino.exe, version: 0.0.0.0, time stamp: 0x60a17e1d
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0x4390
Faulting application start time: 0x01d751355810d16f
Faulting application path: C:\Users\Felanbird\Desktop\2021_05_16_chatterino2\Chatterino2\chatterino.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 7f1fc466-b65a-43cb-94a6-a47c6e05a629
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Trung0246** [comment] 2021-06-11 08:33
Hello, apparently somehow I trigger this bug very frequently
![image](https://user-images.githubusercontent.com/11626920/121656406-4cd4a500-ca54-11eb-87b0-83720e2ed9da.png)

**Comment by Felanbird** [comment] 2021-06-18 04:11
Alright so here's my update, I went with no crashes from 05/26 to 06/06, I decided to update, now I've been using nightly as portable versions of Chatterino for as long as I can remember, but I forgot to mention it since it's basically second nature to me. 

`all times are EST`


So when I downloaded this new version and moved my settings folder over, I eventually crashed an hour or so later, 06/06 04:36:17, so I had a thought about the fact that I'm using a new Chatterino with a brand new cache, I wonder if this is somehow related? 
The next crash happens at 17:09:39 EST, and I decide to haul my old cache over to this new portable instance, and after I do this, I have no crashes until around 9am EST on 06/10 when I have to restart my PC, but this doesn't cause any immediate crashes the crashes don't start until 06/10 23:54:50 EST, 06/11 01:31:00 & 06/11 02:20:20. 

From then there's no crashes until 06/14 22:33:06, and then today crashes at 06/17 23:13:32 & 06/17 23:34:19, but these 2 crashes on 06/17 included 2(?) crashes that Chatterino handled and properly restarted, the problem being after the second handled crash, I was met with the following 
![image](https://user-images.githubusercontent.com/41973452/122504356-2a003e80-cfc8-11eb-82d3-a0dcadf69a6b.png)
 
Only after the second ucrtbase crash did I ask them to check Event Viewer to which I was informed that there was a ucrtbase crash log. (also this user has Chatterino via the installer so it's not some crazy nightly bug)

![image](https://user-images.githubusercontent.com/41973452/122503067-c5dc7b00-cfc5-11eb-90cd-1e0fe2b3199c.png)

Summary: I thought I was able to replicate the issue with cache "testing", but honestly I have no idea, I can't see any world where this isn't some God of War windows issue, purely based on how often it happens in the middle of the night. 🤷

**Comment by Felanbird** [comment] 2021-06-18 05:22
![image](https://user-images.githubusercontent.com/41973452/122510372-78670a80-cfd3-11eb-9994-73a877974ec4.png)

emote is NODDERS incase of confusion

**Comment by ALazyMeme** [comment] 2021-07-03 08:37
Mine just crashed twice over the last hour, same ucrtbase crash.

**Comment by Cragsand** [comment] 2021-08-12 22:37
I have the same mysterious issue and have been having it for a long time. After leaving Chatterino running for days it tends to crash leaving `ucrtbase.dll, version 10.0.19041.789` in the windows error log. This happens on two separate tested PC:s.

I used to stick to the old version of Chatterino 2.2.2 for a long time until Twitch implemented rate limiting of being in over 20 channels at once, https://github.com/Chatterino/chatterino2/issues/3107 which forced me to update. 

Trying to track down the reason for the bug I've done a bit of testing and for 5 days I'm running two fresh portable versions of `Chatterino 2.3.4` having divided all channels I watch into two separate executable instances. One with 18 tabs open and another with 30 open. Strangely enough it only occurs on the one with 18 open of which I'm moderator in most, perhaps its connected to that?

**Comment by ReggX** [comment] 2021-09-28 20:37
I also have this happen from time to time at random. Event viewer shows the same 409 exception code others have already posted. Most of the time I don't even notice the crash immediately since Chatterino is sitting in the background and disappears quietly.

**Comment by brian6932** [comment] 2022-04-20 02:55
![image_204](https://user-images.githubusercontent.com/18603393/164140860-fe210f6c-3c6a-4825-9bd3-ea4cc8090403.png)
I just got this too 🤔 It wasn't happening on my normal window-layout, but I used a friend's one cause he was having crashing, and it seems like that is what triggered this.

**Comment by 12932** [comment] 2022-04-25 18:24
Happened twice to me in the past 3 days:

```
Faulting application name: chatterino.exe, version: 0.0.0.0, time stamp: 0x624c33f4
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0x9428
Faulting application start time: 0x01d854f3993b196f
Faulting application path: C:\Program Files\Chatterino\chatterino.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: dd638033-18c9-423d-86cb-37dfd1491638
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Faulting application name: chatterino.exe, version: 0.0.0.0, time stamp: 0x624c33f4
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0xcce0
Faulting application start time: 0x01d857514b178887
Faulting application path: C:\Program Files\Chatterino\chatterino.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 75a52754-2261-4463-a8bb-cde3eec0728e
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by 12932** [comment] 2022-04-25 18:42
A user on Whingepool forums says it's related to the amount of "user objects" in the GDI layer of Windows 10 processes

https://forums.whirlpool.net.au/archive/3qr1m6p7

"After an EXHAUSTIVE search have found the culprit – a limit of 10,000 USER OBJECTS in the GDI layer of Windows 10 per process. This can be increased to 18,000 by registry hacks. Note there is a HARD overall limit (presumably per login session) mandated by the use of 16 bit pointers in the GDI layer."

https://randomascii.wordpress.com/2020/05/10/gdi-leaks-and-the-importance-of-luck

I'm going to test this and see if it's true, I have Process Hacker open with the GDI Handle column enabled and will monitor it as I leave Chatterino open. It's currently at 279 handles

![image](https://user-images.githubusercontent.com/68835423/165152758-65664be7-d920-4de9-b60f-c938f7780136.png)


Note that this probably only relates to `Fault offset: 0x000000000007286e`

**Comment by 12932** [comment] 2022-04-30 11:21
It crashed after 5 days of being open I had WinDbg attached to it here's the call stack when it crashed:

![image](https://user-images.githubusercontent.com/68835423/166103448-a28b07b3-fa4b-4268-a923-96bdc95bcbc2.png)

**Comment by brian6932** [comment] 2022-05-09 07:04
>It wasn't happening on my normal window-layout

Well scratch that, it happened on my normal window-layout too now
![image_234](https://user-images.githubusercontent.com/18603393/167354597-5d145de7-28aa-4924-b8f1-fbb58bf38a52.png)
The `window-layout.json` has 32 tabs and 42 splits with unique channels

**Comment by Cragsand** [comment] 2022-06-28 19:28
> A user on Whingepool forums says it's related to the amount of "user objects" in the GDI layer of Windows 10 processes
> 
> https://forums.whirlpool.net.au/archive/3qr1m6p7
> 
> "After an EXHAUSTIVE search have found the culprit – a limit of 10,000 USER OBJECTS in the GDI layer of Windows 10 per process. This can be increased to 18,000 by registry hacks. Note there is a HARD overall limit (presumably per login session) mandated by the use of 16 bit pointers in the GDI layer."
> 
> https://randomascii.wordpress.com/2020/05/10/gdi-leaks-and-the-importance-of-luck
> 
> I'm going to test this and see if it's true, I have Process Hacker open with the GDI Handle column enabled and will monitor it as I leave Chatterino open. It's currently at 279 handles
> 
> ![image](https://user-images.githubusercontent.com/68835423/165152758-65664be7-d920-4de9-b60f-c938f7780136.png)
> 
> Note that this probably only relates to `Fault offset: 0x000000000007286e`
> 
> Edit: ~24 hours later and it's only at 304 handles, and i've been using it like I normally would Edit2: 4 days later its at 332 handles, so the issue might be something else.. Unless theres a specific condition where it spawns handles like crazy

If GDI leaks is the reason this is happening, would it be possible to implement preventive measures?
https://www.deleaker.com/blog/2021/12/16/gdi-leaks-how-to-identify-and-fix-them/ 

Unfortunately I don't have enough experience on how but looking up "GDI leaks" and similar list some examples for prevention.

**Comment by pajlada** [comment] 2024-04-07 08:58
This shouldn't happen with the latest nightly version, and definitely not in the upcoming stable release.
If you're able to reproduce this on the latest nightly version, please re-open this issue!

**Closed by pajlada** 2024-04-07 08:58 UTC
Labels: bug, OS: Windows
