### ISSUE TITLE
Split Screen Resizing broken on Windows 11

### ISSUE THREAD

**Issue by CycIoneTM** [Chatterino/chatterino2#4234] opened 2022-12-14 22:43 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

To reproduce my issue just Spit Screen Chatterino and another window and try making Chatterino bigger.

### Screenshots

https://user-images.githubusercontent.com/25011746/207876554-ea88f796-4fae-48d0-aea3-fcc42d640d29.mp4

Original upload: https://kappa.lol/CUeGY

### OS and Chatterino Version

Chatterino Nightly 7.4.0 (commit eaa69978 modified, 2022-12-07) on Windows 11

**Comment by kornes** [comment] 2022-12-15 03:55
appears to be regression, win10 2.4.0 is also affected while 2.3.5 works, i will look into it at weekend.
You can check if 2.3.5 works for you on win11

**Comment by Felanbird** [comment] 2022-12-15 04:02
> appears to be regression, win10 2.4.0 is also affected while 2.3.5 works, i will look into it at weekend. You can check if 2.3.5 works for you on win11

win10 2.4.0 works fine for me, not perfectly consistent but reasonably. I can replicate the inconsistency with applications that aren't Chatterino

**Comment by kornes** [comment] 2022-12-23 20:14
turns out it's not a bug, but default windows 10/11 behavior when always-on-top (`HWND_TOPMOST` flag) is set. 
When window is topmost, aero snap/docking will work on edges of the screen, but not on other windows, so side by side resizing will be broken.
Confirmed its not Qt specific problem, tested few random win32 apps and even windows task manager (options ->always on top) has same issue. 

Don't see simple way to fix that, because whole docking has no api and afaik its handled outside of window manager, so there are no specific window messages to even detect docking happened, just generic resizing/moving aftermath.

**Comment by pajlada** [comment] 2022-12-24 11:36
Thank you for the thorough investigation @kornes - closing as wont-fix

**Closed by pajlada** 2022-12-24 11:36 UTC
Labels: bug, OS: Windows, help wanted
