### ISSUE TITLE
Can't send messages [Windows 11]

### ISSUE THREAD

**Issue by mfmarlow** [Chatterino/chatterino2#3467] opened 2022-01-05 00:14 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Since installing Windows 11, I can't use the enter key to send messages. When I press enter, it adds a new line to my message instead of sending it. 

### OS and Chatterino Version

Windows 11 (version 21H2 | build # 22000.376),  Chatterino Nightly 2.3.4 (commit 79db02aa6, )

**Comment by Felanbird** [comment] 2022-01-05 00:20
#3363 with https://github.com/Chatterino/chatterino2/issues/2844

You should be able to see the channel name highlighted in white when this issue happens, and highlighted in blue (via actually clicking into chatterino) when the issue is "resolved"
![image](https://user-images.githubusercontent.com/41973452/148141398-38591a6f-0ffa-48ee-a898-7b80789c3574.png)
vs
![image](https://user-images.githubusercontent.com/41973452/148141364-dc50183c-72f2-4048-8a07-b27e70bcac4b.png)

**Comment by ALazyMeme** [comment] 2022-01-05 09:10
I still get this bug every now and then, no idea what causes it; but seems to somewhat be when I open a new split (not consistent)

**Comment by romeogiggletoes** [comment] 2022-01-06 07:48
I only get this when I disable the "show input when it's empty" setting, in which case it happens quite frequently. Quiet annoying as I like this setting 😞 
![2022-01-06 02_47_14-Chatterino Settings](https://user-images.githubusercontent.com/97059214/148347667-2c587467-a4ae-4a2d-b723-ffa0042400db.png)

**Comment by LosFarmosCTL** [comment] 2022-01-06 08:30
> I only get this when I disable the "show input when it's empty" setting, in which case it happens quite frequently.

Yes, that setting is sadly a bit buggy rn, in that it messes with the way splits are being focused. If you take a look at the channel name in the split header, if the split is currently focused it should appear blue.
Now, with “Show input when its empty” disabled, press i.e. Ctrl+E to open the emote picker and close it again using ESC. You will see that while you can still type messages, the split itself is no longer focused (channel name is displayed white) and does not receive key presses correctly, which results in all hotkeys seizing to function (see #2714 #2844). Previously that meant things like Ctrl+E, Ctrl+F etc stopped working, but since #2340 that includes whatever keybinding you have set to send a message as well, thus enter is not being caught by chatterino itself but instead the text field just creates a new line.

**Comment by mfmarlow** [comment] 2022-01-06 23:21
Fixed. Turns out all of my keybindings had been removed somehow.

**Comment by Mm2PL** [comment] 2022-01-06 23:26
@mfmarlow did you happen to turn off your PC while Chatterino was still running? I have a little suspicion that hotkeys don't save properly if you do that but instead they just get emptied.

**Comment by VulpesHD** [comment] 2022-01-07 13:25
I just updated Chatterino last night. Coming from a month or 2 old build and I get this issue way too much. Basically I can't chat at all. Haven't had it before ever.

**Comment by Mm2PL** [comment] 2022-01-07 13:37
> [14:34:16.059] Mm2PL: if it's empty just reset it FeelsDankMan 
> [14:34:39.471] VulpesHD: okay that fixed it PagMan

**Comment by L1Q** [comment] 2022-01-15 04:35
had this issue today, apparently, all my hotkeys really did go away somehow

**Comment by Felanbird** [comment] 2022-01-15 04:37
> had this issue today, apparently, all my hotkeys really did go away somehow "Reset to defaults" in the "Hotkeys" tab fixed it for me.

Update to the newest nightly, we attempted to blind fix this in dfa3818a701d5445dea10c102712404fbc104f27

**Comment by L1Q** [comment] 2022-01-15 04:45
I'm using [chatterino2-nightly-appimage](https://aur.archlinux.org/packages/chatterino2-nightly-appimage/) because building from source takes an eternity. Would be nice if that package got updates every now and then.

**Comment by Felanbird** [comment] 2022-01-15 04:57
> the appimage the package is downloading would always be the latest.

Correct, while the date is not updated, the source of the appimage in the package comes directly from our automated builds, found [here](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build) which was last updated 5 hours ago.

**Comment by L1Q** [comment] 2022-01-15 04:58
Is there anything to test now that I do have the latest nightly?
If the issue was that the hotkeys can be wiped randomly, it's not like there are steps to reproduce here.

**Comment by Felanbird** [comment] 2022-01-15 05:02
> Is there anything to test now that I do have the latest nightly? If the issue was that the hotkeys can be wiped randomly, it's not like there are steps to reproduce here.

More or less no, as mm2pl mentioned above, he believed it to be related to the hotkeys not being saved correctly, so other than attempting to turn off your machine while Chatterino is open, you are basically just waiting to see if it breaks again.

**Comment by L1Q** [comment] 2022-01-15 05:05
My computer did go down unexpectedly multiple times while chattering was running, not that I would notice the issue right away, but yeah something to keep an eye on from now on :D

**Comment by BluMarshmallow** [comment] 2022-08-11 08:20
I have the same Issue in macOS. 
It happens usually after i use the emote inline search and tab for autocomplete.

**Comment by pajlada** [comment] 2022-08-11 16:54
> I have the same Issue in macOS. It happens usually after i use the emote inline search and tab for autocomplete.

What version of Chatterino are you using? Commit hash is relevant if running a nightly version

**Comment by pajlada** [comment] 2024-04-07 08:59
I suspect this isn't reproducible in the latest nightly version or in the upcoming stable release. If it happens for you, please re-open this issue.

**Closed by pajlada** 2024-04-07 08:59 UTC
Labels: issue-report
