### ISSUE TITLE
Old ffz vip badge shown

### ISSUE THREAD

**Issue by telvann** [Chatterino/chatterino2#2852] opened 2021-06-02 12:01 UTC
**Describe your issue**
- Change ffz vip badge
- Start chatterino
- Badge shows correctly
- Change badge again
- Restart chatterino
- Chatterino still shows old badge (even more than a month later)
- Clearing the cache manually resolves this

**OS/Chatterino Version**
Windows commit 508fea63

**Comment by talneoran** [comment] 2021-06-02 12:53
I've noticed this as well, seems to be the same problem as #2094 
Maybe a solution that specifically refreshes the cached badges is needed, as mentioned in the other issue. The option to clear the cache from the app (#2750) could also be useful here.

**Comment by zneix** [comment] 2021-06-02 13:12
Duplicate of #2094

**Closed by zneix** 2021-06-02 13:12 UTC
Labels: issue-report
