### ISSUE TITLE
Can't send messages in chat while connected to VPN

### ISSUE THREAD

**Issue by Dibblay** [Chatterino/chatterino2#2978] opened 2021-07-07 22:02 UTC
While connected to VPN (Mullvad), I'm not able to send messages in chat.  Everything is fine and works on the Twitch browser, just having issues with sending messages in chat with Chatterino.  Any help is appreciated, thank you!

**Comment by Mm2PL** [comment] 2021-07-07 22:06
This is because chatterino uses IRC port (6697) not the HTTPS one which the browser chat uses. Duplicate of #1666.

**Closed by Mm2PL** 2021-07-07 22:06 UTC

**Comment by dylan-dot-tech** [comment] 2023-08-08 18:28
> While connected to VPN (Mullvad), I'm not able to send messages in chat. Everything is fine and works on the Twitch browser, just having issues with sending messages in chat with Chatterino. Any help is appreciated, thank you!

I know this is a couple years old but figured I'd post my workaround here should anyone else benefit from it. The idea is to create a very basic bash script that will open Chatterino in a split tunnel via Mullvad CLI:

1. Create and save the following `chatterino.sh` bash file:

```sh
#!/usr/bin/env bash
mullvad-exclude chatterino "$@"
```

2. Set the newly created script as executible via `chmod +x chatterino.sh`
3. Open Streamlink Twitch GUI settings
4. Navigate to the `Chat` tab
5. Set the `Chatterino executable` field to the **full** filepath of your newly created `chatterino.sh` script, ex: `/home/USER/Documents/Development/chatterino.sh`

Chatterino will now open via split tunnel when using Streamlink Twitch GUI and allow for you to send messages as normal. Keep in mind that this will expose your IP to all backend services that are connected to Chatterino.
