### ISSUE TITLE
Mentions, Whispers, Live tabs stop working on restart

### ISSUE THREAD

**Issue by Coldblackice** [Chatterino/chatterino2#2914] opened 2021-06-23 07:41 UTC
**Describe your issue**

When starting Chatterino, previous tabs are properly restored, however "/mentions", "/whispers", and "/live" tabs are empty, not fetching their data from the last use (which might be by design), but they also don't "connect" to start functioning from that point forward. The only way to get them working is closing and recreating them as new tabs.

As for the previous data retrieval, it would be useful if this could also be logged/retrieved, since sometimes Chatterino crashes, taking with it an unread tab of mentions/whispers that doesn't get restored.

**OS and Chatterino Version**

Windows 10 Pro
Chatterino Nightly 2.3.2 (e352d7b31)

**Comment by leon-richardt** [comment] 2021-06-23 07:45
> but they also don't "connect" to start functioning from that point forward. The only way to get them working is closing and recreating them as new tabs.

Can you elaborate on this part? I'm not sure I understand it correctly

**Comment by talneoran** [comment] 2021-06-23 07:54
As for the first part, this is a duplicate of #2572, excluding `/live` that didn't exist before, and I'm unsure if restoring messages makes sense in that split regardless.

**Comment by Felanbird** [comment] 2021-06-23 17:01
As mentioned above the core of your issue is a duplicate, as we pull recent-messages from an external service. 

As for the bug part of your issue, I'm unable to replicate it on 97b9bfb, win10, https://i.imgur.com/kI7VCnW.gif 
My mentions tab works immediately without any need for the tab to be re-opened. 

(Though I did test this on a portable instance)

**Comment by sando** [comment] 2021-06-23 17:12
>they also don't "connect" to start functioning from that point forward. The only way to get them working is closing and recreating them as new tabs.

Can't replicate on e352d7b31 - although only tested with whisper and mentions "channels", they seem to work fine after restart. Of course, no history is preserved to reasons alluded to above.

**Comment by zneix** [comment] 2021-06-26 15:30
@Coldblackice this might be most likely due to behavoir described in #779, can you confirm? I also sometimes run into this issue myself on rare occasions. A "fix" when this happens is to hold `Ctrl` and use resize handles between splits to change size of a split with either of those special channels to minimum and messages magically appear there. I'll make sure to post a video / gif next time this happens.

**Comment by zneix** [comment] 2021-06-26 15:31
Assigning myself, so I won't lose the track of the issue ;)

**Comment by Felanbird** [comment] 2021-06-26 16:30
> this might be most likely due to behavoir described in #779,

can replicate with "smooth scrolling on new messages" on

**Comment by pajlada** [comment] 2022-08-12 19:20
Closing in favour of #779 as that's the underlying bug - fixing that will fix this

**Closed by pajlada** 2022-08-12 19:20 UTC
Labels: bug
