### ISSUE TITLE
Live indicator in tabs not showing when set to anonymous.

### ISSUE THREAD

**Issue by av98911** [Chatterino/chatterino2#1932] opened 2020-09-02 00:58 UTC
The latest few chatterino builds 2.2.2, 2.2.1, and 2.2.0 all have this issue where if I set myself to anonymous the live indicator (red dot top corner) will no longer show for streams. It shows again when I swap back to my account. To reproduce, set yourself to anonymous, restart chatterino, then check. The indicators should be gone. Set yourself back to your account, restart, and the indicators will show again. This behavior did not happen back in version 2.1.7.

**Comment by apa420** [comment] 2020-09-02 05:57
Duplicate of #1915

**Closed by apa420** 2020-09-02 05:57 UTC
Labels: bug, needs triage
