### ISSUE TITLE
Adding title and game category in the notification.

### ISSUE THREAD

**Issue by mambans** [Chatterino/chatterino2#1297] opened 2019-09-07 23:00 UTC
Possible to add stream title and game category in the notification?

**Comment by savabozo** [comment] 2019-09-08 08:15
Duplicate of #1124 ?

**Comment by mambans** [comment] 2019-09-08 13:49
Not exactly, I mean in the windows 10 notification where it currently says the streamers channel name and "Click to open in browser".

**Comment by ALazyMeme** [comment] 2021-08-24 12:23
Closing in favour of https://github.com/Chatterino/chatterino2/issues/3196

**Closed by ALazyMeme** 2021-08-24 12:23 UTC
Labels: enhancement
