### ISSUE TITLE
Streamer's new emotes don't show in the emote menu or autocomplete weeks after they were added

### ISSUE THREAD

**Issue by Velegand** [Chatterino/chatterino2#3011] opened 2021-07-14 17:43 UTC
The streamer Emiru added new emotes, I think it was a few weeks ago and they still aren't showing up in the menu or emote autocomplete

**Screenshots**
Twitch emote menu
![Screenshot 2021-05-08 015645](https://user-images.githubusercontent.com/69394829/125666971-b1543b09-7c61-42bd-86cb-1c3d709af98e.png)
Chatterino emote menu
![Screenshot 2021-05-08 015645](https://user-images.githubusercontent.com/69394829/125666640-1bfe77f9-3546-42e6-9fcc-5f8eb1de847f.png)

**OS and Chatterino Version**
Windows 10, Chatterino Nightly 7.3.3 (commit d9372S4b6 )

**Comment by Mm2PL** [comment] 2021-07-14 17:44
Duplicate of #2935

**Closed by Mm2PL** 2021-07-14 17:44 UTC
Labels: issue-report
