### ISSUE TITLE
Twitch rewards not showing

### ISSUE THREAD

**Issue by Romexin** [Chatterino/chatterino2#3259] opened 2021-09-28 17:29 UTC
Hello when i redeem something in twitch chat,it doesn't show up in my chatterino.I tried to uninstall and install but nothing helped

My chatterino version is 2.3.4
![d7qL](https://user-images.githubusercontent.com/91560977/135136380-d84f4645-8d7c-474c-a6a5-5af718a1eb6f.png)
,4

**Comment by Mm2PL** [comment] 2021-09-28 18:35
Duplicate of #1022. Restarting Chatterino fixes this.

**Closed by Mm2PL** 2021-09-28 18:35 UTC
Labels: issue-report
