### ISSUE TITLE
Add channel points support now that there is an API

### ISSUE THREAD

**Issue by txtsd** [Chatterino/chatterino2#2213] opened 2020-11-21 19:30 UTC
**What should be added?**

The ability to
- Earn periodic channel points like on the website
- Redeem the bonus channel points
- Spend channel points

**Why should it be added?**
Because this has been requested many times and denied in the past, but now there is an API for it: https://blog.twitch.tv/en/2020/11/13/twitch-developer-day-2020-introducing-the-channel-points-api-eventsub-and-more/

**Comment by leon-richardt** [comment] 2020-11-21 19:38
As mentioned in the blog post you linked, the new API enables developers to ...
> - Get Custom Rewards
- Create Custom Reward
- Update Custom Reward
- Delete Custom Reward
- Get Custom Reward Redemptions
- Update Redemption Status

Unfortunately, none of these capabilities allow us to implement the features you suggest.

**Comment by zneix** [comment] 2020-11-21 19:49
Just because it says "Channel points API" it doesn't necessarily mean it gives us what we want. I gotta say twitch just made a big "bait" by "introducing the channel points API".

**Comment by txtsd** [comment] 2020-11-21 20:14
I hoped I was just reading it wrong. Oh well.

**Comment by alazymeme** [comment] 2020-11-22 01:22
Duplicate of https://github.com/Chatterino/chatterino2/issues/1455

**Closed** 2020-11-22 12:01 UTC
Labels: enhancement, needs triage
