### ISSUE TITLE
arabic script is reversed 

### ISSUE THREAD

**Issue by iabo0od** [Chatterino/chatterino2#1655] opened 2020-04-26 18:16 UTC
arabic script is reversed in chatterino

example here is how  "one two three" in twitch chat appears which is correct  https://i.imgur.com/wTSIOO9.png

and here how it shows up in chatterino
https://i.imgur.com/XVhBbS5.png

text " واحد اثنين ثلاثه "

**Comment by cinemassacres** [comment] 2020-04-27 15:39
https://github.com/Chatterino/chatterino2/issues/720

**Comment by apa420** [comment] 2020-04-30 12:39
Duplicate of #720

**Closed by apa420** 2020-04-30 12:39 UTC
Labels: bug, needs triage
