### ISSUE TITLE
Tab completing in emote menu with case sensitive emotes can give wrong emote

### ISSUE THREAD

**Issue by ligos96** [Chatterino/chatterino2#2129] opened 2020-10-25 16:29 UTC
**Describe the bug**
Tab completing in the emote menu when there is multiple emotes with the same name but different casings can autocomplete to the wrong emote.

**To reproduce**
Using MEGALUL and MegaLUL as an example.

1. Type :megal to bring up emote menu
2. Select MEGALUL and press TAB (Note: works as expected if you press ENTER instead)
3. Selected emote is MegaLUL instead of MEGALUL

**Screenshots**
![image](https://user-images.githubusercontent.com/1887350/97112548-28a29e80-16e5-11eb-855e-446da83229e2.png)

**Chatterino version**
Chatterino 2.2.2 (commit 07fc0c3ad)

**Operating system**
Windows 10

**Comment by daiexd** [comment] 2020-10-25 16:33
can replicate on WIndows 10 / Chatterino Nightly 2.2.3-beta (commit 466d85c90, 25.10.2020)

**Comment by dnsge** [comment] 2020-10-25 21:40
duplicate of #1962

**Closed** 2020-11-01 15:01 UTC
Labels: bug, needs triage
