### ISSUE TITLE
Scottish flag emoji becomes a black flag

### ISSUE THREAD

**Issue by jeovanny315** [Chatterino/chatterino2#3257] opened 2021-09-27 00:37 UTC
When trying to send :flag_scotland: it turns into :waving_black_flag:

https://user-images.githubusercontent.com/79304571/134830041-6b0a20ce-7439-4b2e-9d7d-f72ae5306dc5.mp4

Windows 11 Chatterino Nightly 7.3.4

**Comment by Mm2PL** [comment] 2021-09-27 06:40
Not our fault. Duplicate of #916. See https://github.com/twitchdev/issues/issues/307 for more details.

**Closed by Mm2PL** 2021-09-27 06:40 UTC
Labels: issue-report
