### ISSUE TITLE
Claiming of channel point chest in client

### ISSUE THREAD

**Issue by iFrgot** [Chatterino/chatterino2#2476] opened 2021-02-22 00:16 UTC
**What should be added?**
Ability to claim channel point chest in chatterino client.

**Why should it be added?**
Adding this feature would allow me to claim chests without having to go onto twitch directly.

**Comment by alazymeme** [comment] 2021-02-22 06:05
This is not possible due to API limitations. In addition, there have been multiple issues about this that have also been closed. Please search for issues prior to opening one.

**Comment by Mm2PL** [comment] 2021-02-22 08:08
impossible. dupe

**Comment by pajlada** [comment] 2021-02-22 13:27
Duplicate of #1455

**Closed by pajlada** 2021-02-22 13:27 UTC
Labels: enhancement
