### ISSUE TITLE
Match Trigger at end of message not working

### ISSUE THREAD

**Issue by Meeeee6623** [Chatterino/chatterino2#2357] opened 2021-01-12 21:45 UTC
**Describe the bug**

While the box to match command triggers at the end of messages is checked, nothing happens when typing the trigger at the end of the message. 

**To reproduce**

Check the "match trigger at end of message box in the commands tab  in settings. 
Type out a message with a command trigger at the end of it, the command does not trigger. 

**Screenshots**

**Chatterino version**

Chatterino 2.2.3-beta2 (commit 6499b7c12)

**Operating system**

**Additional information**

**Comment by Mm2PL** [comment] 2021-01-12 21:47
No wonder it doesn't work, there are no usages of the setting. Duplicates #2308

**Comment by pajlada** [comment] 2021-01-13 08:35
Duplicate of #2308

**Closed by pajlada** 2021-01-13 08:35 UTC
Labels: bug
