### ISSUE TITLE
User chat logs not found if its clicked from search history window

### ISSUE THREAD

**Issue by sadlyfell** [Chatterino/chatterino2#1440] opened 2019-12-14 19:14 UTC
**Describe the bug**
If we click online logs button(the chat history provided by overrustlelogs or cbenni) from search window not be able to find it, but if we click online logs from normal chatterino windows its working normal. 

Debug message from Qt
```Unable to get logs, no channel name or something specified```

**To reproduce**
1. ctrl + f on channel that support logs by overrustlelogs or cbenni
2. Click user profile and then click Online logs
3. No log's history, only blank window.

**Screenshots**

**Chatterino version**
62cf7cbea

**Operating system**
Windows 7 x64

**Additional information**

**Comment by Felanbird** [comment] 2019-12-17 00:33
Originally you couldn't access the user card function from the search window either, which was fixed in 
47281cf 

I assume this is the same concept/issue.

**Comment by leon-richardt** [comment] 2019-12-17 13:49
The problem is that `LogsPopup::getLogs()` expects a `TwitchChannel`:
https://github.com/Chatterino/chatterino2/blob/11442bba203f1b7d33ce872da1bded934e39ce66/src/widgets/dialogs/LogsPopup.cpp#L52-L62

However, the channel created for the `SearchPopup` is just a regular `Channel`:
https://github.com/Chatterino/chatterino2/blob/11442bba203f1b7d33ce872da1bded934e39ce66/src/widgets/helper/SearchPopup.cpp#L20

Hence, the above cast fails and no logs are fetched. Not sure what the most elegant way to go about this would be.

**Comment by fourtf** [comment] 2020-09-25 22:15
logs were removed

**Closed by fourtf** 2020-09-25 22:15 UTC
Labels: bug
