### ISSUE TITLE
Hebrew and Arabic are reversed 

### ISSUE THREAD

**Issue by Dolev24** [Chatterino/chatterino2#930] opened 2019-01-25 07:02 UTC
for example in english, if i write "Hey how are you" its comes out as "you are how hey"

**Comment by TranRed** [comment] 2019-01-25 23:22
duplicate of #720 NaM

**Comment by RAnders00** [comment] 2019-05-20 18:13
@fourtf close as duplicate please and rename the linked issue to have the title `Hebrew and Arabic are reversed`

**Comment by pajlada** [comment] 2019-05-25 12:29
Duplicate of #720

**Closed by pajlada** 2019-05-25 12:29 UTC
Labels: bug

**Comment by LeopardFMZ** [comment] 2021-06-30 16:38
Came back three years later to see if a fix is possible to this issue of reversed Arabic/Hebrew language  :(

**Comment by killertofus** [comment] 2021-06-30 21:10
@LeopardFMZ #720 also #1970
