### ISSUE TITLE
Location to pick up Twitch points

### ISSUE THREAD

**Issue by adrianovso18** [Chatterino/chatterino2#1625] opened 2020-04-08 20:43 UTC
It would be nice if a function was added in the chatterino to get the channel points of the twitch, as I really like to use the app but only this feature is missing.

**Comment by Mm2PL** [comment] 2020-04-08 20:44
duplicate,
not possible with Twitch's API

**Comment by apa420** [comment] 2020-04-08 21:29
Duplicate of #1455

**Closed by apa420** 2020-04-08 21:29 UTC
Labels: enhancement, needs triage
