### ISSUE TITLE
If chatterino tries to play notification for file that doesn't exist, one thread deadlocks

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1406] opened 2019-11-03 01:11 UTC
**Describe the bug**
If you have notifications for when streamer goes live and you have a sound set that does not exist in set path, chatterino will have a thread that will deadlock and eat all CPU for one core

**To reproduce**
Set up notifications for some streamers, set a custom sound, turn off chatterino, edit the sound path in config file to non-existent one, wait for streamer to go live.

**Chatterino version**
Chatterino Nightly 2.1.5 (commit 556c2aef2, 02.11.2019)

**Operating system**
Win 10 1903 18362.356

**Comment by pajlada** [comment] 2019-11-03 10:41
Not reproducible on Arch Linux

**Comment by Greenlandicsmiley** [comment] 2023-01-28 20:12
I could not reproduce this on a Windows 10 VM with 2.4.0, this seems to no longer be an issue, but in case it still is for you, can you try to reproduce this with the Windows build from PR #4334?

Or if the PR has already been merged by the time you read this, try the nightly build.

**Closed** 2023-01-29 09:36 UTC
Labels: bug, Feature: Highlights
