### ISSUE TITLE
No text, only emotes, emojis and badges appearing

### ISSUE THREAD

**Issue by doggoaltr** [Chatterino/chatterino2#2282] opened 2020-12-15 12:45 UTC
Opened chatterino, and i can't see any text. Only emotes, emojis and badges, on every single chat ![imagem_2020-12-15_094311](https://user-images.githubusercontent.com/69827295/102216468-f0843480-3eb9-11eb-92ae-abbb0f8ef1dc.png)

**Comment by leon-richardt** [comment] 2020-12-15 12:50
Looks like a font problem. Unfortunately, with the little information you provide, it is hard to give any further advice. Please use the ["Bug Report" issue template](https://github.com/Chatterino/chatterino2/issues/new?assignees=&labels=bug&template=bug_report.md&title=) in order for us to be able to assist you better

**Comment by apa420** [comment] 2020-12-16 10:07
duplicate of #2283
Why did you post the same issue twice?

**Closed by apa420** 2020-12-16 10:07 UTC
