### ISSUE TITLE
Delete Message Button does not show for own messages in mod view

### ISSUE THREAD

**Issue by MatthewMiles0** [Chatterino/chatterino2#4845] opened 2023-09-28 22:52 UTC
### Describe your issue

In reference to setting up Moderation Buttons:

Whilst it makes sense that timing out and banning other moderator's messages via mod buttons wouldn't make sense since twitch blocks the action, you are still able to delete your own messages, which is sometimes useful when a mod wants to send a reminder in chat but not have the chat remain flooded with messages when it moves slowly as well as other scenarios. You should still be able to use mod buttons linking to the `/delete` command when on your own message.

The current workaround is to shift right click each message -> copy id -> type "/delete [message id]"

### OS and Chatterino Version

Chatterino 2.4.5 (commit 05a72d33) built with Qt 5.15.2, MSVC 193532217 Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by Felanbird** [comment] 2023-09-28 23:10
> The current workaround is to shift right click each message -> copy id -> type "/delete [message id]"

A better workaround would be to make a normal command and execute it with the right-click-to-execute-commands feature

![image](https://github.com/Chatterino/chatterino2/assets/41973452/4513f7de-32ec-4c61-a5a2-9ce7d0a125e8)
![chatterino_2023-09-28_19-09-14](https://github.com/Chatterino/chatterino2/assets/41973452/709ee6be-e066-429f-9c37-653beb066975)

**Comment by MatthewMiles0** [comment] 2023-09-29 00:39
Thanks! This is a little better but it'd still be nice to have a button rather than second layer right click menu options

**Comment by Felanbird** [comment] 2023-09-29 07:50
Duplicate of #3752

**Closed by Felanbird** 2023-09-29 07:50 UTC
Labels: issue-report
