### ISSUE TITLE
Crash if recent messages endpoint returns 1000 messages

### ISSUE THREAD

**Issue by RAnders00** [Chatterino/chatterino2#1421] opened 2019-11-20 10:55 UTC
**Describe the bug**
Chatterino crashes on startup if the recent messages API returns 1000 messages.

**To reproduce**
- set environment variable: `CHATTERINO2_RECENT_MESSAGES_URL=https://shitty-customapis-si5z3vz69j2s.runkit.sh/recent-messages-test-1k/%1`
- start c2

**Screenshots**
n/a

**Chatterino version**
`Chatterino Nightly 2.1.5 (commit d200f12f4, 27.09.2019)`

**Operating system**
Windows 10

**Additional information**

**Comment by Mm2PL** [comment] 2021-06-24 11:53
Still can reproduce on 97b9bfb2

**Comment by Felanbird** [comment] 2022-06-15 01:38
Due to the implementation of Twitch Announcements, this issue is more prevalent, as Announcements are rendered as 2 separate messages, so when loading historical message if more than 99 announcements are in said history, more than 1000 messages are technically loaded and Chatterino crashes.

See #3820

**Comment by pajlada** [comment] 2022-06-18 10:32
https://github.com/Chatterino/chatterino2/pull/3798 is being merged in now, once that's merged in this *should* be fixed

**Closed** 2022-06-18 10:44 UTC
Labels: bug, crash, backlog

**Comment by Felanbird** [comment] 2022-06-18 17:36
Looks to be fixed 👍 
![image](https://user-images.githubusercontent.com/41973452/174450131-730868be-91b4-4e71-9ebc-f907e2323afe.png)
