### ISSUE TITLE
Chat macro buttons

### ISSUE THREAD

**Issue by wormosteeze** [Chatterino/chatterino2#2261] opened 2020-12-07 00:06 UTC
**What should be added?**
I would love a macro buttons for some of my frequently used chat commands.

**Why should it be added?**
It would be nice to be able to just click a few of my commands without having to type them in every time.

**Comment by apa420** [comment] 2020-12-07 12:47
Duplicate of #1592

**Comment by apa420** [comment] 2020-12-07 12:48
I guess it's not covered by the issue. So I'll leave this open.

**Comment by Mm2PL** [comment] 2020-12-07 14:23
Are you thinking of adding buttons kinda like this, where each one would execute a command?
![supiniFrontend Clap](https://user-images.githubusercontent.com/25011746/101362121-9bcc3280-3897-11eb-83b9-24bba63307c1.png)

**Comment by wormosteeze** [comment] 2020-12-07 17:32
Yes, or similarly to how Streamlabs Chatbot has a set number of available macros that you can rename as seen here - the purple buttons.
https://livedoor.blogimg.jp/matanki153/imgs/2/4/2488142e-s.png

**Comment by pajlada** [comment] 2024-04-06 09:49
I think this can be achieved in two ways now

1) With hotkeys
![image](https://github.com/Chatterino/chatterino2/assets/962989/5bfafdd7-4c63-4a84-b177-5e23e8dca0e0)

2) With command's "Show In Message Menu" option
![image](https://github.com/Chatterino/chatterino2/assets/962989/b34f52d3-2700-4c54-8b06-368a10ce5f1d)
![image](https://github.com/Chatterino/chatterino2/assets/962989/0445d35a-75d7-4122-a211-62dc42d8a05c)

**Closed by pajlada** 2024-04-06 09:49 UTC
Labels: enhancement
