### ISSUE TITLE
Zero-width emotes show up below animated emotes

### ISSUE THREAD

**Issue by clxxiii** [Chatterino/chatterino2#3256] opened 2021-09-26 17:17 UTC
**Describe your issue**

Zero-width emotes show up below animated emotes but works fine for static emotes

**Screenshots**

![Problem Screenshot](https://user-images.githubusercontent.com/46410314/134815685-c68c8421-9b05-46da-9c32-55acf4a68ba0.png)

**OS and Chatterino Version**

Windows 10, Chatterino v2.3.4 (v7.3.4 fork)

**Comment by Mm2PL** [comment] 2021-09-26 17:22
Duplicate of #2994

**Closed by Mm2PL** 2021-09-26 17:22 UTC
Labels: issue-report
