### ISSUE TITLE
Bit emotes and GIF emotes rendered multiple times in the emote menu

### ISSUE THREAD

**Issue by sunkhaskasis** [Chatterino/chatterino2#3007] opened 2021-07-14 10:11 UTC
[Windows 10, 2.3.3 Release]

Today I updated to the newest 2.3.3 and noticed that in the emote menu emotes that I've unlocked with bits, as well as GIF emotes, are repeated multiple times. API-related bug, perhaps? Here's the screenshot:
![image](https://user-images.githubusercontent.com/19194315/125604939-0a386c32-2211-4527-8dac-e794cf861143.png)

**Comment by zneix** [comment] 2021-07-14 10:26
This is known and caused by the same issue that causes #2935. I can confirm that this is fixed in #2992, but I'll leave this open until my PR is merged in.

**Closed** 2021-07-17 15:18 UTC
Labels: bug
