### ISSUE TITLE
Chatterino has a compilation time issue on Windows CI

### ISSUE THREAD

**Issue by Mm2PL** [Chatterino/chatterino2#4623] opened 2023-05-11 12:32 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Chatterino takes 15 to 30 minutes !! depending on the compiler on CI. This is not acceptable.

### Screenshots

From https://github.com/Chatterino/chatterino2/pull/4622 :
![image](https://github.com/Chatterino/chatterino2/assets/25011746/3292e27b-5d62-4491-a72f-0ea58f34eefe)

### OS and Chatterino Version

https://github.com/Chatterino/Chatterino2/commit/1f0aa80

**Comment by Felanbird** [comment] 2023-05-11 15:25
The ubuntu/mac ones are ok, the windows one is the truly unreasonable one

Fix was attempted in https://github.com/Chatterino/chatterino2/pull/4606 by axing LTO but it did not resolve the super slow windows build.

**Comment by fourtf** [comment] 2023-05-11 15:27
Clangs --ftime-trace is useful for figuring out ways to reduce compile time

**Comment by pajlada** [comment] 2023-05-11 16:03
Duplicate of #3452 (your own issue)

**Closed by pajlada** 2023-05-11 16:03 UTC
Labels: bug, ci

**Comment by Mm2PL** [comment] 2023-05-11 16:11
same on complaint xd
