### ISSUE TITLE
Cannot @ people

### ISSUE THREAD

**Issue by Oscillate1** [Chatterino/chatterino2#1742] opened 2020-06-15 20:21 UTC
Cannot @ usernames - Just started today, it may be an issue with Twitch, but in default Twitch chat, I can @ usernames fine.

**To reproduce**
Does it every time I log in, even if I remove my account, reload Chatterino, log back in, reload again, etc.  Nothing helps.

**Chatterino version**
<2.1.7>

**Operating system**
<Windows 10>

**Comment by Mm2PL** [comment] 2020-06-15 20:22
Not a Chatterino issue, this is a Twitch problem.

**Comment by pajlada** [comment] 2020-06-16 07:23
As Mm2PL confirmed, this is not a Chatterino issue. Leaving open while this is still an issue to deter more issues being created.

**Comment by Mm2PL** [comment] 2020-06-16 11:42
Issue seems to be fixed on Twitch's end. I think we can close this now.
@pajlada 🙂

**Closed** 2020-06-16 12:05 UTC
Labels: twitch
