### ISSUE TITLE
Any way to fix this issue? (The extension could not connect to chatterino)

### ISSUE THREAD

**Issue by Qewar** [Chatterino/chatterino2#1104] opened 2019-06-21 12:13 UTC
I've seen it posted multiple times but never found a solution, I've had this months ago before unninstalling and still have it now, any way to fix this?

![image](https://user-images.githubusercontent.com/50082459/59921577-15632d00-9426-11e9-9b95-3884f7adcc38.png)

**Comment by SLCH** [comment] 2019-06-21 13:17
Yea, this fixed it for me:
<details>
<summary>
The fix
</summary>
![123123123123123123123123](https://user-images.githubusercontent.com/2884941/59925096-62f09180-9448-11e9-9910-e12255482b67.jpg)
4HEad
</details>

**Comment by pajlada** [comment] 2019-06-21 20:00
Known issue unfortunately, duplicate of #745

**Closed by pajlada** 2019-06-21 20:00 UTC
