### ISSUE TITLE
Some emotes are not showing up correctly

### ISSUE THREAD

**Issue by ghost** [Chatterino/chatterino2#877] opened 2018-11-15 14:56 UTC
Some emotes are not showing up correctly, the default skin is present instead of the custom one.
We have a custom FeelsBadMan, FeelsGoodMan and monkaS from FFZ added to the channel (sodapoppin) and it shows the default FeelsBadMan, FeelsGoodMan and monkaS.
I would understand the issue with FeelsBadMan and FeelsGoodMan cause they are global BTTV emotes, but monkaS is not global and there is no other monkaS added on BTTV to the channel, just the one we have on FFZ.

Thank you

ps.: I can see the custom emotes using the normal twitch chat (with FFZ and FFZ:AP or FFZ and BTTV installed), but cannot see them in chatterino.

**Comment by fourtf** [comment] 2018-11-15 15:13
Are you seeing the bttv emotes by chance?

**Comment by VulpesHD** [comment] 2018-11-15 18:30
Yes and no, like monkaS is not added, nor a global BTTV emote, it is only added as a custom FFZ emote, but the default monkaS is showing.
I see the default FeelsBadMan and FeelsGoodMan instead of the custom FFZ emote that is added to the channel. 
(Using the latest beta build as of right now)

**Comment by gapbl4** [comment] 2018-11-16 03:35
![](https://i.imgur.com/WyTu7Yo.png)

here's your monkas not being added as bttv emote

**Comment by VulpesHD** [comment] 2018-11-16 03:40
I did not even see that, I went through the list like 3 times. Thank you. Then that part of the problem is solved.
The only other thing would be overwriting global emotes with the same name if there is a custom emote added to FFZ.

**Comment by gapbl4** [comment] 2018-11-16 09:50
to make it work ffz emotes should be parsed first then, because bttv doesn't allow using names of the default emotes for custom emotes anyway

**Comment by TETYYS** [comment] 2018-11-16 17:02
Is FFZ overwriting BTTV emotes documented behavior? If it's undefined, I don't think this should be "fixed"

**Comment by hemirt** [comment] 2018-11-17 19:50
the order is undocumented, but specified  [here](https://github.com/fourtf/chatterino2/blob/master/src/providers/twitch/TwitchMessageBuilder.cpp#L1013-L1028) and it goes global bttv -> chbttv -> globalffz -> chffz

My opinion is that the order be chffz -> chbttv -> globalffz -> globalbttv
cause i think ffz is better than bttv, and bttv should mostly be used only for gif emotes and in that case you ought to not have any other emote with the same name

**Comment by VulpesHD** [comment] 2018-11-17 20:08
I was also looking for the documentation, but could not find it anywhere.
"chffz -> chbttv -> globalffz -> globalbttv" This change would be a +1 from me.

**Comment by TETYYS** [comment] 2018-11-17 20:10
How does it behave in the web chat? Who overwrites who with default BTTV+FFZ?

**Comment by notheowner** [comment] 2018-11-17 20:15
You really can't set a "default order".
Some people use Chatterino, others use FFZ+ FFZ:AP, others use BTTV + FFZ, others use Chatty etc etc.
Unless there is a standard on how it should be ordered, it can differ from person to another.

**Comment by hemirt** [comment] 2018-11-17 20:16
thats why I propose the order and the reasoning for it, that is in my earlier comment 👌

**Comment by VulpesHD** [comment] 2018-11-17 20:18
I have BTTV and FFZ installed without the (FFZ without the addon pack) and the FFZ channel emotes overwrite the global BTTV emotes.

**Comment by TETYYS** [comment] 2018-11-17 20:20
Shouldn't the original combination of addons (which is probably also most used by most people) dictate what overwrites what? I don't think that just because one addon is better than other it should be the one overwriting other.

**Comment by pajlada** [comment] 2019-05-25 08:59
Fixed in #1080

**Closed by pajlada** 2019-05-25 08:59 UTC
Labels: bug
