### ISSUE TITLE
Update the emoji packs

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1553] opened 2020-02-15 15:34 UTC
Seems like there's been quite a few additions to the emojis. I would like to see them updated and natively working in chatterino :)

![image](https://user-images.githubusercontent.com/12804673/74590711-777b3d00-505c-11ea-8656-3bcdf24f876d.png)

**Comment by pajlada** [comment] 2020-02-16 10:04
Duplicate of #869

**Closed by pajlada** 2020-02-16 10:04 UTC
Labels: enhancement, needs triage
