### ISSUE TITLE
Ping sound

### ISSUE THREAD

**Issue by MohamedRass** [Chatterino/chatterino2#3704] opened 2022-05-01 14:56 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Chatterino bug/problem - 
1- When someone has tagged you in a chat the ping sound don't work and sometimes it is delayed

Fix i've tried - 
- Ive reinstalled chatterino by going into the chatterino file and doing unistall and also deleted the temp file in the appdata, and i got another issue of " Message history service unavailable (Error 502) ", i also have the latest version of Chatterino,"Chatterino Nghtly 7.3.5"

### Screenshots

Message History Error-
https://i.imgur.com/kfKHWl4.png

Chatterino Nightly 7.3.5 - 
https://i.imgur.com/lZyEcXo.png

Highlights Setting - 
https://i.imgur.com/Uesq3Wc.png

### OS and Chatterino Version

Microsoft Windows

**Comment by Felanbird** [comment] 2022-05-01 15:14
>and i got another issue of " Message history service unavailable (Error 502)

Message history is getting updated, unrelated issue.

>When someone has tagged you in a chat the ping sound don't work

https://github.com/Chatterino/chatterino2/issues/1228#issuecomment-893043374

> and sometimes it is delayed

That's just lag from my experience.

**Comment by jammehcow** [comment] 2022-05-02 01:05
> > and sometimes it is delayed
> 
> That's just lag from my experience.

Could also be caused by #3560. I believe this issue can be closed in favour of that and #1228

**Comment by Mm2PL** [comment] 2022-08-12 21:47
Closing as stale, there was no recent confirmations of this behavior. Please open a new issue if the problem is still around.

**Closed by Mm2PL** 2022-08-12 21:47 UTC
Labels: issue-report
