### ISSUE TITLE
Chatterino crashes when i open a new brower tab.

### ISSUE THREAD

**Issue by hotbear1110** [Chatterino/chatterino2#2359] opened 2021-01-14 11:50 UTC
90% of the time i open a new brower tab in firefox, chatterino 2.2.3-beta2 crashes. It only happens in firefox and when i have the browser extension enabled.

**Comment by leon-richardt** [comment] 2021-01-14 12:01
Use the [issue template](https://github.com/Chatterino/chatterino2/issues/new?assignees=&labels=bug&template=bug_report.md&title=)

**Comment by zneix** [comment] 2021-01-14 12:30
Pretty sure this is a duplicate of Chatterino/chatterino-browser-ext#48 and I think there was a similar issue opened in this repository as well. Either way, issues related to Chatterino browser extension issues should be tracked in [it's issue tracker](https://github.com/chatterno/chatterino-browser-ext/issues).

**Closed** 2021-01-16 23:02 UTC
