### ISSUE TITLE
Chatterino cannot find streamlink path

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#1976] opened 2020-09-20 10:55 UTC
**Describe the bug**
Chatterino throws an error when the quality is set to `Choose`:
```Unable to find Streamlink executable Make sure your custom path is pointing to the DIRECTORY where the streamlink executable is located```

**To reproduce**
1. Set custom streamlink path (I have mine set to `"C:\Program Files (x86)\Streamlink\bin"`)
2. Set quality to `Choose`
3. Try to launch a stream
4. Set to `Source`
5. Notice that it works

**Screenshots**
![image](https://user-images.githubusercontent.com/12804673/93709686-9d813680-fb83-11ea-9d5b-320ee41fd444.png)

**Chatterino version**
Chatterino Nightly 2.2.2 (commit 913193f8b, 19.09.2020)

**Operating system**
Windows 10

**Additional Information**
Uncheck the custom installation option and it starts working all of a sudden?

**Comment by flex3r** [comment] 2020-09-20 10:57
I have the exact same issue, Chatterino Nightly 2.2.2 (commit 0814fca7d)

**Comment by oldLucke** [comment] 2020-09-24 11:54
Works fine for me on Chatterino 2.2.2 (commit 07fc0c3ad) and streamlink 1.5.0

**Comment by oldLucke** [comment] 2020-09-24 12:00
@alazymeme what version of streamlink are you running?

**Comment by alazymeme** [comment] 2020-09-24 12:29
> @alazymeme what version of streamlink are you running?

1.6.0

**Comment by alazymeme** [comment] 2020-09-24 12:31
I'd like to now add to this issue:

Since updating to 1.6.0, turning off `Use Custom Path` isn't an option. It won't work no matter what is selected under preferred quality.

Setting the custom path works, but only when the quality is not set to `Choose`

**Comment by alazymeme** [comment] 2020-09-24 12:40
Chatterino 2.2.2 (commit 9a73ceaca)
Running chatterino in debug mode shows that streamlink will work when `Use Custom Path` is disabled, but when it's enabled, it won't work at all.

**Comment by jprochazk** [comment] 2020-10-28 09:45
I have the same issue. Streamlink works by itself. Windows 10, Streamlink 1.7.0 (latest stable), Chatterino .2.2 (commit 07fc0c3ad).

**Comment by Brog33** [comment] 2021-08-08 11:04
I have the same issue in Linux where Chatterino is installed from Flathub. PATH to streamlink is set globally, and even though I override it with the full path to the executable, it doesn't work - it's like in OP's screenshot. Streamlink v2.3.0

**Comment by zneix** [comment] 2021-08-08 15:21
I'm pretty sure that with Flatpak version of Chatterino there's something different going on, most likely unrelated to the issue present on Windows. @ilyazzz explained that a couple times to me but I've forgotten what was the deal exactly.

**Comment by apa420** [comment] 2021-08-18 10:05
You need to remove the "" when setting the streamlink path.
For me:
`C:/Program Files (x86)/Streamlink/bin` works
`"C:/Program Files (x86)/Streamlink/bin"` doesn't work

**Comment by ilyazzz** [comment] 2021-08-20 20:17
@Brog33 the Flatpak issue is resolved with #3178 , the update is already on Flathub.

**Comment by apa420** [comment] 2021-08-20 21:31
@flex3r @jprochazk do you still have this issue after updating and removing "" from the path?

**Comment by flex3r** [comment] 2021-08-20 21:40
Just tested again and I got the same results as @apa420 now. In addition, chatterino also finds streamlink in the default path without setting a custom path.

**Comment by apa420** [comment] 2021-08-20 22:05
I will then assume the issue is resolved for now.
So I will close it.

If the issue persists I'll reopen the issue.

**Closed by apa420** 2021-08-20 22:05 UTC
Labels: bug
