### ISSUE TITLE
Option to stop message history from being greyed out

### ISSUE THREAD

**Issue by Velegand** [Chatterino/chatterino2#2811] opened 2021-05-23 12:03 UTC
I would like an option to disable message history from being greyed out as I don't see a big reason why it should be greyed out.
I specifically want to screenshot a message but it is greyed out due to a chatterino restart.

**Comment by Velegand** [comment] 2021-05-23 12:04
idk how to add the enhancement tag sry

**Comment by talneoran** [comment] 2021-05-23 12:07
Duplicate of #2690

**Comment by pajlada** [comment] 2021-05-23 12:51
Duplicate of #2690

**Closed by pajlada** 2021-05-23 12:51 UTC
Labels: issue-report
