### ISSUE TITLE
The ability to be able to tab bit emotes

### ISSUE THREAD

**Issue by daiexd** [Chatterino/chatterino2#2183] opened 2020-11-13 19:54 UTC
**What should be added?**
An addition should be added that allows for you to tab bit emotes, I don't understand why this is not a feature in chatterino, as tabbing emotes is very helpful.

**Why should it be added?**
So that you do not have to type out bit emote names, and worry about capitalization when you can just tab the emote instead. This is already an addition on the basic web chat, so I thought it would be already implemented into chatterino. I'm not sure if this is just not available for chatterino, because I guess someone would have already suggested this addition.

**Comment by Felanbird** [comment] 2020-11-13 21:57
Duplicate of #1450 which is blocked as stated, there's no api for bit emotes.

**Closed** 2020-11-14 01:44 UTC
Labels: enhancement, needs triage
