### ISSUE TITLE
Personal BTTV Emotes do not show on Chatterino

### ISSUE THREAD

**Issue by unclebeanbag7** [Chatterino/chatterino2#1808] opened 2020-07-14 06:55 UTC
I rarely use Vanilla chat and the Personal Emotes feature for me is basically useless. 

**Screenshots**
Here is a comparison of what it looks like in vanilla and chatterino.
![image](https://user-images.githubusercontent.com/68268492/87394115-e52c8600-c574-11ea-8a3a-588dba02b3da.png)

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10

**Comment by zneix** [comment] 2020-07-14 09:23
Duplicate of #12

**Comment by Mm2PL** [comment] 2020-07-14 10:16
Not a bug, this is an unimplemented feature.

**Comment by apa420** [comment] 2020-07-14 11:25
Duplicate of #12

**Closed by apa420** 2020-07-14 11:25 UTC
Labels: bug, needs triage
