### ISSUE TITLE
Chatterino doesn't work for Opera GX

### ISSUE THREAD

**Issue by luca-live** [Chatterino/chatterino2#2186] opened 2020-11-15 19:09 UTC
**Describe the bug**
Chatterino doesn't work in Opera GX. Already installed the extension correctly. 

**Chatterino version**
Chatterino 2.2.3-beta (commit 3c6e6446c) 

**Operating system**
Windows 10 

**Additional information**

**Comment by alazymeme** [comment] 2020-11-15 21:11
Duplicate of https://github.com/Chatterino/chatterino-browser-ext/issues/43

Please use the issue templates before posting issues.

**Closed** 2020-11-16 12:00 UTC
Labels: bug, needs triage
