### ISSUE TITLE
Chatterino gives you an "Exception thrown: read access violation." if you right click the icon of something like the "AutoMod Queue message"

### ISSUE THREAD

**Issue by karl-police** [Chatterino/chatterino2#3495] opened 2022-01-12 23:13 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

![image](https://user-images.githubusercontent.com/12023782/149237772-1d41cb1f-d75f-4d00-ae9b-aa7a40950f48.png)
Right clicking that icon crashes Chatterino, at least it does that in the Debug one.

### OS and Chatterino Version

Chatterino 2.3.4 on Windows 10

**Comment by zneix** [comment] 2022-01-12 23:39
Duplicate of #2969

**Closed by zneix** 2022-01-12 23:39 UTC
Labels: issue-report
