### ISSUE TITLE
Feature request: Show game or title in live notifications

### ISSUE THREAD

**Issue by xHeaveny** [Chatterino/chatterino2#3196] opened 2021-08-24 12:04 UTC
Show the title/ game in the live notifications 

Thans in the moment the notification 
![image](https://user-images.githubusercontent.com/69117321/130612602-5a5108ec-336f-4bd0-97a2-c5f09ca0073c.png)

After that I should look like that 
![Screenshot 2021-08-24 135958](https://user-images.githubusercontent.com/69117321/130613255-a7965488-13c8-499a-8b01-2c9364823af4.png)

**Comment by ALazyMeme** [comment] 2021-08-24 12:23
Duplicate of https://github.com/Chatterino/chatterino2/issues/1297
But closing https://github.com/Chatterino/chatterino2/issues/1297 in favour of this issue

**Comment by apa420** [comment] 2021-08-24 12:24
Post enhancements in discussions just as the issue templates suggest
![](https://i.nuuls.com/KaKU-.png)

**Closed by apa420** 2021-08-24 12:24 UTC
Labels: enhancement, windows
