### ISSUE TITLE
Usercard popup from clicking a mention

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1578] opened 2020-02-29 12:23 UTC
Not sure if this is a dupe issue (could've sworn I've seen it before), but ffz has a neat feature where you are able to click @mentions in chat and it will highlight all their messages currently in chat and will show their usercard. Would like to see something similar in ch2. I think this along with the integrated logs in the usercard would make for an extremely useful feature.

![image](https://user-images.githubusercontent.com/12804673/75607365-15353880-5b42-11ea-984f-e8fd7ca1501f.png)

**Comment by leon-richardt** [comment] 2020-02-29 20:37
The highlighting part has been requested in #228. 😄

**Comment by alazymeme** [comment] 2020-02-29 21:46
Maybe the issues can be merged or something, fourtf can figure something out

**Comment by apa420** [comment] 2020-03-10 20:53
Duplicate of #228

**Closed by apa420** 2020-03-10 20:53 UTC
Labels: enhancement, needs triage
