### ISSUE TITLE
"Usercard" button not linking correctly

### ISSUE THREAD

**Issue by MomsSpag** [Chatterino/chatterino2#2532] opened 2021-03-15 22:53 UTC
![image](https://user-images.githubusercontent.com/23405694/111231373-0dc3be80-85e1-11eb-8110-bb75adf046a8.png)

![image](https://user-images.githubusercontent.com/23405694/111231398-187e5380-85e1-11eb-882c-e4e75e5d86a9.png)

The button for "usercard" when pressing on someones username doesn't correctly link to the user card for the channel, just for the mentions for some reason. I'm pressing on the user via the chat itself, not mentions. 

Version: Chatterino 2.2.2-fix (commit a82f57f94)

**Comment by Mm2PL** [comment] 2021-03-15 23:19
Kind of duplicates #2248, essentially same premise, just different "channels".

**Comment by pajlada** [comment] 2021-03-16 00:16
Duplicate of #2248

**Closed by pajlada** 2021-03-16 00:16 UTC
Labels: bug
