### ISSUE TITLE
In the settings Chatterino crashes when pressing any button that says "Remove"

### ISSUE THREAD

**Issue by Intrets** [Chatterino/chatterino2#1958] opened 2020-09-11 17:13 UTC
**Describe the bug**
In the settings, Chatterino crashes when removing accounts, commands, highlighted messages, highlighted users, blacklisted users, ignores, moderation buttons and channels selected for live notifications. Every button I can find that says "remove".

**To reproduce**
Settings -> Commands -> Add -> Select the command -> Click Remove -> Chatterino 100% crashes

**Chatterino version**
Chatterino 2.2.2 (commit 07fc0c3ad), also experienced this bug on 2.2.1

**Operating system**
Windows 10 Home
10.0.19041 Build 19041

**Additional information**
I have removed %appdata%/chatterino2 before reinstalling chatterino2 and bug still occurs.
I understand this report is mostly useless, is there a way to get error logging or something? Only thing I could find was chat messages logging.

**Comment by leon-richardt** [comment] 2020-09-11 17:15
Duplicate of https://github.com/Chatterino/chatterino2/issues/1529, I suppose.

**Comment by apa420** [comment] 2020-09-11 17:18
Duplicate of #1529

**Closed by apa420** 2020-09-11 17:18 UTC
Labels: bug, needs triage
