### ISSUE TITLE
When someone uses channel points to request a reward no text appears in chat, like in Twitch chat.

### ISSUE THREAD

**Issue by keirakatana** [Chatterino/chatterino2#1850] opened 2020-08-11 09:26 UTC
**Describe the bug**
So this is purely missing text, not the feature I am reporting. So someone uses Twitch channel points to request me to do something like eg 'Hydrate". In Twitch chat client the text appears in the chat telling me to do the request reward. In Chatterino nothing pops up in chat. 

**To reproduce**
-User requests reward through their Twitch interface
-I don't see request in chat through Chatterino

![image](https://user-images.githubusercontent.com/69507917/89881594-9d257100-dbbd-11ea-9a91-e0ec7926e3c6.png)

**Chatterino version**
Chatterino 2.1.7 (commit 845c8fa63)

**Operating system**
Windows 10 pro

**Comment by Mm2PL** [comment] 2020-08-11 09:35
Not a bug, missing feature. This is being worked on iirc, maybe it has been merged already. Please check the latest nightly release. The latest stable release(2.1.7) is quite outdated.

**Comment by zneix** [comment] 2020-08-11 09:35
This functionality was recently added in nightly when [this pr](https://github.com/Chatterino/chatterino2/pull/1809) got merged, you should try it first.

**Comment by d4nl** [comment] 2020-08-11 20:05
Perhaps related to this. Seeing the below messages:

Invalid point event type: redemption-status-update
Invalid point event type: custom-reward-updated

These appear to be coming from row 1141 in src/providers/twitch/PubsubClient.cpp with build Chatterino 2.1.7 (commit 36dd640cd)

The resulting chat log messages are empty except for the timestamp

**Comment by keirakatana** [comment] 2020-08-12 14:02
> Not a bug, missing feature. ~This is being worked on iirc, maybe~ it has been merged already. Please check the latest nightly release. The latest stable release(2.1.7) which you are running is quite outdated.

Hi, thank you for responding so quick. 

![image](https://user-images.githubusercontent.com/69507917/90024424-c07b1980-dcac-11ea-9406-bc71f5c45120.png)

It works on the nightly build. Keep doing an awesome job!

**Comment by Cranken** [comment] 2020-08-12 20:31
> Perhaps related to this. Seeing the below messages:
> 
> Invalid point event type: redemption-status-update
> Invalid point event type: custom-reward-updated
> 
> These appear to be coming from row 1141 in src/providers/twitch/PubsubClient.cpp with build Chatterino 2.1.7 (commit [36dd640](https://github.com/Chatterino/chatterino2/commit/36dd640cd9da45aa8a9acdc75273c375159eca6b))
> 
> The resulting chat log messages are empty except for the timestamp

Just fyi:
These events are currently not processed because they do not contain the actual reward data.
These events instead update the cost and text for existing rewards if they are changed by the streamer.
Currently if there was a reward redeemed the text and cost of the reward will stay the same while the channel is open in chatterino without ever updating.
Updating existing rewards based on these events is something I'll probably work on in the near future.

**Comment by fourtf** [comment] 2020-09-25 18:44
this is fixed in the latest version

**Closed by fourtf** 2020-09-25 18:44 UTC
Labels: bug, needs triage
