### ISSUE TITLE
Crash on lock with special button

### ISSUE THREAD

**Issue by savabozo** [Chatterino/chatterino2#937] opened 2019-01-31 10:03 UTC
Windows lock screen => crash.
Only when i use special button to lock it. Win+L combo doesnt trigger it.
**Upd** Win+L does crash after some time too.
**Upd2** Now it doesnt crash. inconsistent bug 
![img_20190131_135619](https://user-images.githubusercontent.com/47025788/52046732-ddd01300-2560-11e9-8171-3a055976c19a.jpg)

Latest nightly build

> nightly v1.0.876 built 2019-01-31T07:32:25.0000000Z
Last change: Merge pull request #933 from hemirt/master
Historic messages behaviour

**Comment by gapbl4** [comment] 2019-01-31 12:17
Just use Win+L then ![4head](https://user-images.githubusercontent.com/14076068/52053740-42906b00-256b-11e9-8eea-89fa217f4291.png)

**Comment by alazymeme** [comment] 2020-05-28 10:18
I can't reproduce this. Do you still have this issue in the latest nightly? https://github.com/Chatterino/chatterino2/releases/tag/nightly-build

**Comment by Mm2PL** [comment] 2020-05-28 10:20
> Upd2: Now it doesnt crash. inconsistent bug

probably needs closing as unable to reproduce

**Comment by alazymeme** [comment] 2020-09-15 09:40
@fourtf @pajlada pls close

**Comment by fourtf** [comment] 2020-09-25 19:42
not reproducible

**Comment by Mm2PL** [comment] 2023-11-24 15:32
we have crash reporting now

**Comment by pajlada** [comment] 2024-03-02 13:38
@savabozo If you're able to reproduce this with the latest version, please re-open this issue with the crashdump.

Crashdumps are saved inside the Crashes/reports folder in your [Chatterino folder](https://wiki.chatterino.com/Settings/#where-is-my-chatterino-folder-located).

**Closed by pajlada** 2024-03-02 13:38 UTC
Labels: bug, crash, OS: Windows
