### ISSUE TITLE
Different volume levels of pings for when chatterino is focused/unfocused

### ISSUE THREAD

**Issue by crissmoovee** [Chatterino/chatterino2#1934] opened 2020-09-02 10:41 UTC
a feature that allows the user to set the volume of pings when focused to be higher or lower.

for me atleast when chatterino is focused i can miss pings when its on other cannels because i have them off due to the high volume i like them to be at when its unfocused. i would like there to be a setting that allows me to reduce the volume of pings so that i can barely hear it but still makes me look at the mentions tab. i would like this also because i dont really look at the tabs unless im going to change channels therefore i can miss the red highlight on the tab itself.

**Comment by cinemassacres** [comment] 2020-09-02 17:08
Duplicate of #1436

**Comment by leon-richardt** [comment] 2020-09-02 17:12
> Duplicate of #1436

Not a real duplicate in my opinion. This issue asks for different volumes levels depending on focus.

**Comment by fourtf** [comment] 2020-09-26 01:00
This issue does not provide enough useful features. As such there is a likely chance of this never being implemented. I will close this so it doesn't become a stale issue that never gets closed.

**Closed by fourtf** 2020-09-26 01:00 UTC
Labels: enhancement, needs triage
