### ISSUE TITLE
Chatterino keeps crashing right after starting

### ISSUE THREAD

**Issue by MESSIOS** [Chatterino/chatterino2#2229] opened 2020-11-26 23:32 UTC
**Describe the bug**
Chatterino keeps crashing right after starting

**To reproduce**
Start chatterino

**Screenshots**

**Chatterino version**
Chatterino 2.2.3-beta
Chatterino 2.2.3-Nightly beta3
Chatterino 2.2.2-fix
Chatterino 2.2.1

**Operating system**
Windows 10 Home. Version 2004

**Additional information**
I installed and Reinstalled Chatterino multiple times in different version. It keeps crashing after some time (sometimes it workes for a month before crashing sometimes it crashes right after the first start. As soon as it crahed once it wont work again unless i reinstall it. I had the Microsoft Visual C++ rep 2015/2019 already installed

**Comment by alazymeme** [comment] 2020-11-27 05:01
Cannot reproduce on either Linux nor Windows 10, 05aab868455500ede7cc1d3d3f9a2006392d5f12

**Comment by leon-richardt** [comment] 2020-11-28 10:05
There also have been multiple reports of similar issues on the Chatterino Discord over the last few days. Obviously, we can't tell from these reports whether they are all related to the same underlying problem but I feel like an uptick in reports is definitely noticeable.

![image](https://user-images.githubusercontent.com/35232120/100499286-90c32500-3168-11eb-9bbd-fe8ab187e3f8.png)
![image](https://user-images.githubusercontent.com/35232120/100499297-acc6c680-3168-11eb-9419-427c9cb40f4d.png)
![image](https://user-images.githubusercontent.com/35232120/100499330-fd3e2400-3168-11eb-88b6-5bb30c26fa9e.png)

**Comment by bobotheklown** [comment] 2020-11-30 22:32
Also experiencing instant crash on startup. Version: Chatterino 2.2.2-fix

Is there a dump log somewhere that may give more details?

**Comment by Borinius** [comment] 2020-12-08 13:57
Am also having this, getting the same error as above. version 2.2.2-fix and also a newer version a while back that i downloaded to test if that would fix it dont rmber which one tho. The crash for me is not only on startup, its random it seems, can go an hour or 1 day.

**Comment by leon-richardt** [comment] 2020-12-08 14:40
> Am also having this, getting the same error as above. version 2.2.2-fix and also a newer version a while back that i downloaded to test if that would fix it dont rmber which one tho. The crash for me is not only on startup, its random it seems, can go an hour or 1 day.

I have heard multiple users report that updating Windows resolves the issue for them. Maybe that is something you could try as well?

**Comment by Borinius** [comment] 2020-12-08 15:31
@leon-richardt do you know what update? the optional one?
this is the only on i have atm and it says its optional 2020-11, cumulative update for Windows 10 Version 20H2 for x64-based system (KB4586853)

**Comment by leon-richardt** [comment] 2020-12-08 15:38
Don't really know, we are not sure yet whether they are related at all even. I would just try installing all available updates.

**Comment by Borinius** [comment] 2020-12-08 18:16
will give it a try, ill report back.

**Comment by leon-richardt** [comment] 2020-12-10 11:52
@MESSIOS @Borinius

For easier reproduction, it'd be great if you could share your `window-layout.json` file with us. (Maybe upload it as a [Gist](https://gist.github.com/)?)
You can find that file in the `Settings` folder by clicking the "Open AppData directory" button under the section **AppData & Cache** in the settings.

**Comment by Borinius** [comment] 2020-12-11 07:46
Think that is the right file, hope it helps.
https://gist.github.com/Borinius/7f801956f73a3e55d4d9299bf92421fd

**Comment by McN57Y** [comment] 2020-12-20 04:00
@MESSIOS @Borinius 

I think I was having a similar issue as you. The app would crash at random intervals/times. Even when using the latest nightly build. _(Chatterino Nightly 2.2.3-beta2 (commit fea52faa6, 19.12.2020))_ Most crashes would occur when switching between theater or fullscreen viewing modes on Twitch, especially after just opening Chatterino or just after switching streams. Running in Compatibility mode has so far fixed my problems. YMMV.

**Event viewer:**
Faulting application name: chatterino.exe, version: 0.0.0.0, time stamp: 0x5fde078e
Faulting module name: ntdll.dll, version: 10.0.19041.662, time stamp: 0x27bfa5f0
Exception code: 0xc0000374
Fault offset: 0x00000000000ff0f9
Faulting process id: 0x1168
Faulting application start time: 0x01d6d67ea25a72a5
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: e1ac78d6-9a54-4504-9a1e-38291420a5d7
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Borinius** [comment] 2021-01-26 06:35
any news on this? ive installed the latest win update and its still happening, any other info/logs i can provide to help out?

**Comment by leon-richardt** [comment] 2021-02-12 08:00
Potentially related issue to track: #2323

**Comment by MichaelPogU** [comment] 2021-05-07 18:54
had the same problem, once i decided to run it as an admin and it fixed itself but maybe it was just a coincidence

**Comment by Bomjus1** [comment] 2021-05-18 03:18
still getting this issue. did my windows updates, restarted my PC, worked for a day. now it's crashing on startup again.

**Comment by jammehcow** [comment] 2021-05-18 03:38
@Bomjus1 Does it still happen on 2.3.2 beta?

**Comment by Bomjus1** [comment] 2021-05-18 15:02
it does not occur in the "Nightly 2.3.2" release that i installed last night.

**Comment by zneix** [comment] 2021-06-26 12:13
Duplicate of #2198, there's too many "chatterino crashing" / "chatterino crashing on startup" issues open, so I'll keep one open and close the other ones.

**Closed by zneix** 2021-06-26 12:13 UTC
Labels: bug
