### ISSUE TITLE
Spelling auto-correct option

### ISSUE THREAD

**Issue by PatrickKSU** [Chatterino/chatterino2#1768] opened 2020-06-30 02:04 UTC
**What should be added?**
an option that allows users to shows misspellings in whatever default language with red squiggle lines. 
right clicks shows potential corrections/emotes related to the misspelling.

**Why should it be added?**
this would help the illiterates such as myself :)

**Comment by cinemassacres** [comment] 2020-06-30 02:14
#16

**Comment by apa420** [comment] 2020-07-01 18:49
Duplicate of #16

**Closed by apa420** 2020-07-01 18:49 UTC
Labels: enhancement, needs triage
