### ISSUE TITLE
Customisable Mod Icons

### ISSUE THREAD

**Issue by alectbh** [Chatterino/chatterino2#2594] opened 2021-04-06 14:58 UTC
As moderators we like our customisation, this is why we would like to decide what colours are for out mod icons

Thanks,
Moderator

**Comment by jammehcow** [comment] 2021-04-07 08:55
I'm assuming you mean the mod sword badge like below? 
![Twitch_ModBadge_3](https://user-images.githubusercontent.com/4962764/113839084-79b1d500-97e3-11eb-9cbc-0fcf50338422.png)

That badge is dictated by Twitch so the green is chosen by them. 
We could use our own badge or modify the colour channels but I feel like that's a lot of work for something so tiny.

**Comment by zneix** [comment] 2021-04-08 06:15
I believe this is a duplicate of #737

**Comment by zneix** [comment] 2021-04-15 11:05
@alectbh given the very little information you've provided it's ultra unclear on what you mean by "mod icons" - in chatterino there are either mod badges or mod buttons, but there's no icons. Though, since mod badges are already customized I assume you've meant mod buttons and that Duplicate of #737. If i got you wrong, feel free to make a reply and re-open the issue. Cheers.

**Closed by zneix** 2021-04-15 11:05 UTC
Labels: enhancement
