### ISSUE TITLE
Additional Options for the Chatterino Extension

### ISSUE THREAD

**Issue by kehlery** [Chatterino/chatterino2#1746] opened 2020-06-19 06:58 UTC
**What should be added?**
There should be a setting added to the chatterino extension that allows the watching tab on the program to update to the current channel while not replacing the default twitch chat

**Why should it be added?**
I only use the extension so that i can use the watching tab. There are often times where i want to redeem channel points or check something in regular twitch chat, but to do that i have to disable the extension and refresh the page. It would be nice if there was a setting in the extension that allowed you to have the watching channel update but not replace the chat

**Comment by alazymeme** [comment] 2020-06-19 07:45
Duplicate of https://github.com/Chatterino/chatterino2/issues/1427

**Comment by cinemassacres** [comment] 2020-06-19 15:59
solution is to open the videos/clips in a new tab
![gif](https://user-images.githubusercontent.com/16343162/85153507-842ebe00-b213-11ea-8005-bcf5fcf627b2.gif)

**Comment by fourtf** [comment] 2020-06-21 19:11
That setting exists in the extension

**Comment by fourtf** [comment] 2020-06-21 19:12
![image](https://user-images.githubusercontent.com/6320036/85233032-d7fff980-b403-11ea-9b58-8be9fa634414.png)

**Closed** 2020-06-21 19:14 UTC
Labels: enhancement, needs triage

**Comment by alazymeme** [comment] 2020-06-21 23:51
> That setting exists in the extension

I think you misunderstood. They want an option to track who they are watching via the extension WITHOUT replacing web chat
