### ISSUE TITLE
Chatterino closing every time a message is input in a specific channel

### ISSUE THREAD

**Issue by iamlodd** [Chatterino/chatterino2#3820] opened 2022-06-15 01:10 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Seems like this issue is only happening in the Repullze channel, every time I type a word, the chatterino app closes down. Very frustrating and I dont know what is causing it. Doesnt matter if its one letter or a command. But, If I type in anyone elses channel, it works fine. 

### OS and Chatterino Version

Windows 10 2.3.5

**Comment by Felanbird** [comment] 2022-06-15 01:14
@iamlodd It's due to the fact that the message history of that channel is spammed with announcements - since they are 2 part messages it floods the history with too many messages, and thus reproduces a crash that happens when more than 1000 historical messages are loaded.

**Comment by iamlodd** [comment] 2022-06-15 01:20
> @iamlodd It's due to the fact that the message history of that channel is spammed with announcements - since they are 2 part messages it floods the history with too many messages, and thus reproduces a crash that happens when more than 1000 historical messages are loaded.

Thank you so much! Fixed by reducing max number of history messages to load on connect to 100 or 0!

**Comment by Felanbird** [comment] 2022-06-15 01:37
I'm going to go ahead and close this, and make a note of the more annoying issue in the original issue. #1421

**Closed by Felanbird** 2022-06-15 01:37 UTC
Labels: issue-report
