### ISSUE TITLE
Zero-Width emotes are behind animated emotes

### ISSUE THREAD

**Issue by telvann** [Chatterino/chatterino2#3230] opened 2021-09-06 12:05 UTC
**Describe your issue**
If you combo zero-width emotes with animated emotes the animated emote is on top.

In browser chat the zero-width emote is always on top.
In chatterino it works fine with static emotes

**Screenshots**

Chatterino with static emote:
![image](https://user-images.githubusercontent.com/85226184/132214892-293d6591-0d89-4632-ba38-534f5365707a.png)

Chatterino with animated emote:
![image](https://user-images.githubusercontent.com/85226184/132214681-50f1e457-d344-4d0f-98d3-87295194e9c7.png)

Webchat with animated emote:
![image](https://user-images.githubusercontent.com/85226184/132214726-88a4b07a-bc80-41af-81c2-03761dc01948.png)

**OS and Chatterino Version**
Nightly 4bfa56c

**Comment by talneoran** [comment] 2021-09-06 12:34
Duplicate of #2994.
Title is a bit off there though so I can see why.

**Closed** 2021-09-06 13:08 UTC
Labels: issue-report
