### ISSUE TITLE
New Hype Train emotes (animal set) don't show in the picker.

### ISSUE THREAD

**Issue by Magnificus36** [Chatterino/chatterino2#3031] opened 2021-07-17 15:31 UTC
The current new Hype Train emotes, the animal ones [1], don't show up in the picker.

1: https://help.twitch.tv/s/article/hype-train-guide#emotesntitles

**Comment by zneix** [comment] 2021-07-17 16:35
tl;dr this is a limitation due to how this new emoteset of Hype Train emotes is implemented on Twitch's side
See [my comment](https://github.com/Chatterino/chatterino2/issues/2935#issuecomment-881914969) on previous issue for more explanation.

**Comment by Mm2PL** [comment] 2024-03-09 01:42
Closing as duplicate of #3583. Same cause.

**Closed by Mm2PL** 2024-03-09 01:42 UTC
Labels: Platform: Twitch, blocked
