### ISSUE TITLE
Suggestion: Add the ability to use the character ":" to complete emotes.

### ISSUE THREAD

**Issue by gortys** [Chatterino/chatterino2#1366] opened 2019-10-13 23:25 UTC
**Is your feature request related to a problem? Please describe.**

Tab complete works for many emotes, however it isn't quite as useful when trying to type sub emotes with long names. For example, someone with the name bigfatpandaslayer might have emotes titled bigfatpandaslayerHi bigfatpandaslayerDog, which means to tab complete you have to cycle through all emotes starting with bigfat which takes a while when you're just trying to find an emote with a relatively simple name. The browser version of twitch allows a user to use ":" to complete emotes, negating the problem. It's the only feature from browser twitch that I miss.
**Describe the solution you'd like**

 I would like to be able to use ":" to complete emotes. Thats all. It'd make sub emotes much easier to type, which i feel a good amount of twitch users have.

**Describe alternatives you've considered**

 Other lesser used symbols such as ~ or | could be used so that : doesnt create complications when trying to type emojis.

**Additional context**
 Thanks for reading my suggestion! Im only suggesting this because I suffer from wrist pains, which makes twitch chat harder to use than usual.

**Comment by leon-richardt** [comment] 2019-10-14 09:33
Duplicate of #591.

You can enable substring matching for emote names in the settings (it's under the "Miscellaneous" section) which would allow you to type `dog` and complete that to `bigfatpandaslayerDog`.

**Comment by RAnders00** [comment] 2019-11-02 10:42
Closing this in favour of #591

**Closed by RAnders00** 2019-11-02 10:42 UTC
Labels: enhancement, needs triage
