### ISSUE TITLE
BUG: Crashing when removing accounts

### ISSUE THREAD

**Issue by okhuntre** [Chatterino/chatterino2#2055] opened 2020-10-10 16:06 UTC
**Describe the bug**
When trying to remove an account, chatterino crashes and fails to remove the account.

**To reproduce**
Try to remove an account.

**Screenshots**
https://imgur.com/a/jJ9D9Fc

**Chatterino version**
Chatterino 2.2.2 (commit 07fc0c3ad)

**Operating system**
Windows 10

**Comment by alazymeme** [comment] 2020-10-11 13:57
Cannot reproduce:

Windows 10
Chatterino Nightly 2.2.2 (commit 3be62c929, 11.10.2020)

**Comment by TranRed** [comment] 2020-10-11 21:35
I can actually reproduce this on my laptop, but not on my desktop. Both windows 10 and I can confirm this for multiple different nightlies since mid of 2019. And it's all the remove buttons likewise in my experience.

Didn't really care to investigate further so far. I change these settings very rarely and just editing the json was always an acceptable workaround for me.

**Comment by sando** [comment] 2020-10-20 13:15
This was fixed in 1ec109748f715cc0150bfd4e75326371a9d82dc5 - doesn't look like it can be reproduced on later builds?

**Comment by apa420** [comment] 2020-10-20 13:20
@okhuntre @TranRed can you test if this occurs on the latest nightly?

**Comment by TranRed** [comment] 2020-10-20 18:17
No crash on 3c6e6446c for me

![NOIDONTTHINKSO](https://user-images.githubusercontent.com/16636423/96627497-3cc75400-1311-11eb-86a9-5ab33943dd0f.gif)

**Comment by fourtf** [comment] 2020-10-22 18:20
seems to be fixed

**Closed by fourtf** 2020-10-22 18:20 UTC
Labels: bug, needs triage
