### ISSUE TITLE
when you have open links in incog/private mode ticked on it does not work 

### ISSUE THREAD

**Issue by cinemassacres** [Chatterino/chatterino2#1534] opened 2020-02-05 00:40 UTC
**Describe the bug**

when you have open links in incog/private mode ticked on it does not work and it's open in non incog tab
**To reproduce**

tick open links in incog/private mode, open a link
**Screenshots**

https://streamable.com/q5yvf
**Chatterino version**

Chatterino 2.1.7 (commit 845c8fa63)
**Operating system**
N/A

**Additional information**

**Comment by 5E7EN** [comment] 2020-02-05 02:42
I believe this is intentional behavior.
The purpose of that setting is to affect the right-clicking of links and if you take a look at that menu closely, it gives you the option to open the link in an incognito window as well.

**Comment by apa420** [comment] 2020-02-07 16:35
This is not intentional behaviour. Ticking the checkbox should indeed make all links get opened in icognito/private.

**Comment by alazymeme** [comment] 2020-02-08 09:21
@apa420 Why would the "open link" option remain there if that option is enabled? imo this is intentional behaviour, this option should only change left clicking the link; not right clicking and clicking "open link" (when an obvious option to open in incognito is just below that.

**Comment by apa420** [comment] 2020-02-08 15:32
The issue is that ticking the option and clicking a link will open it in normal mode and not private/icognito mode. The option when right-clicking should not change.

**Comment by alazymeme** [comment] 2020-02-09 01:30
It works just fine for me, and in the gif it shows him right clicking > open link. Am I missing something? This behaviour seems entirely intentional to me...

**Comment by apa420** [comment] 2020-02-09 18:17
I guess I messed up testing. I never checked the streamable link. But what he's showing is intentional. So I'll close this issue.

**Closed by apa420** 2020-02-09 18:17 UTC
Labels: bug

**Comment by apa420** [comment] 2020-02-09 18:19
Sorry @5E7EN @alazymeme
