### ISSUE TITLE
Fast emote search with ":"

### ISSUE THREAD

**Issue by Qureneko** [Chatterino/chatterino2#1168] opened 2019-07-29 10:44 UTC
this search function that gets triggered by ":" in the beginning.
![Screenshot_4](https://user-images.githubusercontent.com/40634631/62042482-e0a57b00-b206-11e9-9165-8b6442ca605c.png)

**Comment by Qureneko** [comment] 2019-07-29 17:07
and for "@" users too. Not tab. Arrows+enter

**Comment by fourtf** [comment] 2019-07-29 17:10
Duplicate of #591

**Closed by fourtf** 2019-07-29 17:10 UTC
