### ISSUE TITLE
Unable to remove mod buttons, highlights, accounts, etc.

### ISSUE THREAD

**Issue by GodHatesBaguettes** [Chatterino/chatterino2#1597] opened 2020-03-10 20:25 UTC
**Describe the bug**
Unable to remove many settings in Chatterino.  This includes mod buttons, highlights, and accounts.  When attempting to remove something Chatterino will crash and not remove it.  I am able to add as many buttons, highlights, and accounts as I want, I just can't remove them.

**To reproduce**
Attempt to remove a mod button, highlight, or account.

**Screenshots**
![image](https://user-images.githubusercontent.com/25945839/76350148-d7b67500-62d0-11ea-8796-627b9ebca954.png)
![Annotation 2020-03-10 131410](https://user-images.githubusercontent.com/25945839/76350265-10564e80-62d1-11ea-8a3f-1b18c59437d1.jpg)

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 2e39dd4d9, )

**Operating system**
Windows 10

**Additional information**
This happens no matter what version of Chatterino I run, I switched to nightly hoping it would be fixed but it didn't change the problem at all.

**Comment by Mm2PL** [comment] 2020-03-10 20:29
Possibly related to #814, #1586

**Comment by apa420** [comment] 2020-03-10 20:42
Duplicate of #1586 
Please search for your issue before posting a new one

**Closed by apa420** 2020-03-10 20:42 UTC
Labels: bug, needs triage
