### ISSUE TITLE
Show FFZ bot and bot/mod chat badges

### ISSUE THREAD

**Issue by n1kodim** [Chatterino/chatterino2#3647] opened 2022-04-03 17:50 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I added a user to my channel's bot list via FFZ to display a special badge in the chat. But this badge is not displayed in Chatterino.

### Screenshots

![chrome_BLQviYHwwl](https://user-images.githubusercontent.com/54215444/161440883-4e649d6b-517c-4713-821a-41a42bffbba3.png)

![chrome_f8oZ9vhZ9K](https://user-images.githubusercontent.com/54215444/161440868-5fe3cde4-5487-45a8-a2fc-49ac24e140ae.png)

### OS and Chatterino Version

Chatterino 2.3.4 (commit 4e5170799)

**Comment by Felanbird** [comment] 2022-04-03 17:54
Duplicate of #2241

**Closed by Felanbird** 2022-04-03 17:54 UTC
Labels: issue-report
