### ISSUE TITLE
Animated emotes do not show in the "Subs" tab of the emotes window after refreshing emotes

### ISSUE THREAD

**Issue by karl-police** [Chatterino/chatterino2#2902] opened 2021-06-19 16:42 UTC
**Describe your issue**

If you refresh the emotes using F5 as example, if you open the emotes window, the animated emotes do not show in the "Subs" tab anymore.

**OS and Chatterino Version**
Windows 10, Chatterino Nightly 2.3.2 (commit 964083795)

**Comment by sando** [comment] 2021-06-19 16:53
Duplicate of #2631

**Comment by Mm2PL** [comment] 2021-06-19 16:59
Duplicate of #2631

**Closed by Mm2PL** 2021-06-19 16:59 UTC
Labels: issue-report
