### ISSUE TITLE
Select which channel to log

### ISSUE THREAD

**Issue by lyniakk** [Chatterino/chatterino2#1700] opened 2020-05-21 18:51 UTC
**What should be added?**
Ability to whitelist channel to log.

**Why should it be added?**
I have added lot of channels to Chatterino and I want to log only few of them. Now I have to log them all because I can't select which one should be logged.

**Comment by Mm2PL** [comment] 2020-05-21 18:53
duplicate of #1456

**Closed** 2020-05-22 13:54 UTC
Labels: enhancement, needs triage
