### ISSUE TITLE
Rightclick emotes in emote popup

### ISSUE THREAD

**Issue by fourtf** [Chatterino/chatterino2#1836] opened 2020-08-05 20:37 UTC
**What should be added?**
Right clicking emotes in the emote popup
- copy image
- go to ffz/bttv page

**Comment by zneix** [comment] 2020-08-06 00:14
Not sure, but isn't this a duplicate of #1735 ?

**Comment by cinemassacres** [comment] 2020-08-06 02:44
also this https://github.com/Chatterino/chatterino2/issues/1740

**Comment by apa420** [comment] 2020-08-06 20:29
Duplicate of #1735

**Closed by apa420** 2020-08-06 20:29 UTC
Labels: enhancement, needs triage
