### ISSUE TITLE
PubSub doesn't connect after a disconnect/reconnect

### ISSUE THREAD

**Issue by TETYYS** [Chatterino/chatterino2#1022] opened 2019-04-26 21:56 UTC
This also applies when switching accounts

**Comment by apa420** [comment] 2019-04-26 21:58
Also doesn't connect after being modded

**Comment by TETYYS** [comment] 2019-05-02 11:55
Now it works correctly after https://github.com/fourtf/chatterino2/pull/1049 , but still doesn't if I hibernate my PC with chatterino open and come back to it.

**Comment by apa420** [comment] 2019-05-02 12:54
It does not work correctly after #1049 the only thing #1049 did was make it so pubsub messages would appear in the right channel. This has nothing to do with the pubsub connecting or reconnecting issue.

**Comment by savabozo** [comment] 2019-05-08 07:54
Might be the cause of #937

**Comment by alazymeme** [comment] 2020-03-29 01:43
I just reconnected on d1d17d4e4 and it worked just fine. Does this still happen? Or am I missing a certain step?

**Comment by TETYYS** [comment] 2020-03-29 11:09
Can you try hibernating and resuming your PC?

**Comment by alazymeme** [comment] 2020-03-29 21:35
I will test when I get home tonight - I disabled hibernation on my pc a while ago so I'll have to re-enable it.

**Comment by fourtf** [comment] 2020-09-25 19:46
@pajlada do you know if this still happens?

**Comment by TETYYS** [comment] 2020-09-25 19:47
i personally still encounter it after every day `Chatterino Nightly 2.2.1 (commit 63c167f1d, )`

**Comment by Felanbird** [comment] 2020-10-18 13:55
I have been asked by a mysterious person to bump this. 😱

**Comment by zneix** [comment] 2021-02-26 20:46
This is happening very often as of recently, @pajlada could you look into this? thank you :heart:

**Comment by karl-police** [comment] 2021-05-10 06:01
It's happening too much

**Comment by karl-police** [comment] 2021-05-10 06:04
Does this work properly? https://github.com/Chatterino/chatterino2/blob/master/src/providers/twitch/TwitchChannel.cpp#L169

**Comment by Mm2PL** [comment] 2021-05-10 07:42
> Does this work properly? https://github.com/Chatterino/chatterino2/blob/master/src/providers/twitch/TwitchChannel.cpp#L783

That reconnects to pubsub, it just re-listens on an existing connection.

**Comment by apa420** [comment] 2021-05-10 11:03
Does this only happen when hibernating your pc?
Because it's properly connecting for me otherwise.

**Comment by Mm2PL** [comment] 2021-05-10 11:07
Pubsub connection still breaks after suspending my laptop. ![dank](https://cdn.frankerfacez.com/emote/536927/1)

**Comment by Felanbird** [comment] 2022-05-07 15:25
Fixed by #3643

**Closed by Felanbird** 2022-05-07 15:25 UTC
Labels: bug, backlog, pubsub
