### ISSUE TITLE
Add commands to use channel points

### ISSUE THREAD

**Issue by doximanman** [Chatterino/chatterino2#1672] opened 2020-05-06 16:44 UTC
**Describe the solution you'd like**
I suggest adding commands to use channel points, for eg. "/channelpoints count" would show you how many channel points you have, "/channelpoints list" would show you the channel points rewards for this channel, "/channelpoints claim 1/2/3..." would redeem a reward from the list with the channel points.
**Describe alternatives you've considered**
Add a button to the GUI (maybe next to the emote menu) that would function the same way the channel points button does in native chat.

I think this would be great as the only reason I use native chat is just when I want to use channel points, so it would be nice if it was available too in chatterino.

**Comment by leon-richardt** [comment] 2020-05-06 16:45
Duplicate of https://github.com/Chatterino/chatterino2/issues/1455. In short, there is no documented API to redeem channel points currently. Check #1455 for more information.

**Comment by SLCH** [comment] 2020-05-06 17:38
A little addition - we could use it, but twitch finds the usage of it as smth illegal and would send their law bajs if it was implemented.

**Comment by apa420** [comment] 2020-05-07 18:54
Duplicate of #1455

**Closed by apa420** 2020-05-07 18:54 UTC
Labels: enhancement, needs triage
