### ISSUE TITLE
Trying to remove a channel from the Live Notifications settings tab crashes the application

### ISSUE THREAD

**Issue by ProTear** [Chatterino/chatterino2#2390] opened 2021-01-22 22:21 UTC
As stated in the title:

https://user-images.githubusercontent.com/30202043/105554802-16310480-5cd6-11eb-92fd-0ba0a1f1909b.mp4

**Comment by Mm2PL** [comment] 2021-01-22 22:21
Could you please include the Chatterino version from the About section of the settings?

**Comment by ProTear** [comment] 2021-01-22 22:23
Sorry about that, new to this
![image](https://user-images.githubusercontent.com/30202043/105555022-88094e00-5cd6-11eb-86bf-4378997ade0e.png)

**Comment by Mm2PL** [comment] 2021-01-22 22:31
I am unable to reproduce the issue on latest nightly. Could you try updating to it and reproducing the issue again?

**Comment by zneix** [comment] 2021-01-22 22:32
Cannot reproduce on Arch Linux 5.10.9, i3 4.19, Chatterino version: latest master branch (857705668e65bceeb9833ff87f61b3ac11245bda)
Please update to [the latest nightly](https://github.com/Chatterino/chatterino2/releases/tag/nightly-build) and see if your issue still persists on that version.

**Comment by ProTear** [comment] 2021-01-22 22:33
The issue is fixed in the latest nightly version, thanks.

**Comment by alazymeme** [comment] 2021-01-23 01:49
Can we close the issue? ![FeelsDankMan](https://cdn.frankerfacez.com/emote/536927/1)

**Closed** 2021-01-23 03:05 UTC
Labels: bug
