### ISSUE TITLE
Anonymous mode glitch

### ISSUE THREAD

**Issue by CycloneYT** [Chatterino/chatterino2#2174] opened 2020-11-10 03:14 UTC
When i was in anonymous mode i got "ping" but the @ wasn't mine

1) Go in anonymous mode
2) Wait for a random ping

https://i.imgur.com/WnmviGy.jpg

Chatterino Nightly 2.2.3-beta (commit 0eed45ae6, )

Windows 10

**Comment by fanway** [comment] 2020-11-10 03:28
Duplicate of #2156

**Closed** 2020-11-10 09:17 UTC
Labels: bug, needs triage
