### ISSUE TITLE
New link regex seems to pickup the wrong thing

### ISSUE THREAD

**Issue by alazymeme** [Chatterino/chatterino2#1468] opened 2019-12-29 12:07 UTC
**Describe the bug**
New link regex picks up the wrong phrases

**To reproduce**
One word/number followed by a . and another word or number

**Screenshots**
![image](https://user-images.githubusercontent.com/12804673/71556719-85aed300-2a87-11ea-82ea-bd7c8df41214.png)

**Chatterino version**
Chatterino Nightly 2.1.6 (commit 443aba3f9, 29.12.2019)

**Operating system**
Windows 10

**Comment by pajlada** [comment] 2019-12-29 14:35
Duplicate of #1466 - feel free to add a list of links that are currently being parsed but should (and other way around)

**Closed by pajlada** 2019-12-29 14:35 UTC
Labels: bug, needs triage
