### ISSUE TITLE
An intentionally introduced delay in chat.

### ISSUE THREAD

**Issue by Yusuf-joe** [Chatterino/chatterino2#1796] opened 2020-07-07 22:32 UTC
**What should be added?**
An option to introduce a set delay in chat and the auto scroll.

**Why should it be added?**
The internet connection speed in my country, despite being high enough to watch streams in FHD and source qualities (60Mbps down), it doesnt go high enough in time for a livestream so it causes the streams to keep buffering every couple of seconds, even for lower qualities like 160p theres still a buffer every minute or so. 

By using 3rd party players such as Alternate Player for Twitch.tv, streamlink and vlc, i was able to solve the problem by adding a delay, a delay that works can range from 15 to 30secs to be able to watch any stream in any quality, but the chat is always in advance for me, sometimes spoiling things that happens on stream for me, if you can add the option to delay chat or a delayed auto scroll, it would solve my chat desync problem.

**Comment by apa420** [comment] 2020-07-08 00:56
Duplicate of #645

**Closed by apa420** 2020-07-08 00:56 UTC
Labels: enhancement, needs triage
