### ISSUE TITLE
Doesn't start: GLIBC not found

### ISSUE THREAD

**Issue by MrBarnabass** [Chatterino/chatterino2#2665] opened 2021-04-22 21:24 UTC
**Describe the bug**
Chatterino doesn't start since updating to 2.3.0 from 2.2.2

**To reproduce**
I used the appimage from https://chatterino.com/linux

**Result**
Running it from the command line results in this:
/tmp/.mount_chatteoX1Sri/usr/bin/chatterino: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_chatteoX1Sri/usr/bin/chatterino)

/tmp/.mount_chatteoX1Sri/usr/bin/chatterino: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_chatteoX1Sri/usr/bin/../lib/libpulse.so.0)

/tmp/.mount_chatteoX1Sri/usr/bin/chatterino: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_chatteoX1Sri/usr/bin/../lib/libpulsecommon-13.99.so)

/tmp/.mount_chatteoX1Sri/usr/bin/chatterino: /lib64/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/.mount_chatteoX1Sri/usr/bin/../lib/libsystemd.so.0)

/tmp/.mount_chatteoX1Sri/usr/bin/chatterino: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_chatteoX1Sri/usr/bin/../lib/libsndfile.so.1)

/tmp/.mount_chatteoX1Sri/usr/bin/chatterino: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_chatteoX1Sri/usr/bin/../lib/libFLAC.so.8) 

**Chatterino version**
Since it won't start I cant access the about page I can't paste the whole thing but the version is 2.3.0

**Operating system**
Red Hat Enterprise Linux 8.3

**Additional Information**
Seems like chatterino fails to create the .mount_chatteoX1Sri directory, I only found similar directories (.mount_chatteXYZXYZ) that were made before updating, maybe irrelevant I don't know.

**Comment by MrBarnabass** [comment] 2021-04-22 21:58
Using the flatpak instead of the appimage works.

**Comment by zneix** [comment] 2021-04-23 07:33
I did the same steps and can't reproduce this on Arch Linux 5.11.16.arch1-1

> I cant access the about page I can't paste the whole thing but the version is 2.3.0

Since you're on linux, you can try running `chatterino --version` and that should give you exact version with git commit.

> Seems like Chatterino fails to create the .mount_chatteoX1Sri directory

I don't think it fails to do that, since your logs state that `/tmp/.mount_chatteoX1Sri/usr/bin/chatterino` exists.

If I'm correct, the AppImage from https://chatterino.com/linux is built from CI, not exactly sure about flatpak one.
Not an AppImage expert, but maybe AppImage in CI might be missing some library that's reqiured for Chatterino to run on your system.

**Comment by MrBarnabass** [comment] 2021-04-23 08:25
Running ./chatterino --version results in the same error

**Comment by Fijxu** [comment] 2021-04-23 08:32
I can confirm, no works 
![image](https://user-images.githubusercontent.com/61166695/115843493-e5538f00-a3ec-11eb-9587-f6313f9fd951.png)

**Comment by zneix** [comment] 2021-04-23 11:14
@MrBarnabass @Fijxu could you guys check what libc version do you have?
I'm asking because I believe this might be a cause due to RHEL shipping 2.28 and Chatterino may require 2.29 or newer. My guess is that flatpak provides required libraries thus it's working. For now you can use Flatpak and if we can't do anything about this, I'll ask fourtf to specify that AppImage doesn't work on RHEL.

**Comment by MrBarnabass** [comment] 2021-04-23 19:45
I can confirm it does come with 2.28

**Comment by theaustria** [comment] 2021-04-24 11:23
I have the same problem, Chatterino 2.2.3-beta2 is working. Version of glibc is 2.27.
![grafik](https://user-images.githubusercontent.com/1621312/115956813-4e2b2c00-a4ff-11eb-98dc-1069adf0d83e.png)

**Comment by digital-carver** [comment] 2021-09-24 19:34
The usual suggested solution appears to be to create the AppImage on an older system for eg. one with glibc 2.26, which will make that be the version requirement for the resulting AppImage: 
1. https://askubuntu.com/questions/1125407/i-cant-install-pencil2d-using-its-appimage-any-help
2. https://github.com/thestr4ng3r/chiaki/issues/25

**Comment by Felanbird** [comment] 2023-08-23 22:11
As this is a 2021 issue, and we more or less hate the AppImage now, I'm going to go ahead and close this.

Currently the approach is to support as many distros as possible natively, and leaving the AppImage as a last resort, as it's usefulness is no longer outweighing the issues that arise from it. As noted from the original author, the flatpak worked on his distro.

**Closed by Felanbird** 2023-08-23 22:11 UTC
Labels: bug
