### ISSUE TITLE
Possible race condition when logging messages

### ISSUE THREAD

**Issue by ScrubN** [Chatterino/chatterino2#5552] opened 2024-08-20 02:25 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

It seems it may be possible for 2 threads to write to a given log file at once, creating duplicate and/or malformed messages.

I noticed this about 2 weeks ago but only just got around to reporting it so forgive me if I'm misremembering, but I believe there was a message history service recover event when the messages in the screenshot were sent (and logged).

### Screenshots

![image](https://github.com/user-attachments/assets/d782639c-ccc0-44da-a216-f3dafa9d4db8)
(the conversation topic is very ironic)

### OS and Chatterino Version

Chatterino 2.5.1 (commit eafcb941) built with Qt 6.5.0, MSVC 193833135 Running on Windows 10 Version 22H2, kernel: 10.0.19045

**Comment by pajlada** [comment] 2024-08-20 06:42
Duplicate of https://github.com/Chatterino/chatterino2/issues/5470

Some windows, when opened, started logging all the messages it saw.
e.g. if you opened a usercard of a user, it might log that user's messages again, or if you opened a search popup, it might log those again.

The issue will have been fixed in the next stable release, for now you can update to the latest nightly version.

**Closed by pajlada** 2024-08-20 06:42 UTC
Labels: issue-report
