### ISSUE TITLE
Gifted subs not appearing in 2.1.3

### ISSUE THREAD

**Issue by Jibbby** [Chatterino/chatterino2#1277] opened 2019-09-03 03:55 UTC
**Someone gifted 25 subs and it didnt appear**

**Comment by Evanito** [comment] 2019-09-03 05:27
Duplicate of #1252 's subproblem

**Comment by RAnders00** [comment] 2019-09-08 21:26
Closing this since a fix should be released, should the issue persist feel free to open another issue

**Closed by RAnders00** 2019-09-08 21:26 UTC
Labels: bug, needs triage
