### ISSUE TITLE
/mentions is blank when you're mentioned and haven't visited /mentions tab since app launched

### ISSUE THREAD

**Issue by zneix** [Chatterino/chatterino2#1617] opened 2020-03-28 15:31 UTC
**Describe the bug**
When I launch chatterino and someone mentions me, my /mentions tab is red, sound also plays. The message that mentions me is also highlighted, but if I haven't "visited" /mentions tab since application launch, that tab is completely blank.

**To reproduce**
1. Launch chatterino on tab different than /mentions and don't go to /mentions
2. Get mentioned/pinged by someone in another channel
3. Go to /mentions

**Screenshots**
pajbot mentioned me https://zneix.s-ul.eu/iM9Fd5YX.png
mentions is blank https://zneix.s-ul.eu/edaCUKbX.png

**Chatterino version**
Chatterino 2.1.7 (commit [845c8fa63](https://github.com/Chatterino/chatterino2/commit/845c8fa63) 29.12.2019)

**Operating system**
Linux Debian 10 (it occurs on Windows 10 1909 as well)

**Additional information**
I'm pretty sure, that same thing happens with /whispers tab. However, once you visit the tab, all the mentions and whispers work perfectly fine.

**Comment by apa420** [comment] 2020-03-28 23:09
I can't reproduce on windows 8.1`6229b2f43`

**Comment by alazymeme** [comment] 2020-03-29 01:04
Can reproduce. Windows 10, 1909; d1d17d4e4

**Comment by alazymeme** [comment] 2020-03-29 01:41
Furthermore, duplicate of https://github.com/Chatterino/chatterino2/issues/779

**Comment by pajlada** [comment] 2020-03-29 11:10
Duplicate of #779

**Closed by pajlada** 2020-03-29 11:10 UTC
Labels: bug, needs triage
