### ISSUE TITLE
Alt Gr triggers the split overlay as well

### ISSUE THREAD

**Issue by karl-police** [Chatterino/chatterino2#2903] opened 2021-06-19 18:05 UTC
**Describe your issue**

If you press "Alt Gr" it makes the split overlay show as well, which should show when pressing CTRL + ALT. This is an annoying issue, because on keyboards that have "Alt Gr", there are also combinations that use "Alt Gr" but can also be used with CTRL + ALT, but if "Alt Gr" exists, then "Alt Gr" gets mostly pressed as far as I know, rather than CTRL + ALT.

And it is possible to differentiate the key "Alt Gr" from CTRL + ALT.

Alt Gr shouldn't be triggering the split overlay. Alt Gr is used as some kind of shortcut for CTRL + ALT, to type symbols.

I don't think you can even disable that split overlay from appearing in the settings?

&nbsp;
On the "On Screen Keyboard", when pressing Alt Gr, this issue doesn't happen, unsure why, there are other issues regarding On Screen Keyboard in some applications.

**OS and Chatterino Version**
Windows 10, Chatterino Nightly 2.3.2 (commit 964083795)

**Comment by Mm2PL** [comment] 2021-06-19 18:53
Duplicate of #490

**Closed by Mm2PL** 2021-06-19 18:53 UTC
Labels: issue-report
