### ISSUE TITLE
Emote menu issue

### ISSUE THREAD

**Issue by CycloneYT** [Chatterino/chatterino2#2240] opened 2020-11-29 17:11 UTC
**Describe the bug**
When opening the emote menu it will only open on my main monitor even if my chatterino is on my second monitor. This is not the case with the settings menu. When i open the settings menu it saves it location no matter what. 

**To reproduce**
1. Have chatterino open on a second monitor(not main monitor)
2. Open emote menu
3. If opens on main monitor then drag to second monitor and close 
4. Reopen emote menu(still opens on main monitor)

**Screenshot**
![]( https://i.imgur.com/yqyhtm3.png)

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit 0a0cfb8e4, )

**Operating system**
Windows 10

**Additional information**
I've gone into window-layout.json where the emote menu position is saved and it does in fact save its location on my second monitor. But when opening the emote it ignores what is saved and opens on the closest possible location on my main monitor.

**Comment by Mm2PL** [comment] 2020-11-29 17:14
Looks like it always opens on the left monitor (where I usually have Chatterino) even if the main window is on the right one, in other words: can reproduce.
Ubuntu 20.04; WM: i3

**Comment by alazymeme** [comment] 2020-12-09 03:53
Duplicate of #1926

**Closed** 2020-12-13 10:45 UTC
Labels: bug
