### ISSUE TITLE
Support for Personal BTTV Emotes

### ISSUE THREAD

**Issue by JonasXc** [Chatterino/chatterino2#1415] opened 2019-11-14 02:21 UTC
**Is your feature request related to a problem? Please describe.**
Yes, since the personal emotes are part of "BetterTTV Pro" and it would be unfortunate if I couldn't use my personal BetterTTV emotes while using Chatterino.

**Describe the solution you'd like**
A way to detect if people have BetterTTV Pro, so they can use their personal emotes.

**Additional context/screenshots**

[The BetterTTV feature I'm talking about](https://gyazo.com/c1897111b7a863929cf20e7c1a4b2b3f)

[Screenshot of both chats, showing that it is not working in chatterino](https://prnt.sc/pwnta1)

**Comment by Felanbird** [comment] 2019-11-14 05:25
#12 
There is no API for personal emotes so there's nothing we can do, hence such an old issue still open

**Comment by pajlada** [comment] 2019-11-16 11:04
Duplicate of #12

**Closed by pajlada** 2019-11-16 11:04 UTC
Labels: enhancement, needs triage
