### ISSUE TITLE
Large timeout times in moderation buttons overlaps user's usernames

### ISSUE THREAD

**Issue by ALazyMeme** [Chatterino/chatterino2#2865] opened 2021-06-05 08:42 UTC
**Describe your issue**
Inputting overly large timeout times in the moderation button settings, overlaps users' usernames.

**Screenshots**
![image](https://user-images.githubusercontent.com/12804673/120885721-b48e8880-c62d-11eb-9af5-e7d98be39914.png)

**OS and Chatterino Version**
Windows 10, Chatterino 2.3.2, Commit 508fea638

_Idea sourced from https://github.com/Chatterino/chatterino2/pull/2864_

**Comment by alazymeme** [comment] 2021-06-05 08:43
Given the max timeout time is 2 weeks, we should probably check the unit and input to ensure it does not exceed said 2 week timeout.

**Comment by talneoran** [comment] 2021-06-05 09:34
I can look at this after #2864 is merged. Note that the screenshot in the issue is only reproducible with the changes there, for an example with the current build see https://github.com/Chatterino/chatterino2/pull/2864#issuecomment-855204985.

**Comment by talneoran** [comment] 2021-06-05 09:38
As a solution I suggest converting any entered duration that exceeds 2 weeks down to 2 weeks, and also displaying `2w` in the button text. This will allow the button to still work, giving the max timeout, and also inform the user that his input was too big and got cut down.

**Closed** 2021-06-27 12:14 UTC
Labels: bug, issue-report
