### ISSUE TITLE
Chatterino breaks audio on Mac

### ISSUE THREAD

**Issue by eniigma1337** [Chatterino/chatterino2#4445] opened 2023-03-10 20:41 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Im using Macbook Air M2. For some reason whenever I have chatterino open the audio from my mac starts cracking every 20 seconds or so. Its fixed as soon as I quit the Chatterino app.

### OS and Chatterino Version

Chatterino 2.4.2 (commit c8204ef7) built with Qt 5.15.2 Running on macOS 13.2, kernel: 22.3.0

**Comment by Mm2PL** [comment] 2023-03-10 20:44
Does [2.4.0](https://github.com/Chatterino/chatterino2/releases/tag/v2.4.0) and earlier break it too? I have a suspicion that this could be caused by us switching to Miniaudio a while back.

**Comment by eniigma1337** [comment] 2023-03-10 21:29
> Does [2.4.0](https://github.com/Chatterino/chatterino2/releases/tag/v2.4.0) and earlier break it too? I have a suspicion that this could be caused by us switching to Miniaudio a while back.

**Comment by eniigma1337** [comment] 2023-03-10 21:30
> Does [2.4.0](https://github.com/Chatterino/chatterino2/releases/tag/v2.4.0) and earlier break it too? I have a suspicion that this could be caused by us switching to Miniaudio a while back.

no it does not. I just tested it. 2.4.0 works fine

**Comment by LosFarmosCTL** [comment] 2023-03-10 23:19
I cannot reproduce this on macOS 12.6, so maybe an issue on Ventura. Or are you maybe using any additional audio software i.e. for separately controlling app volumes or something?

**Comment by eniigma1337** [comment] 2023-03-11 02:56
No not using any additional audio software. Fairly new computer dont have anything additional software installed and I tested closing other apps. Im using Ventura 13.2.1

**Comment by Felanbird** [comment] 2023-03-11 04:19
User reports having the issue on 7.4.2 - but not having it on 2.4.2
![image](https://user-images.githubusercontent.com/41973452/224464438-8d7651bf-f58c-4e9c-99e9-7dff80067919.png)
![image](https://user-images.githubusercontent.com/41973452/224464451-42840d56-8b16-4c26-b854-0e3261e28ec8.png)

**Comment by b-ggs** [comment] 2023-03-11 09:59
I can confirm that this also happens on the 14" MacBook Pro with M1 Pro on macOS 13.2.1.

Initially thought it was because of some audio issues with the amd64 -> arm64 translation layer, so tried building from source but the audio issues still persisted.

What worked for me to get 2.4.2 running without crackling audio was reverting the miniaudio change. https://github.com/b-ggs/chatterino2/commit/8019be3013f0f4ead3a4a552c4a4caa8bd57800f

**Comment by mektem** [comment] 2023-03-12 22:05
Can confirm I'm having this issue too. The issue seems to have occurred since 2.4.1 (or 7.4.1 in my case). I'm also on macOS 13. Had to revert to 2.4.0 (7.4.0) since it makes things basically unwatchable.

**Comment by pajlada** [comment] 2023-03-14 19:47
So it makes other sound play back improperly?

Any chance anyone's able to record a clean audio stream before & after starting chatterino?

**Comment by b-ggs** [comment] 2023-03-15 16:07
Unfortunately the crackling doesn't get picked up on OBS' macOS Screen Capture, as can be seen in OBS' audio mixer, so I used the built-in microphone for this video.

https://files.catbox.moe/tq0zws.mp4 (Recording is too big for GitHub attachments)

0:00 - 0:35 - Chatterino is closed, audio is smoothly playing
0:35 - Chatterino is opened
0:46, 0:56, 1:06, 1:16, 1:26 - Audio crackles
1:32 - 2:01 - Chatterino is closed, audio is smoothly playing

I also initially tried recording this with all my tabs closed, but the crackles only seem to occur when a tab is opened.

**Comment by arneeichhorn** [comment] 2023-03-15 20:56
I have the same issue... I don't know since when, but atleast for sure i have it with version 4.1 now... I think i have it already longer.

I found that the problem occures when chatterino is open by intensively searching for the audio crackling/popping problem and found this reddit where so many people have the exact same issue (videos and audio samples included): https://www.reddit.com/r/macbookpro/comments/s4r1m5/macbook_pro_16_2021_audio_crackling_issue_m1_pro/

One comment (https://www.reddit.com/r/macbookpro/comments/s4r1m5/comment/it6q7c9/?utm_source=reddit&utm_medium=web2x&context=3) suggests its related to rosetta 2 when running intel apps on m1.

thats why i looked up my running tasks and saw that Chatterino is running as an Intel Architecture app. I stopped chatterino and the crackling was instantly gone... left it closed for some time, not a single crackling sound. then i opened it again and the crackling starts again. this is 100% reproducible for me.

then i tried to find a chatterino specific solution for this and found this issue. i guess its a apple / rosetta problem when an intel architecture app accesses the audio interface? maybe its only fixable by building an Apple Silicion Native app version.

hope this is some help in finding the problem...

**Comment by pajlada** [comment] 2023-03-15 21:51
If anyone having the problem is able to build c2 natively and running it to see if that fixes that problem that would be super helpful, atm I don't have an arm-compatible building system to test on

**Comment by dieserRobin** [comment] 2023-03-15 22:17
Can't produce the error at the moment, but have had it several times in the past with Chatterino. A native build fixed the problem, but as mentioned, I'm currently running the Intel version as well. (M1 Pro) 

I had this problem in other programs only when RAM usage was extremely high.

**Comment by arneeichhorn** [comment] 2023-03-15 22:20
> Can't produce the error at the moment, but have had it several times in the past with Chatterino. A native build fixed the problem, but as mentioned, I'm currently running the Intel version as well. (M1 Pro)
> 
> I had this problem in other programs only when RAM usage was extremely high.

Right now I'm having 28GB of 64GB RAM usage. 0 Byte Swap usage. And its cracking every 5-20 seconds.

I'm trying to build it now with the macos build instructions of chatterino.

**Comment by Felanbird** [comment] 2023-03-15 23:40
> EDIT 2: 1 hour now without audio cracks... seems good.

Likely related to the fact that Github runners don't have m1 support https://github.com/github/roadmap/issues/528

**Comment by tamsch** [comment] 2023-03-16 00:13
> > EDIT 2: 1 hour now without audio cracks... seems good.
> 
> Likely related to the fact that Github runners don't have m1 support [github/roadmap#528](https://github.com/github/roadmap/issues/528)

I don't understand your comment mate.... I only have question marks in my head. What do you mean about the reference to github runners?

**Comment by Sanafan** [comment] 2023-03-16 00:16
> > EDIT 2: 1 hour now without audio cracks... seems good.
> 
> Likely related to the fact that Github runners don't have m1 support [github/roadmap#528](https://github.com/github/roadmap/issues/528)

huh? What u mean? 

Thanks for all the work to arne, what you have done runs astrein!

**Comment by Felanbird** [comment] 2023-03-16 00:20
> I don't understand your comment mate.... I only have question marks in my head. What do you mean about the reference to github runners?

The builds you download are generated by the system Github Actions offers, if the audio issue can't be replicated by arneeichhorn while building Chatterino locally, it's very likely the issue stems from the fact that Github actions does not yet offer a runner that correctly supports your mac hardware.

**Comment by arneeichhorn** [comment] 2023-03-16 00:26
> > I don't understand your comment mate.... I only have question marks in my head. What do you mean about the reference to github runners?
> 
> The builds you download are generated by the system Github Actions offers, if the audio issue can't be replicated by arneeichhorn while building Chatterino locally, it's very likely the issue stems from the fact that Github actions does not yet offer a runner that correctly supports your mac hardware.

the chatterino release that is offered for download is an intel architecture build.
seems like a native apple silicon build is needed. with an native apple silicon arm build the sound issue seems to be gone (for me atleast). so from my internet research it seems like its an rosetta (the engine that translates intel architecture code for apple silicon) issue and not explicit a problem of chatterino. maybe its also an issue of multiple factors. when github provides an m1 builder it should also produce code for the apple silicon architecture or am I wrong? seems like the OSX Build of chatterino is currently only running on x86 runners.

**Comment by Felanbird** [comment] 2023-03-16 00:30
> or am I wrong?

As far as I'm aware what you've said is all correct 👍

**Comment by arneeichhorn** [comment] 2023-03-16 00:43
> User reports having the issue on 7.4.2 - but not having it on 2.4.2

Btw. I also builded the 7.4.2 7TV Version myself and its also working fine as apple silicon native build. with the intel build it also has the audio crackling problem.

[2023-03-15_chatterino7.4.2_apple_silicon_build_release.zip](https://github.com/Chatterino/chatterino2/files/10985627/2023-03-15_chatterino7.4.2_apple_silicon_build_release.zip)

**Comment by Brog33** [comment] 2023-03-16 06:49
M1 Pro here too and I have not experienced this crackling noise in Chatterino (even though it's running all day in the background). But that said, I do recognise the sound because I have an other app that generates exactly the same crackling noise from time to time (VICE C64 emulator).

**Comment by Mm2PL** [comment] 2023-03-16 09:13
Blocked until #2300 is fixed.

**Comment by pajlada** [comment] 2023-04-29 17:42
I ended up buying a mac mini and have set up a 'local CI' to build universal builds (ARM64 & x86_64).
This issue is fixed in nightly builds using the `Chatterino-universal-Qt-6.5.0.dmg` artifact, and the fix will be available in the next stable release.

**Closed by pajlada** 2023-04-29 17:42 UTC
Labels: bug, OS: Mac, blocked
