### ISSUE TITLE
Commands not expanding despite "Match trigger at end of message"

### ISSUE THREAD

**Issue by Coldblackice** [Chatterino/chatterino2#3074] opened 2021-07-26 13:16 UTC
**Describe your issue**

Regarding "Commands", despite enabling "_Also match the trigger at the end of the message_" enabled, custom commands don't expand when at the end of the line. The only place they properly expand is when they're at the very beginning of the line. 

Is this a bug, or am I doing it wrong?

**OS and Chatterino Version**

        Windows 10, Chatterino Nightly 2.3.3 (commit ae9f92ded, )

**Comment by sando** [comment] 2021-07-26 13:18
Duplicate of #2308

**Comment by Mm2PL** [comment] 2021-07-26 13:31
Duplicate of #2308

**Closed by Mm2PL** 2021-07-26 13:31 UTC
Labels: issue-report
