### ISSUE TITLE
Feature request: Chatterino 1 dark style (dark chat with white tabs) or custom colour styles in Chatterino 2

### ISSUE THREAD

**Issue by agenttud** [Chatterino/chatterino2#1041] opened 2019-04-30 12:54 UTC
I am talking about something like Chatterino 1's style, where you could have light-themed tabs with dark-themed chat (like in the [screenshot from the Chatterino site](https://chatterino.com/img/screenshot-1.png)). At the moment, the styles in Chatterino 2 change both the chat and tabs.

**Comment by savabozo** [comment] 2019-05-01 16:40
WutFace

**Comment by apa420** [comment] 2019-05-01 18:51
this is by design, early versions featured a layout similar to chatterino1

**Comment by fourtf** [comment] 2020-09-25 19:44
This issue is out of scope of the Chatterino project.

**Closed by fourtf** 2020-09-25 19:44 UTC
Labels: enhancement
