### ISSUE TITLE
Chatterino doesn't refresh access to moderator messages while app is open

### ISSUE THREAD

**Issue by karl-police** [Chatterino/chatterino2#2763] opened 2021-05-10 05:56 UTC
**Describe the bug**
Chatterino doesn't refresh access to moderator messages while app is open. This means that you can't see who timed out with reason and you can't see filtered messages, basically anything that has to do with Moderator messages can not be seen, even though you're a moderator.

**To reproduce**
Not really sure, except usage of the app.

When you reopen the app, apperantly it's fixed. Over the time, something happens and refreshing Chatterino doesn't fix it.

I think hibernation mode while app is open probably breaks it, unsure. Maybe it has to do with the opened tabs, however it's not working properly and best would be to verify it in the source code.

**Chatterino version**
Chatterino 2.3.1 (commit cf33566fd)

**Operating system**
Windows 10 64-Bit

**Comment by Felanbird** [comment] 2021-05-10 05:59
Duplicate of #1022

**Comment by karl-police** [comment] 2021-05-10 06:00
It's a 2 year old bug

**Comment by Felanbird** [comment] 2021-05-10 06:06
The length of the issue report has no real meaning, it just means nobody has an idea/plan yet to deal with it. 2 year old bugs are just waiting for somebody to come along, see #869 #1016 etc

**Comment by Felanbird** [comment] 2021-05-10 06:06
So you can go ahead and close it.

**Closed** 2021-05-10 06:07 UTC
Labels: issue-report
