### ISSUE TITLE
Chatterino installer stays frozen

### ISSUE THREAD

**Issue by ACViper** [Chatterino/chatterino2#2669] opened 2021-04-23 15:14 UTC
After clicking the install button, the setup just stays frozen and doesn't install what so ever.
I am on Windows 10 and trying to install the latest version.

**Comment by sando** [comment] 2021-04-23 15:40
Please use the [issue template](https://raw.githubusercontent.com/Chatterino/chatterino2/master/.github/ISSUE_TEMPLATE/bug_report.md) when filing a bug report instead of clearing it, otherwise we have to take a wild guess on how to reproduce your issue.

Can you describe the problem further detail? Reproduction steps and a screen capture would be helpful, along with the exact Windows version you are running (right-click Start, then Run, then type `winver`).

**Comment by fourtf** [comment] 2021-04-23 16:42
This doesn't fit any of the issue templates, so it's fine to not use one.

**Comment by atrigent** [comment] 2021-04-24 17:44
I am encountering this issue. It looks like it's trying to delete the entire emote cache (which is currently about 72k files for me and may have been over 100k before I ran the installer).

**Comment by jammehcow** [comment] 2021-04-27 00:49
@atrigent you could try deleting the emote cache directory manually (at `%APPDATA%\Chatterino2\Cache` and rerun the installer.
@ACViper this might also solve your issue. Give it a try.

For the future it might be worth adding a cache expiry to our emote cache to prevent the huge backlog. Maybe 30 days?

**Comment by atrigent** [comment] 2022-01-09 00:18
@sando, @fourtf, @jammehcow, or anyone else who can make this change... Can you please modify the Windows installer so that it doesn't try to delete the cache directory? Thanks.

**Comment by jammehcow** [comment] 2022-01-09 00:21
![NOIDONTTHINKSO3x](https://user-images.githubusercontent.com/4962764/148664396-b396574d-e0f8-406c-b9c4-861c54775750.gif)
I wasn't even part of this discussion, do not ping me :)

**Comment by Nerixyz** [comment] 2023-10-06 18:49
> Can you please modify the Windows installer so that it doesn't try to delete the cache directory?

The current installer doesn't try to delete the cache by default:
https://github.com/Chatterino/chatterino2/blob/7c8cabaa420dd9ce9120c9a2ff14717d7749ff34/.CI/chatterino-installer.iss#L72

**Comment by Felanbird** [comment] 2023-10-06 20:30
Closing this as it was a 2021 issue that was only bumped once, the bump was resolved, and the original issue I've never heard reported since.
If someone is able to replicate this issue please open a new issue.

**Closed by Felanbird** 2023-10-06 20:30 UTC
Labels: bug
