### ISSUE TITLE
Adjust sound notification volume

### ISSUE THREAD

**Issue by KeeksEsq** [Chatterino/chatterino2#1931] opened 2020-09-01 21:17 UTC
**What should be added?**
I should be able to adjust the volume of my sound notifications.

**Why should it be added?**
Sometimes I need to be able to hear my notifications across the room, but when I'm streaming I'd prefer it to be barely audible. When it's the same volume all the time, sometimes I just have to turn it off.

**Comment by cinemassacres** [comment] 2020-09-02 01:01
duplicate https://github.com/Chatterino/chatterino2/issues/1436

**Comment by apa420** [comment] 2020-09-02 05:57
Duplicate of #1436

**Closed by apa420** 2020-09-02 05:57 UTC
Labels: enhancement, needs triage
