### ISSUE TITLE
whisper 

### ISSUE THREAD

**Issue by alaiiide** [Chatterino/chatterino2#2062] opened 2020-10-11 08:22 UTC
I try to send a whisper to someone on chat, using the /w and I cant. It shows the message: ''Your settings prevent you from sending this whisper.''
![image](https://user-images.githubusercontent.com/72686758/95673700-8aa9c280-0b81-11eb-9ee0-b2c7f1105d9b.png)

**Comment by pajlada** [comment] 2020-10-11 09:02
Duplicate of #1526

**Closed by pajlada** 2020-10-11 09:02 UTC
Labels: bug, needs triage
