### ISSUE TITLE
Adjustable chat delay

### ISSUE THREAD

**Issue by hptk** [Chatterino/chatterino2#645] opened 2018-07-29 19:04 UTC
I would like to be able to delay chat in Chatterino2, so that I can have chat synchronized with a video stream that is behind that of the average chatter.

For me, when I stream to my TV with Chromecast, I want to have chat available on a laptop, but I often end up closing it because chat spoils what will happen the next 5 sec on the stream.

The best would be something like a slider in the settings (or somewhere) where I could adjust the delay exactly to what I want it to be.

I am not sure if I would like the setting to be global or per chat.

**Comment by fourtf** [comment] 2020-09-25 19:13
This issue is out of scope of the Chatterino project.

**Comment by zneix** [comment] 2022-01-28 22:26
Recently we've came across this issue once again and turns out there's users (generally streamers) who'd benefit from this - mainly because of moderation of messages that are kept in the chat delay buffer. So while there might be no progress on implementing this, the issue is still relevant so I'm going to reopen this.

**Comment by Felanbird** [comment] 2022-01-28 22:28
just kidding we gonna make a new issue

**Closed by Felanbird** 2022-01-28 22:28 UTC
Labels: enhancement

**Comment by kamild1996** [comment] 2024-03-29 19:51
"Out of scope"? Really? What exactly is the "scope" of this project then if not to make chat more configurable/customizable?
Chatterino has so many useful features, yet the lack of just this one is sufficient for me to be a dealbreaker for those of us with unreliable internet connections.

**Comment by Felanbird** [comment] 2024-03-29 19:54
> "Out of scope"? Really? What exactly is the "scope" of this project then if not to make chat more configurable/customizable? Chatterino has so many useful features, yet the lack of just this one is sufficient for me to be a dealbreaker for those of us with unreliable internet connections.

This is a comment from almost 4 years ago you are commenting about, as I commented 2 years ago, we already re-opened this as a separate discussion, #3549.

**Comment by kamild1996** [comment] 2024-03-29 20:31
> > "Out of scope"? Really? What exactly is the "scope" of this project then if not to make chat more configurable/customizable? Chatterino has so many useful features, yet the lack of just this one is sufficient for me to be a dealbreaker for those of us with unreliable internet connections.
> 
> This is a comment from almost 4 years ago you are commenting about, as I commented 2 years ago, we already re-opened this as a separate discussion, #3549.

Was not aware of the discussion, thanks for the link. Still wanted to express demand for this feature - especially since that discussion you linked haven't had activity for around 2 years, and this issue shows up first when googling "chatterino chat delay".
