### ISSUE TITLE
Keybinds update

### ISSUE THREAD

**Issue by okhuntre** [Chatterino/chatterino2#1732] opened 2020-06-11 05:22 UTC
Customize key binds and use key binds when chatterino isn't in focus.
Because i use the same key binds for other things on my computer and its annoying when they activate things in chatterino

**Comment by Mm2PL** [comment] 2020-06-11 09:17
duplicate of #1592

**Comment by apa420** [comment] 2020-06-11 13:29
Duplicate of #1592

**Closed by apa420** 2020-06-11 13:29 UTC
Labels: enhancement, needs triage
