### ISSUE TITLE
arabic language

### ISSUE THREAD

**Issue by Nishyo** [Chatterino/chatterino2#1795] opened 2020-07-07 21:44 UTC
![download (5)](https://user-images.githubusercontent.com/67963524/86846689-e7459f00-c0b3-11ea-8ff0-85ab41abc2ad.png)
arabic words are backwards

**Comment by Mm2PL** [comment] 2020-07-07 21:46
Dupe of #1655

**Comment by apa420** [comment] 2020-07-08 00:55
Duplicate of #720

**Closed by apa420** 2020-07-08 00:55 UTC
Labels: bug, needs triage
