### ISSUE TITLE
@'ing someone

### ISSUE THREAD

**Issue by King-Joey** [Chatterino/chatterino2#2437] opened 2021-02-06 21:56 UTC
After searching through the wiki I still haven't found why I am unable to @ someone and when I start to type their name it auto-fills. Am I missing something or is this currently bugged?

**Operating system**
Windows 10

**Comment by alazymeme** [comment] 2021-02-07 00:17
Just want to confirm:

When you @ someone, it auto-completes?

**Comment by zneix** [comment] 2021-04-15 11:33
Duplicate of #1979

**Closed by zneix** 2021-04-15 11:33 UTC
Labels: bug
