### ISSUE TITLE
reverse chat vertical options missing

### ISSUE THREAD

**Issue by jackzback** [Chatterino/chatterino2#2872] opened 2021-06-06 21:37 UTC
**Describe your issue**

hello, this app looks perfect thank for your effort. i just cant find an option to reverse chat for a new message. i wanna see new messages from top not bottom if its possible if not please add <3 <3 <3 <3

-->

    
        Windows 10, Chatterino 2.3.0
       

-->

**Comment by Mm2PL** [comment] 2021-06-06 21:48
Same thing as #2821

**Comment by pajlada** [comment] 2021-06-06 22:55
Duplicate of #2821

**Closed by pajlada** 2021-06-06 22:55 UTC
Labels: issue-report
