### ISSUE TITLE
giving users a "nickname"

### ISSUE THREAD

**Issue by mxllyvnn** [Chatterino/chatterino2#1821] opened 2020-07-23 17:23 UTC
**What should be added?**
i'd love the ability to click on a username and add a nickname from the user card. i find myself using chatterino when i'm streaming, rather than my browser. find a lot of users have very similar usernames so would love to be able to give nicknames.
BTTV already has a nickname feature which i do use (but rarely use browser for chat), would love something similar on here. 

![image](https://user-images.githubusercontent.com/68705403/88317636-7805b700-cd11-11ea-9e16-9d2466c57927.png)

**Comment by Mm2PL** [comment] 2020-07-23 17:25
duplicate of #137

**Comment by apa420** [comment] 2020-07-23 17:37
Duplicate of #137

**Closed by apa420** 2020-07-23 17:37 UTC
Labels: enhancement, needs triage
