### ISSUE TITLE
Pause on hover breaks text selection

### ISSUE THREAD

**Issue by wigoor** [Chatterino/chatterino2#1336] opened 2019-09-24 18:14 UTC
If you scroll up and try to mark some text and someone types in chat the selection move with the chat even though the text isn't moving.
https://streamable.com/pq9cw

**Comment by Mm2PL** [comment] 2019-09-25 09:07
Can you please provide more details, like the Chatterino version? The issue template exists for you to know what to provide to make fixing the bug easier.

Here's a shortened version of it.
Ticked boxes represent things you have in your report, boxes that are not ticked represent things that are missing.

 - [x] Describe the bug
 - [x] To Reproduce. Steps to reproduce the behavior
 - [ ] Expected behavior. A clear and concise description of what you expected to happen. 
 - [x] Screenshots
 - [ ] Chatterino version Please copy the version information from the "About" page in the Settings, e.g. `Chatterino 2.1.4 (commit 35c7853c4, 16.09.2019)`
 - [ ] Additional context Add any other context about the problem here.

**Comment by wigoor** [comment] 2019-09-25 09:55
I expect it to work like a nomal select?
There is no version listed in Settings > About, but its 2.1.4-beta-2
no spammerino in the chatterino

**Comment by Mm2PL** [comment] 2019-09-25 10:01
Just tested it on 2.1.5. Seems to be fixed now. If you update to the newest nightly, you shoud not experience this issue.

**Comment by wigoor** [comment] 2019-09-25 10:09
Maybe, it might be related to the chat history limit, need to wait for a chat to go beyond that and see what happens.

**Comment by Mm2PL** [comment] 2019-09-25 10:14
The thing you showed on the screencast doesn't happen to me even with old messages getting removed. However if you are selecting and a new message appears the selection shifts and the mouse stays at the same place making selecting things harder.

**Comment by wigoor** [comment] 2019-09-25 10:17
Now i know what it is, its based on the chat hoover pause option, if you set it to 0.5s it will start to affect selections.

**Comment by Mm2PL** [comment] 2019-09-25 10:19
Can confirm this happens with having pause on hover set.

**Comment by RAnders00** [comment] 2019-09-25 21:03
Please update issue title to reflect it affects "pause on hover" feature 🙃

**Comment by fourtf** [comment] 2019-09-25 21:50
Nice find, turns out that `unpause()` isn't the only function that can actually unpause.

**Closed** 2019-09-25 21:49 UTC
Labels: bug, needs triage
