### ISSUE TITLE
Add an option to ask for confirmation when doing CTRL W

### ISSUE THREAD

**Issue by nitrousGranola** [Chatterino/chatterino2#1535] opened 2020-02-05 03:28 UTC
I often find myself wait to close a browser tab with ctrl w, but forgetting that I'm tabbed into Chatternio and close that tab instead of whatever I had open in my browser.

**Comment by leon-richardt** [comment] 2020-02-05 05:17
I feel like asking for confirmation goes against the idea of a key shortcut. Instead, like suggested in #1515, would an option to disable certain hotkeys solve your problem as well?

**Comment by fourtf** [comment] 2020-02-10 16:43
To improve error tolerance I believe that we should ask for confirmation.

**Comment by Mm2PL** [comment] 2020-03-10 20:52
Duplicates #339

**Comment by pajlada** [comment] 2020-03-14 13:24
Closing as duplicate of #339

**Closed by pajlada** 2020-03-14 13:24 UTC
Labels: enhancement
