### ISSUE TITLE
An option to make @mentions the same color as the mentioned person's username

### ISSUE THREAD

**Issue by mhollinger21** [Chatterino/chatterino2#2121] opened 2020-10-25 03:43 UTC
**What should be added?**
When you @ someone, there should be an option to make their username in your message the same color as their name. For example, if my username is bob, and someone @'d me in chat. The message should read: "@bob [this part in my color] hey! [this part in the normal text color]"

**Why should it be added?**
There's an option like this in the FrankerFaceZ Control Center on Twitch, and it makes it a lot easier to find the people who get @'d.

**Comment by alazymeme** [comment] 2020-10-25 05:15
Duplicate of https://github.com/Chatterino/chatterino2/issues/1963

**Closed** 2020-12-19 13:09 UTC
Labels: enhancement
