### ISSUE TITLE
Chatterino reverts back to default settings after system restart

### ISSUE THREAD

**Issue by Shigure02** [Chatterino/chatterino2#3262] opened 2021-10-01 07:33 UTC
**Describe your issue**
It's been a long time since this issue has been going on and sometimes when I restart my computer it reverts back to its default settings 

    Examples:
    - It reverts back to its default settings like clears the settings.
    - Tabs still stay the same and format. Splits remain, Close button re-enabled, 
    

 **Possible fix**
      -Copying the Settings folder from the %AppData% of Chatterino `` AppData > Roaming > Chatterino2 `` 

**OS and Chatterino Version**

        Win 10 Home, V 20H2 (OS Build 19042.867)
          Chatterino 2.3.4

**Comment by LosFarmosCTL** [comment] 2021-10-01 08:00
So only the current settings.json gets reset and everything else stays the same?

What about the commands and the .bkp backup settings files?

**Comment by Mm2PL** [comment] 2021-10-01 08:12
I have a little suspicion that winblows kills Chatterino while saving settings, so it leaves and invalid file behind and therefore can load the settings after restarting

**Comment by Akemi02** [comment] 2021-10-02 06:57
> So only the current settings.json gets reset and everything else stays the same?
> 
> What about the commands and the .bkp backup settings files?

I'm assuming the commands are reset as well as it wasn't saved for me and I'm not sure about the backup files as I haven't compared the differences of it yet, I apologize I'm quite new to Chatterino

**Comment by Felanbird** [comment] 2023-11-02 22:35
It's my strong belief that this issue only happens due to the users C: drive being a HDD, and it's a very old Windows issue.
I often ran into it with World of Warcraft addons, as many of them stored all of their data in `.json` files.

We discussed this in the Runelite discord back in July, as a `config.json` file is used for Runelite, and if it corrupts due to this, the client would silently fail to start. Another dev reported their belief that this was an issue that only happened on HDD's, and I confirmed I hadn't ran into it for programs installed on an SSD (chatterino, runelite, WoW addons after getting an SSD)

afaik the changes made here: [runelite/runelite@compare](https://github.com/runelite/launcher/compare/15d5b73ba7e92e0f745d74456b4ac8c8d35913e3...runelite:952d224b126dbd58691d76841634227666c18e63) fixed the problem for Runelite, but they are a java app and using fsync so this info probably doesn't help.

**Comment by Nerixyz** [comment] 2023-11-03 14:26
All the saving of settings is done in https://github.com/pajlada/settings. It uses iostreams to save [here](https://github.com/pajlada/settings/blob/f92bc7bc4940bf58b7f03cefa81a78ef09752007/src/settings/settingmanager.cpp#L512-L528). These do flush when closed. Maybe they don't flush hard enough. I wonder if it's any different with a `QFile`.

**Comment by pajlada** [comment] 2023-11-03 20:54
window-layout.json has the same issue, which uses QSaveFile

**Comment by Nerixyz** [comment] 2023-11-03 23:23
> - Tabs still stay the same and format. Splits remain, Close button re-enabled, 

> window-layout.json has the same issue, which uses QSaveFile

Tabs are saved in window-layout.json. Please clarify.

**Comment by Felanbird** [comment] 2023-11-03 23:24
> Tabs are saved in window-layout.json. Please clarify.

window-layout.json is often lost in this scenario as well

**Comment by Felanbird** [comment] 2023-11-03 23:31
I will acknowledge that my most-recent issue reporter _only_ lost their settings, window-layout and commands were not lost, but previous reports claim to also lose window-layout.
![image](https://github.com/Chatterino/chatterino2/assets/41973452/0e7b16f3-dc6a-4c03-981c-6fb0d4a19e9e)

**Comment by wigoor** [comment] 2024-06-29 11:33
Had this or a very similar issue happen today:
Yesterday i accidentaly pressed restart on my computer instead of shutdown, when i got back into windows i instantly shutdown windows again, the next day the settings were gone and 5/10 settings.json backup files was corrupted.
![Code_wfKoTXFt2v](https://github.com/Chatterino/chatterino2/assets/26260419/48cc6532-3d93-4be1-8e72-a0dc5dd1d529)

I have chatterino stored on an SSD though it is not my OS drive.
Shutdown might have happen during the startup of chatterino since its in my autostarts.

Chatterino Nightly 2.4.6 (commit [fbc8aaca](https://github.com/Chatterino/chatterino2/commit/fbc8aaca)) built on 2023-11-19 with Qt 6.5.0, MSVC 193732825
Running on Windows 11 Version 22H2, kernel: 10.0.22621

**Comment by pajlada** [comment] 2024-07-07 10:13
This should be fixed since https://github.com/Chatterino/chatterino2/commit/2d11e79f4d30bc2795e83bea652396cf169dbbc0 (just merged in). If you notice it after running Chatterino after that version, please re-open or comment on this issue. https://github.com/pajlada/settings/pull/87 is what actually did the work on improving this, and it looks super promising.

**Closed by pajlada** 2024-07-07 10:13 UTC
Labels: bug, OS: Windows, Feature: Settings

**Comment by w3bprinz** [comment] 2025-12-06 14:18
Same here every time the settings.json is gone all settings are removed and i have to setup again... thats so annoying!

**Comment by Nerixyz** [comment] 2025-12-06 14:23
> Same here every time the settings.json is gone all settings are removed and i have to setup again... thats so annoying!

See #6358. Chatterino also creates backups of your settings in `%APPDATA%/Chatterino2`.
