### ISSUE TITLE
Opening a link in Chatterino while Edge is closed causes Edge to start first time setup

### ISSUE THREAD

**Issue by Greenlandicsmiley** [Chatterino/chatterino2#4407] opened 2023-02-24 18:21 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [x] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

After PR #4362, opening a link while Edge is closed causes Edge to start the first time setup.

Steps to reproduce:

1. Make sure Edge is closed
2. Open a link in Chatterino

### OS and Chatterino Version

Chatterino 2.4.1 (commit 7e005ba6) on Windows 10 version 22H2 (19045.2604)

**Comment by ALazyMeme** [comment] 2023-02-24 23:19
Cannot reproduce using the portable build of the 2.4.1 release. Can you please try updating edge and confirm if you're still having the issue? I tested on version 110.0.1587.56

https://user-images.githubusercontent.com/12804673/221319553-765db268-a6cf-498c-8d58-c0212bb2f0fc.mp4

**Comment by kornes** [comment] 2023-02-24 23:21
tested with 2.4.1 release and also can't reproduce with Edge 110.0.1587.56 on win10 19045.2604
both incognito and standard links open correctly for me

**Comment by ALazyMeme** [comment] 2023-02-24 23:26
I'm closing this issue, since the solution is not to do with Chatterino.

**Closed by ALazyMeme** 2023-02-24 23:26 UTC
Labels: OS: Windows
