### ISSUE TITLE
Ignores not working with announcement messages

### ISSUE THREAD

**Issue by Nerixyz** [Chatterino/chatterino2#4694] opened 2023-06-18 17:20 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

_From https://github.com/SevenTV/chatterino7/issues/226:_

I found "ignores" function is not working to ignore bots announcement messages,
Is there any way to do this?

See also: https://github.com/Chatterino/chatterino2/issues/4163 (related to search filters)

### OS and Chatterino Version

Chatterino 7.4.4 (commit 90ee0af) built with Qt 5.15.2, Windows SDK, MSVC 193431944, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19044

**Comment by Mm2PL** [comment] 2023-08-01 19:20
Can reproduce on 89323ffa1fb73e00c7c2fefdbc92eab809107288. Weirdly enough non-block (replace) ignores work fine.

**Comment by Felanbird** [comment] 2023-08-01 19:43
Duplicate of #3412

**Closed by Felanbird** 2023-08-01 19:43 UTC
Labels: bug, Feature: Ignores
