### ISSUE TITLE
Emote List Not Updating

### ISSUE THREAD

**Issue by peterno3** [Chatterino/chatterino2#2980] opened 2021-07-08 16:28 UTC
**Describe your issue**
The emote list, and emote autocomplete, aren't updating with newly added emotes. The channel i'm chatting in has added a few new emotes over the past few days, but they don't appear in the emote menu, and tab doesn't complete them. 

**Screenshots**
From Chatterino:
![image](https://user-images.githubusercontent.com/5396987/124958146-ae921b80-dfce-11eb-93a2-cfc12e6ba2a5.png)

From Twitch directly:
![image](https://user-images.githubusercontent.com/5396987/124958282-d8e3d900-dfce-11eb-89f1-e5774519ac76.png)

**OS and Chatterino Version**
Windows 10 64-bit
Nightly 2.3.3, and also 2.3.2

**Comment by peterno3** [comment] 2021-07-08 16:29
Note, I tried clearing all of my cache, re-logging, and uninstalling and reinstalling Chatterino. None of them fixed the issue.

**Comment by zneix** [comment] 2021-07-08 16:29
Duplicate of #2935

**Closed by zneix** 2021-07-08 16:29 UTC
Labels: issue-report
