### ISSUE TITLE
A recently closed keybind

### ISSUE THREAD

**Issue by iAmAnt1** [Chatterino/chatterino2#2072] opened 2020-10-12 23:33 UTC
**What should be added?**
A recently closed command like chrome, where if you closed a chatterino tab, you can get it back from a keybind
**Why should it be added?**
I accidentally close tabs sometimes, and I forget what the tab is, so I wanted some sort of "history tab" that showed the tab you last closed in case of accidents like these.

**Comment by Felanbird** [comment] 2020-10-13 04:28
Just as a note, the keybind for chrome is Ctrl + Shift + T which is already taken so we'd have to decide on something else

**Comment by Y0dax** [comment] 2020-10-13 04:38
Just after I read this issue, I accidentally keybind closed a tab with over 10-15 channels configured. So this is a vote from me.

**Comment by apa420** [comment] 2020-10-13 08:18
Duplicate of #339

**Closed by apa420** 2020-10-13 08:18 UTC
Labels: enhancement, needs triage
