### ISSUE TITLE
Reload recent-messages when reconnecting

### ISSUE THREAD

**Issue by LosFarmosCTL** [Chatterino/chatterino2#3173] opened 2021-08-16 00:10 UTC
**Describe your issue**

Might be an idea to reload message history from recent-messages when reconnecting to IRC, especially with the new JOIN limit it gets really annoying to reconnect since you lose quite a lot of messages until all open slits have regained their read connection, right now I just end up restarting Chatterino as a whole when something goes wrong with my connection, which means that the mention and whispers split history gets cleared, also pretty annoying at least for me.

Should probably be configurable in settings, since it would definitely slow down the reconnecting process and might not be a behavior every user wants/expects

**Comment by LosFarmosCTL** [comment] 2021-08-16 00:13
Another idea could be to just add an entry into the three-dot menu to reload chat history from recent-messages for a specific chat, since you probably wouldnt care about most of your open splits losing a few messages while reconnecting, but only for the ones you are actually chatting in at the moment.

**Comment by Mm2PL** [comment] 2021-08-16 09:45
Duplicate of #1308.

**Closed by Mm2PL** 2021-08-16 09:45 UTC
Labels: issue-report
