### ISSUE TITLE
Chatterino Mac restricted/possible ban evader

### ISSUE THREAD

**Issue by lenn5** [Chatterino/chatterino2#5313] opened 2024-04-10 02:27 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Chatterino Mac latest beta. I'm seeing the restricted/possible ban evader's message now but unlike Twitch chat there is nothing to say that the person is restricted, ect. Without those warnings it just looks like another person in chat. 

### Screenshots

Chatterino Mac latest beta. I'm seeing the restricted/possible ban evader's message now but unlike Twitch chat there is nothing to say that the person is restricted, ect. Without those warnings it just looks like another person in chat. 

### OS and Chatterino Version

MacOS Ventura Chatterino 2.5.0-beta.1 (commit 25a69fd1) built with Qt 6.5.0

**Comment by iProdigy** [comment] 2024-04-10 02:35
Could you take a screenshot? Does it not have a restricted label as below?

![image](https://github.com/Chatterino/chatterino2/assets/8106344/d06130b2-5638-49c8-82a8-57f5e6be9113)

**Comment by iProdigy** [comment] 2024-04-10 02:35
If you're talking about *monitored* users, that's a known area for improvement https://github.com/Chatterino/chatterino2/issues/5208

**Comment by lenn5** [comment] 2024-04-10 02:46
You are right. Sorry for the mix up. Btw. the warning for possible ban evader is included in restricted right?
thx

**Comment by iProdigy** [comment] 2024-04-10 02:48
Yes, when the user is restricted, the label also indicates their ban evasion evaluation & the number of shared channels in which they are also banned https://github.com/Chatterino/chatterino2/pull/5056/files#diff-a61469571f1ced2559899f109781be679b0a705e22a97ca651a8b40973d4e726R2046-R2069

**Comment by lenn5** [comment] 2024-04-10 03:22
Thank you for your help!

**Comment by Felanbird** [comment] 2024-04-10 03:23
Duplicate of #5208

**Closed by Felanbird** 2024-04-10 03:23 UTC
Labels: issue-report
