### ISSUE TITLE
Chatterino Nightly Debian/Ubuntu does nothing.

### ISSUE THREAD

**Issue by aknight2015** [Chatterino/chatterino2#3825] opened 2022-06-21 14:16 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I install using the .deb file. I've tried both versions of the install, and nothing happens. No icon, no binary to execute in the terminal.

### OS and Chatterino Version

Chatterino 2.3.5 (commit 9583b4965 modified) built with Qt 5.15.2 Running on Debian GNU/Linux 11 (bullseye), kernel: 5.10.110-15808-ge5740beba59b

**Comment by Mm2PL** [comment] 2022-06-21 14:50
Sorry the deb package is fucked. I've not been able to fix it properly. Try the other build system (qmake vs cmake), one works more than the other. I've honestly been thinking of just deleting ubuntu/debian packaging. 

Duplicate of #3245.

**Closed by Mm2PL** 2022-06-21 14:50 UTC
Labels: issue-report
