### ISSUE TITLE
FFZ emotes not showing

### ISSUE THREAD

**Issue by HajleSellasje** [Chatterino/chatterino2#4431] opened 2023-03-04 23:26 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I don't see any ffz emotes in any channel.
Reconnecting, or reloading emotes didn't work. Reinstalling also unsuccesful.

![](https://i.imgur.com/ZKQnbWN.png)

![](https://i.imgur.com/rwK8yNr.png)

![](https://i.imgur.com/zRU5uEB.png)

### OS and Chatterino Version

Chatterino 2.4.1 (commit 5ed4a21d) built with Qt 5.15.2, Windows SDK, MSVC 193431942, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19045

**Comment by Felanbird** [comment] 2023-03-04 23:27
Duplicate of #4430

**Comment by Mm2PL** [comment] 2023-03-04 23:27
FFZ issue, they changed the api in a way that broke our implementation

**Closed by Felanbird** 2023-03-04 23:27 UTC
Labels: issue-report
