### ISSUE TITLE
ENHANCEMENT - 7TV emotes support 

### ISSUE THREAD

**Issue by Nerxxy** [Chatterino/chatterino2#3523] opened 2022-01-17 15:05 UTC
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

add 7TV emote support 👍 

### OS and Chatterino Version

Chatterino 2.3.4 (commit 4e5170799) Windows 10 21H2

**Comment by Mm2PL** [comment] 2022-01-17 15:06
Duplicate of https://github.com/Chatterino/chatterino2/discussions/2827

**Closed by Mm2PL** 2022-01-17 15:06 UTC
Labels: issue-report
